# -*- coding: utf-8 -*-
"""生成 test_case_inventory.csv"""
import csv, os

rows = []

def add(module, feature, test_file, test_case, level, rule, perm, tenant, status, result, risk, notes=''):
    rows.append([module, feature, test_file, test_case, level, rule, perm, tenant, status, result, risk, notes])

# department_duty_log
for tc, level, rule, perm, tenant, risk, notes in [
    ('test_create_success','normal','创建值班日志成功','add','False','low',''),
    ('test_create_missing_duty_date','boundary','缺少值班日期应失败','add','False','low',''),
    ('test_create_missing_duty_person','boundary','缺少值班人应失败','add','False','low',''),
    ('test_create_missing_department','boundary','缺少部门应失败','add','False','low',''),
    ('test_edit_draft_success','normal','编辑草稿成功','edit','False','low',''),
    ('test_edit_nonexistent','boundary','编辑不存在记录','edit','False','low',''),
    ('test_delete_draft_success','normal','删除草稿成功（软删除）','del','False','low',''),
    ('test_delete_nonexistent','boundary','删除不存在记录','del','False','low',''),
    ('test_list_default','normal','列表返回记录','view','False','low',''),
    ('test_list_pagination','normal','分页正确','view','False','low',''),
    ('test_list_filter_by_duty_person','normal','按值班人筛选','view','False','low',''),
    ('test_list_filter_by_date_range','normal','日期区间筛选','view','False','low',''),
    ('test_list_empty_result','normal','空结果','view','False','low',''),
    ('test_detail_success','normal','详情返回完整数据','view','False','low',''),
    ('test_detail_nonexistent','boundary','不存在记录详情','view','False','low',''),
    ('test_view_with_permission','normal','有view权限可列表','view','False','low',''),
    ('test_view_without_permission','normal','无权限不可列表','','False','medium',''),
    ('test_add_without_permission','normal','无add权限不可创建','','False','medium',''),
    ('test_supper_bypasses_permission','normal','超级管理员绕过权限','supper','False','low',''),
    ('test_cross_tenant_list_isolation','normal','租户隔离列表','view','True','high',''),
    ('test_cross_tenant_delete_blocked','normal','跨租户删除被拒','del','True','high',''),
    ('test_supper_sees_all_tenants','normal','超级管理员可见全部','supper','True','medium',''),
    ('test_signed_record_edit_blocked','normal','已签署记录不可编辑','edit','False','high',''),
    ('test_signed_record_delete_blocked','normal','已签署记录不可删除','del','False','high',''),
    ('test_signed_visible_to_all','normal','已签署记录对所有用户可见','view','False','medium',''),
    ('test_return_to_draft','normal','退回已签署记录变为草稿','edit','False','high',''),
    ('test_duplicate_within_window_blocked','normal','30秒窗口内重复提交被拦截','add','False','high',''),
    ('test_different_person_allows','normal','不同值班人可同时创建','add','False','low',''),
    ('test_options_returns_users','normal','选项返回用户列表','view','False','low',''),
    ('test_options_returns_departments','normal','选项返回部门列表','view','False','low',''),
    ('test_duty_dates_returns_dates','normal','返回值班日期列表','view','False','low',''),
    ('test_same_tenant_user_can_view_others','normal','同租户用户可查看他人记录','view','False','medium',''),
    ('test_same_tenant_user_can_delete_others','normal','同租户用户可删除他人记录','del','False','medium',''),
    ('test_created_by_set_on_create','normal','创建时设置created_by','add','False','low',''),
    ('test_created_at_set_on_create','normal','创建时设置created_at','add','False','low',''),
]:
    add('department_duty_log','记录CRUD' if 'list' not in tc and 'detail' not in tc and 'options' not in tc and 'duty_dates' not in tc else '列表查询','test_department_duty_log.py',tc,level,rule,perm,tenant,'pass','pass',risk,notes)

# duty
for tc, level, rule, perm, tenant, risk, notes in [
    ('test_create_success','normal','创建值班日志成功','add','False','low',''),
    ('test_create_minimal_fields','normal','仅必填字段创建','add','False','low',''),
    ('test_create_missing_duty_person','boundary','缺少duty_person应失败','add','False','low',''),
    ('test_create_missing_department','boundary','缺少department应失败','add','False','low',''),
    ('test_create_missing_duty_date','boundary','缺少duty_date应失败','add','False','low',''),
    ('test_create_reporter_not_from_client','normal','reporter自动填充不信任客户端','add','False','high',''),
    ('test_edit_success','defect','编辑成功（DUTY-001）','edit','False','high','生产Bug: timezone UnboundLocalError [expected_failure]'),
    ('test_edit_partial_update','defect','部分更新（DUTY-001）','edit','False','high','同上 [expected_failure]'),
    ('test_edit_nonexistent_record','boundary','编辑不存在记录','edit','False','low',''),
    ('test_delete_via_post_action','normal','POST action=delete删除','del','False','low',''),
    ('test_delete_via_delete_method','normal','DELETE方法删除','del','False','low',''),
    ('test_delete_nonexistent','boundary','删除不存在记录','del','False','low',''),
    ('test_view_with_permission','normal','有view权限可列表','view','False','low',''),
    ('test_view_without_permission','normal','无权限不可列表','','False','medium',''),
    ('test_add_without_permission','normal','无add权限不可创建','','False','medium',''),
    ('test_add_with_permission','normal','有add权限可创建','add','False','low',''),
    ('test_supper_bypasses_permission','normal','超级管理员绕过权限','supper','False','low',''),
    ('test_cross_tenant_list_isolation','normal','租户隔离列表','view','True','high',''),
    ('test_cross_tenant_delete_blocked','normal','跨租户删除被拒','del','True','high',''),
    ('test_supper_sees_all_tenants','normal','超级管理员可见全部','supper','True','medium',''),
    ('test_tenant_id_not_from_client','normal','tenant_id不信任客户端','add','True','high',''),
    ('test_soft_delete_excludes_from_list','normal','软删除后不出现在列表','view','False','high',''),
    ('test_soft_delete_preserves_db_record','normal','软删除后DB记录保留','view','False','medium',''),
    ('test_double_delete','boundary','重复删除已删除记录','del','False','low',''),
    ('test_duplicate_within_window_blocked','normal','30秒窗口内重复提交被拦截','add','False','high',''),
    ('test_different_person_allows','normal','不同duty_person可同时创建','add','False','low',''),
    ('test_list_default_order','normal','默认按duty_date倒序','view','False','low',''),
    ('test_list_pagination','normal','分页正确','view','False','low',''),
    ('test_list_returns_duty_persons','normal','返回去重duty_persons','view','False','low',''),
    ('test_list_returns_departments','normal','返回去重departments','view','False','low',''),
    ('test_list_no_keyword_search','boundary','列表API无keyword搜索','view','False','medium','BIZ-001'),
    ('test_same_tenant_user_can_view_others','normal','同租户用户可查看他人记录','view','False','medium',''),
    ('test_same_tenant_user_can_delete_others','normal','同租户用户可删除他人记录','del','False','medium',''),
    ('test_empty_duty_situation','normal','空duty_situation允许','add','False','low',''),
    ('test_past_date_allowed','normal','允许补录历史日志','add','False','medium',''),
    ('test_future_date_allowed','normal','允许创建未来日期日志','add','False','medium',''),
    ('test_created_by_set_on_create','normal','创建时设置created_by','add','False','low',''),
    ('test_created_at_set_on_create','normal','创建时设置created_at','add','False','low',''),
    ('test_updated_at_set_on_edit','defect','编辑时设置updated_at（DUTY-001）','edit','False','high','生产Bug [expected_failure]'),
]:
    result = 'expected_failure' if 'expected_failure' in notes else 'pass'
    add('duty','CRUD','test_duty.py',tc,level,rule,perm,tenant,'pass',result,risk,notes)

# runlog
for tc, level, rule, perm, tenant, risk, notes in [
    ('test_create_event_success','normal','创建事件成功（含首次动态）','add','False','low',''),
    ('test_create_missing_title','boundary','缺少event_title','add','False','low',''),
    ('test_create_missing_event_type','boundary','缺少event_type','add','False','low',''),
    ('test_create_missing_system_name','boundary','缺少system_name','add','False','low',''),
    ('test_create_invalid_severity','boundary','非法severity','add','False','low',''),
    ('test_create_without_first_update','boundary','缺少首次动态','add','False','low',''),
    ('test_create_default_severity','normal','默认severity为P2','add','False','low',''),
    ('test_edit_event_fields','normal','编辑事件字段','edit','False','low',''),
    ('test_edit_nonexistent_event','boundary','编辑不存在事件','edit','False','low',''),
    ('test_delete_event_soft_delete','normal','删除事件是软删除','del','False','high',''),
    ('test_delete_event_cascade_updates','normal','删除事件级联删除动态','del','False','high',''),
    ('test_delete_nonexistent','boundary','删除不存在事件','del','False','low',''),
    ('test_in_progress_to_resolved','normal','in_progress->resolved','edit','False','high',''),
    ('test_resolved_to_verified','normal','resolved->verified','edit','False','high',''),
    ('test_verified_to_closed','defect','verified->closed（RUNLOG-001）','edit','False','high','生产Bug: datetime序列化 [expected_failure]'),
    ('test_closed_to_voided','normal','closed->voided','edit','False','high',''),
    ('test_illegal_in_progress_to_verified','boundary','非法in_progress->verified','edit','False','high',''),
    ('test_illegal_in_progress_to_closed','boundary','非法in_progress->closed','edit','False','high',''),
    ('test_illegal_resolved_to_voided','boundary','非法resolved->voided','edit','False','high',''),
    ('test_illegal_voided_to_anything','boundary','voided后不可流转','edit','False','high',''),
    ('test_resolved_back_to_in_progress','normal','resolved->in_progress回退','edit','False','medium',''),
    ('test_verified_back_to_in_progress','normal','verified->in_progress回退','edit','False','medium',''),
    ('test_closed_with_resolution','defect','关闭时填写处理措施（RUNLOG-001）','edit','False','high','生产Bug [expected_failure]'),
    ('test_closed_sets_snapshot_hash','defect','关闭时设置快照哈希（RUNLOG-001）','edit','False','high','生产Bug [expected_failure]'),
    ('test_add_update_success','normal','添加动态成功','update_add','False','low',''),
    ('test_add_update_missing_content','boundary','缺少detail_content','update_add','False','low',''),
    ('test_add_update_nonexistent_event','boundary','添加动态到不存在事件','update_add','False','low',''),
    ('test_add_multiple_updates_sequence','normal','同一天多次动态序号递增','update_add','False','medium',''),
    ('test_edit_update_within_24h','defect','24小时内编辑动态（RUNLOG-002）','update_edit','False','high','生产Bug: duty_person NOT NULL [expected_failure]'),
    ('test_edit_update_expired','boundary','超过24小时不能编辑','update_edit','False','medium',''),
    ('test_edit_update_by_non_creator','normal','非创建者不能编辑动态','update_edit','False','medium',''),
    ('test_delete_update','normal','删除动态','update_del','False','low',''),
    ('test_delete_update_updates_dates','normal','删除动态后更新日期统计','update_del','False','medium',''),
    ('test_view_with_permission','normal','有view权限可列表','view','False','low',''),
    ('test_view_without_permission','normal','无权限不可列表','','False','medium',''),
    ('test_add_without_permission','normal','无add权限不可创建','','False','medium',''),
    ('test_supper_bypasses_permission','normal','超级管理员绕过权限','supper','False','low',''),
    ('test_cross_tenant_list_isolation','normal','租户隔离列表','view','True','high',''),
    ('test_cross_tenant_edit_blocked','normal','跨租户编辑被拒','edit','True','high',''),
    ('test_cross_tenant_delete_blocked','normal','跨租户删除被拒','del','True','high',''),
    ('test_cross_tenant_detail_blocked','normal','跨租户详情被拒','view','True','high',''),
    ('test_cross_tenant_add_update_blocked','normal','跨租户添加动态被拒','update_add','True','high',''),
    ('test_supper_sees_all_tenants','normal','超级管理员可见全部','supper','True','medium',''),
    ('test_duplicate_event_blocked','normal','30秒内重复提交相同事件被拦截','add','False','high',''),
    ('test_different_title_allows','normal','不同标题可创建','add','False','low',''),
    ('test_list_default_order','normal','默认按created_at倒序','view','False','low',''),
    ('test_filter_by_status','normal','按状态筛选','view','False','low',''),
    ('test_filter_by_severity','normal','按级别筛选','view','False','low',''),
    ('test_filter_by_system_name','normal','按系统名称筛选','view','False','low',''),
    ('test_pagination','normal','分页','view','False','low',''),
    ('test_empty_result','normal','空结果','view','False','low',''),
    ('test_returns_system_names','normal','返回系统名称列表','view','False','low',''),
    ('test_soft_delete_excludes_from_list','normal','软删除后不出现在列表','view','False','high',''),
    ('test_deleted_event_edit_blocked','normal','已删除事件不能编辑','edit','False','medium',''),
    ('test_statistics_returns_data','normal','统计接口返回数据','view','False','low',''),
    ('test_statistics_empty_data','normal','空数据统计','view','False','low',''),
    ('test_detail_returns_updates','normal','详情返回动态列表','view','False','low',''),
    ('test_detail_nonexistent','boundary','不存在事件详情','view','False','low',''),
    ('test_get_event_types','normal','获取事件类型列表','supper','False','low',''),
    ('test_create_event_type_supper','normal','超级管理员创建事件类型','supper','False','low',''),
    ('test_create_event_type_normal_blocked','normal','普通用户不能创建事件类型','','False','medium',''),
    ('test_create_duplicate_name','boundary','重复名称','supper','False','low',''),
]:
    result = 'expected_failure' if 'expected_failure' in notes else 'pass'
    add('runlog','事件CRUD','test_runlog.py',tc,level,rule,perm,tenant,'pass',result,risk,notes)

# reminder
for tc, level, rule, perm, tenant, risk, notes in [
    ('test_create_success','normal','创建提醒成功','add','False','low',''),
    ('test_create_missing_name','boundary','缺少name','add','False','low',''),
    ('test_create_missing_target_date','boundary','缺少target_date','add','False','low',''),
    ('test_create_missing_recipient_users','boundary','缺少recipient_users','add','False','low',''),
    ('test_create_empty_recipient_users','boundary','空接收人列表','add','False','low',''),
    ('test_create_invalid_target_date_format','boundary','目标日格式错误','add','False','low',''),
    ('test_create_invalid_repeat_type','boundary','非法重复类型','add','False','low',''),
    ('test_create_invalid_repeat_interval','boundary','重复间隔<1','add','False','low',''),
    ('test_create_default_repeat_type','normal','默认repeat_type为none','add','False','low',''),
    ('test_edit_success','normal','编辑提醒成功','edit','False','low',''),
    ('test_edit_nonexistent','boundary','编辑不存在提醒','edit','False','low',''),
    ('test_delete_success','normal','删除提醒（软删除）','delete','False','high',''),
    ('test_delete_nonexistent','boundary','删除不存在提醒','delete','False','low',''),
    ('test_list_returns_all','normal','列表返回所有未删除','view','False','low',''),
    ('test_list_excludes_deleted','normal','列表不包含已删除','view','False','high',''),
    ('test_detail_success','normal','详情','view','False','low',''),
    ('test_detail_nonexistent','boundary','详情不存在','view','False','low',''),
    ('test_view_with_permission','normal','有view权限可列表','view','False','low',''),
    ('test_view_without_permission','normal','无权限不可列表','','False','medium',''),
    ('test_add_without_permission','normal','无add权限不可创建','','False','medium',''),
    ('test_delete_without_permission','normal','无delete权限不可删除','','False','medium',''),
    ('test_supper_bypasses_permission','normal','超级管理员绕过权限','supper','False','low',''),
    ('test_pending_no_permission_required','normal','pending不需管理权限','','False','medium',''),
    ('test_ack_no_permission_required','normal','ack不需管理权限','','False','medium',''),
    ('test_cross_tenant_list_isolation','normal','租户隔离列表','view','True','high',''),
    ('test_cross_tenant_edit_blocked','normal','跨租户编辑被拒','edit','True','high',''),
    ('test_cross_tenant_delete_blocked','normal','跨租户删除被拒','delete','True','high',''),
    ('test_cross_tenant_detail_blocked','normal','跨租户详情被拒','view','True','high',''),
    ('test_supper_sees_all_tenants','normal','超级管理员可见全部','supper','True','medium',''),
    ('test_none_matches_on_target_date','normal','none仅target_date当天匹配','','False','high',''),
    ('test_none_before_target_date','normal','none:target_date之前不匹配','','False','medium',''),
    ('test_daily_interval_1','normal','daily interval=1每天匹配','','False','high',''),
    ('test_daily_interval_3','normal','daily interval=3每3天匹配','','False','high',''),
    ('test_weekly_interval_1','normal','weekly interval=1每7天匹配','','False','high',''),
    ('test_monthly_interval_1','normal','monthly interval=1每月同日匹配','','False','high',''),
    ('test_yearly_interval_1','normal','yearly interval=1每年同月同日匹配','','False','high',''),
    ('test_pending_creates_log','normal','pending懒创建ReminderLog','','False','high',''),
    ('test_pending_idempotent','normal','重复调用pending不创建重复log','','False','high',''),
    ('test_pending_excludes_disabled','normal','已禁用提醒不出现在pending','','False','high',''),
    ('test_pending_excludes_deleted','normal','已删除提醒不出现在pending','','False','high',''),
    ('test_pending_excludes_not_recipient','normal','非接收人不出现在pending','','False','high',''),
    ('test_pending_excludes_non_matching_date','normal','非匹配日期不出现在pending','','False','high',''),
    ('test_pending_excludes_acked','normal','已确认的log不出现在pending','','False','high',''),
    ('test_ack_success','normal','确认成功','','False','low',''),
    ('test_ack_by_non_owner','normal','非接收人不能确认','','False','high',''),
    ('test_ack_already_acked','normal','重复确认','','False','medium',''),
    ('test_ack_nonexistent_log','boundary','确认不存在的log','','False','low',''),
    ('test_ack_missing_log_id','boundary','缺少log_id','','False','low',''),
    ('test_status_returns_matching_reminders','normal','返回今天匹配的提醒','view','False','low',''),
    ('test_status_shows_ack_status','normal','显示确认状态','view','False','medium',''),
    ('test_status_no_matching','normal','无匹配提醒','view','False','low',''),
    ('test_status_without_permission','normal','无权限不能查看status','','False','medium',''),
    ('test_users_returns_active','normal','返回活跃用户','view','False','low',''),
    ('test_users_excludes_inactive','normal','不返回非活跃用户','view','False','low',''),
    ('test_users_without_permission','normal','无权限不能查看users','','False','medium',''),
    ('test_duplicate_reminder_allowed','normal','相同提醒可重复创建（无幂等检查）','add','False','medium','BIZ-005'),
    ('test_soft_delete_excludes_from_list','normal','软删除后不出现在列表','view','False','high',''),
    ('test_soft_delete_preserves_db_record','normal','软删除后DB记录保留','view','False','medium',''),
    ('test_double_delete','boundary','重复删除已删除提醒','delete','False','low',''),
    ('test_deleted_reminder_logs_preserved','normal','软删除后log保留不级联删除','delete','False','high',''),
]:
    add('reminder','CRUD','test_reminder.py',tc,level,rule,perm,tenant,'pass','pass',risk,notes)

# announcement
for tc, level, rule, perm, tenant, risk, notes in [
    ('test_create_draft_success','normal','创建草稿成功','add','False','low',''),
    ('test_create_missing_title','boundary','缺少标题','add','False','low',''),
    ('test_create_missing_content','boundary','缺少内容','add','False','low',''),
    ('test_create_missing_scope_type','boundary','缺少scope_type','add','False','low',''),
    ('test_create_invalid_scope_type','boundary','非法scope_type','add','False','low',''),
    ('test_create_tenant_scope_without_targets','boundary','指定部门范围但未选部门','add','False','medium',''),
    ('test_create_with_invalid_tenant_ids','boundary','无效部门ID','add','False','medium',''),
    ('test_create_missing_effective_start','boundary','缺少生效开始时间','add','False','low',''),
    ('test_create_end_before_start','boundary','结束时间早于开始时间','add','False','low',''),
    ('test_edit_draft_success','normal','编辑草稿成功','edit','False','low',''),
    ('test_edit_published_blocked','normal','已发布不能直接编辑','edit','False','high',''),
    ('test_edit_nonexistent','boundary','编辑不存在公告','edit','False','low',''),
    ('test_delete_success','normal','删除公告（软删除）','delete','False','high',''),
    ('test_delete_published_auto_withdraw','normal','删除已发布先自动撤回','delete','False','high',''),
    ('test_delete_nonexistent','boundary','删除不存在公告','delete','False','low',''),
    ('test_admin_detail_success','normal','管理端详情','view','False','low',''),
    ('test_admin_detail_nonexistent','boundary','详情不存在','view','False','low',''),
    ('test_publish_success','normal','发布成功','publish','False','high',''),
    ('test_publish_already_published','boundary','重复发布','publish','False','medium',''),
    ('test_publish_nonexistent','boundary','发布不存在公告','publish','False','low',''),
    ('test_withdraw_success','normal','撤回成功','withdraw','False','high',''),
    ('test_withdraft_unpublished','boundary','撤回未发布公告','withdraw','False','medium',''),
    ('test_withdraw_then_republish','normal','撤回后重新发布','publish','False','high',''),
    ('test_scope_all_visible_to_all_tenants','normal','全平台公告对所有租户可见','','True','high',''),
    ('test_scope_tenant_only_visible_to_target','normal','指定部门公告仅目标租户可见','','True','high',''),
    ('test_unpublished_not_visible','normal','未发布公告不可见','','False','high',''),
    ('test_deleted_not_visible','normal','已删除公告不可见','','False','high',''),
    ('test_future_start_not_visible','normal','未来生效公告不可见','','False','high',''),
    ('test_expired_not_visible','normal','已过期公告不可见','','False','high',''),
    ('test_detail_auto_mark_read','normal','详情自动标记已读','','False','medium',''),
    ('test_manual_mark_read','normal','手动标记已读','','False','low',''),
    ('test_mark_read_idempotent','normal','重复标记已读幂等','','False','medium',''),
    ('test_detail_not_visible_to_non_target','normal','非目标租户不能查看详情','','True','high',''),
    ('test_unread_count','normal','未读数量','','False','low',''),
    ('test_unread_count_after_read','normal','标记已读后未读减少','','False','low',''),
    ('test_reminders_returns_unread','normal','reminders返回未读公告','','False','low',''),
    ('test_reminders_excludes_read','normal','reminders不返回已读','','False','low',''),
    ('test_read_status_filter','normal','按已读状态筛选','','False','low',''),
    ('test_admin_view_with_permission','normal','有view权限可列表','view','False','low',''),
    ('test_admin_view_without_permission','normal','无权限不能访问管理端','','False','medium',''),
    ('test_add_without_permission','normal','无add权限不能创建','','False','medium',''),
    ('test_publish_without_permission','normal','无publish权限不能发布','','False','medium',''),
    ('test_withdraw_without_permission','normal','无withdraw权限不能撤回','','False','medium',''),
    ('test_delete_without_permission','normal','无delete权限不能删除','','False','medium',''),
    ('test_user_list_no_permission_required','normal','用户端列表仅需登录','','False','medium',''),
    ('test_supper_bypasses_permission','normal','超级管理员绕过权限','supper','False','low',''),
    ('test_list_default','normal','列表默认返回所有未删除','view','False','low',''),
    ('test_filter_by_status','normal','按状态筛选','view','False','low',''),
    ('test_search_by_keyword','normal','关键词搜索','view','False','low',''),
    ('test_pagination','normal','分页','view','False','low',''),
    ('test_excludes_deleted','normal','不包含已删除','view','False','high',''),
    ('test_admin_list_no_tenant_filter','normal','管理端列表不过滤租户','view','True','high','BIZ-003'),
    ('test_admin_delete_cross_tenant','normal','管理端可跨租户删除','delete','True','high','BIZ-003'),
    ('test_admin_edit_cross_tenant','normal','管理端可跨租户编辑','edit','True','high','BIZ-003'),
    ('test_get_departments','normal','获取部门列表','view','False','low',''),
    ('test_no_scheduled_publish_field','normal','当前无定时发布功能','add','False','low','BIZ-006'),
    ('test_future_effective_start_not_auto_published','normal','未来生效但不自动发布','add','False','low',''),
]:
    add('announcement','草稿CRUD','test_announcement.py',tc,level,rule,perm,tenant,'pass','pass',risk,notes)

out_dir = os.path.dirname(os.path.abspath(__file__))
out_path = os.path.join(out_dir, 'test_case_inventory.csv')
with open(out_path, 'w', newline='', encoding='utf-8-sig') as f:
    w = csv.writer(f)
    w.writerow(['module','page_or_feature','test_file','test_case','test_level','business_rule','permission_role','tenant_related','status','result','risk_level','notes'])
    w.writerows(rows)

print(f'Generated {len(rows)} rows -> {out_path}')
