# Generated by Django 4.2.30 on 2026-07-11 19:50

from django.db import migrations, models
import django.db.models.deletion
import libs.tenant_base_model
import libs.utils


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('title', models.CharField(help_text='公告标题', max_length=200)),
                ('content', models.TextField(help_text='公告内容（首期纯文本）')),
                ('scope_type', models.CharField(choices=[('all', '全平台'), ('tenant', '指定部门')], default='all', help_text='发布范围', max_length=20)),
                ('publish_department_id', models.CharField(default='', help_text='发布部门ID（首期对应 Tenant.id）', max_length=50)),
                ('publish_department_name', models.CharField(default='', help_text='发布部门名称快照', max_length=100)),
                ('effective_start_at', models.CharField(default=libs.utils.human_datetime, help_text='生效开始时间', max_length=20)),
                ('effective_end_at', models.CharField(default='', help_text='生效结束时间，空表示长期有效', max_length=20)),
                ('status', models.CharField(choices=[('unpublished', '未发布'), ('published', '已发布'), ('expired', '已过期')], default='unpublished', help_text='存储状态', max_length=20)),
                ('published_at', models.CharField(default='', help_text='实际发布时间', max_length=20)),
                ('published_by_id', models.IntegerField(blank=True, help_text='发布人ID', null=True)),
                ('published_by_name', models.CharField(default='', help_text='发布人姓名快照', max_length=100)),
                ('withdrawn_at', models.CharField(default='', help_text='撤回时间', max_length=20)),
                ('withdrawn_by_id', models.IntegerField(blank=True, help_text='撤回人ID', null=True)),
                ('withdrawn_by_name', models.CharField(default='', help_text='撤回人姓名快照', max_length=100)),
                ('is_important', models.BooleanField(default=False, help_text='是否重要')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标识')),
                ('created_at', models.CharField(default=libs.utils.human_datetime, help_text='创建时间', max_length=20)),
                ('created_by_id', models.IntegerField(blank=True, help_text='创建人ID', null=True)),
                ('created_by_name', models.CharField(default='', help_text='创建人姓名快照', max_length=100)),
                ('updated_at', models.CharField(default='', help_text='更新时间', max_length=20)),
                ('updated_by_id', models.IntegerField(blank=True, help_text='更新人ID', null=True)),
                ('updated_by_name', models.CharField(default='', help_text='更新人姓名快照', max_length=100)),
                ('deleted_at', models.CharField(default='', help_text='删除时间', max_length=20)),
                ('deleted_by_id', models.IntegerField(blank=True, help_text='删除人ID', null=True)),
                ('deleted_by_name', models.CharField(default='', help_text='删除人姓名快照', max_length=100)),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'tdyw_announcements',
                'ordering': ('-published_at', '-id'),
            },
            bases=(models.Model, libs.tenant_base_model.TenantModelMixin),
        ),
        migrations.CreateModel(
            name='AnnouncementScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('tenant_name', models.CharField(default='', help_text='目标部门/租户名称快照', max_length=100)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, help_text='创建时间', max_length=20)),
                ('announcement', models.ForeignKey(help_text='公告', on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='home.announcement')),
            ],
            options={
                'verbose_name': '公告发布范围',
                'verbose_name_plural': '公告发布范围',
                'db_table': 'tdyw_announcement_scopes',
                'ordering': ('id',),
            },
            bases=(models.Model, libs.tenant_base_model.TenantModelMixin),
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('user_id', models.IntegerField(help_text='用户ID')),
                ('username', models.CharField(default='', help_text='登录账号快照', max_length=100)),
                ('nickname', models.CharField(default='', help_text='姓名快照', max_length=100)),
                ('read_at', models.CharField(default=libs.utils.human_datetime, help_text='阅读时间', max_length=20)),
                ('announcement', models.ForeignKey(help_text='公告', on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='home.announcement')),
            ],
            options={
                'verbose_name': '公告已读',
                'verbose_name_plural': '公告已读',
                'db_table': 'tdyw_announcement_reads',
                'ordering': ('-read_at', '-id'),
            },
            bases=(models.Model, libs.tenant_base_model.TenantModelMixin),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', 'published_at', 'id'], name='ann_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['scope_type', 'status'], name='ann_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['publish_department_id', 'published_at'], name='ann_pub_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['effective_start_at', 'effective_end_at'], name='ann_effective_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_deleted', 'status'], name='ann_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementscope',
            index=models.Index(fields=['tenant_id'], name='ann_scope_tenant_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementscope',
            constraint=models.UniqueConstraint(fields=('announcement_id', 'tenant_id'), name='uniq_announcement_scope_tenant'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['user_id', 'announcement_id'], name='ann_read_user_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['announcement_id', 'user_id'], name='ann_read_notice_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementread',
            constraint=models.UniqueConstraint(fields=('announcement_id', 'user_id'), name='uniq_announcement_read_user'),
        ),
    ]
