# Generated by Django 4.2.30 on 2026-07-22 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_announcement_id_alter_announcementread_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='删除时间', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='effective_end_at',
            field=models.DateTimeField(blank=True, help_text='生效结束时间，空表示长期有效', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='effective_start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='生效开始时间'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='实际发布时间', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='更新时间', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, help_text='撤回时间', null=True),
        ),
        migrations.AlterField(
            model_name='announcementread',
            name='read_at',
            field=models.DateTimeField(auto_now_add=True, help_text='阅读时间'),
        ),
        migrations.AlterField(
            model_name='announcementscope',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间'),
        ),
    ]
