# Generated by Django 4.2.30 on 2026-07-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['unpublished', 'published', 'expired'])), name='ann_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(check=models.Q(('scope_type__in', ['all', 'tenant'])), name='ann_scope_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(check=models.Q(('effective_end_at__gte', models.F('effective_start_at')), ('effective_end_at__isnull', True), _connector='OR'), name='ann_end_after_start'),
        ),
    ]
