# Generated by Django 4.2.30 on 2026-07-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_announcement_ann_status_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='删除时间', null=True),
        ),
        migrations.AddField(
            model_name='navigation',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='软删除标识'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='tenant_id',
            field=models.CharField(default='', help_text='租户标识', max_length=50),
        ),
        migrations.AddField(
            model_name='notice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='删除时间', null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='软删除标识'),
        ),
        migrations.AddField(
            model_name='notice',
            name='tenant_id',
            field=models.CharField(default='', help_text='租户标识', max_length=50),
        ),
    ]
