# Generated by Django 4.2.30 on 2026-07-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alert_alertread_alertread_uniq_alert_read_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alertread',
            name='uniq_alert_read_user',
        ),
        migrations.RemoveField(
            model_name='alertread',
            name='alert',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='AlertRead',
        ),
    ]
