# Generated by Django 4.2.30 on 2026-08-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_alertread_alert_delete_alert_delete_alertread'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='deleted_by_id',
            field=models.IntegerField(blank=True, help_text='删除人ID', null=True),
        ),
        migrations.AddField(
            model_name='navigation',
            name='deleted_by_name',
            field=models.CharField(default='', help_text='删除人姓名快照', max_length=100),
        ),
        migrations.AddField(
            model_name='navigation',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='更新时间', null=True),
        ),
        migrations.AddField(
            model_name='navigation',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='更新人ID', null=True),
        ),
        migrations.AddField(
            model_name='navigation',
            name='updated_by_name',
            field=models.CharField(default='', help_text='更新人姓名快照', max_length=100),
        ),
        migrations.AddField(
            model_name='notice',
            name='deleted_by_id',
            field=models.IntegerField(blank=True, help_text='删除人ID', null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='deleted_by_name',
            field=models.CharField(default='', help_text='删除人姓名快照', max_length=100),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='更新时间', null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='更新人ID', null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_by_name',
            field=models.CharField(default='', help_text='更新人姓名快照', max_length=100),
        ),
    ]
