# Generated by Django 4.2.30 on 2026-08-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_navigation_notice_audit_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
