#!/bin/bash
# Restore document-library files generated by documents_incremental_backup.sh.
# Intended to run on a Linux host that can access the Docker container tdyw.
#
# 重要：数据库备份与 documents 文件备份必须来自同一备份周期。
#       仅恢复数据库而不同步恢复对应 documents 全量包及增量包，会导致数据库记录
#       存在但物理文件缺失（前端可见但预览/下载报“文件不存在”）。
#
# 还原顺序（生产）：
#   停止业务 -> 恢复数据库 -> 清空 documents -> 恢复 full -> 恢复 incrementals
#   -> 启动业务 -> 一致性检查 -> 清理缓存

set -euo pipefail
umask 027

APP_CONTAINER="${APP_CONTAINER:-tdyw}"
DOCUMENTS_PATH="${DOCUMENTS_PATH:-/data/spug/spug_api/storage/documents}"
FULL_BACKUP_FILE="${FULL_BACKUP_FILE:-${1:-}}"
INCREMENTAL_DIR="${INCREMENTAL_DIR:-}"
APPLY_INCREMENTALS="${APPLY_INCREMENTALS:-YES}"
RESTORE_TMP_DIR="${RESTORE_TMP_DIR:-/tmp/tdyw_documents_restore_$(date +%Y%m%d_%H%M%S)}"
CLEAR_TARGET="${CLEAR_TARGET:-YES}"
FORCE_RESTORE="${FORCE_RESTORE:-NO}"

# 恢复报告相关全局变量
RESTORED_FILE_COUNT=0
INCREMENTAL_COUNT=0
MANIFEST_MISSING_COUNT=0
MANIFEST_MISSING_LIST=""
MANIFEST_EXPECTED_COUNT=0
ACTUAL_LIST_FILE=""

log() {
    printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}

usage() {
    cat <<EOF
Usage:
  FULL_BACKUP_FILE=/data/backups/tdyw/documents/full/documents_full_YYYYmmdd_HHMMSS.tar.gz \\
  INCREMENTAL_DIR=/data/backups/tdyw/documents/incremental \\
  FORCE_RESTORE=YES \\
  ./documents_restore.sh

Or:
  INCREMENTAL_DIR=/data/backups/tdyw/documents/incremental FORCE_RESTORE=YES ./documents_restore.sh /path/to/full.tar.gz

Options:
  APP_CONTAINER          Default: tdyw
  DOCUMENTS_PATH         Default: /data/spug/spug_api/storage/documents
  APPLY_INCREMENTALS     Default: YES
  INCREMENTAL_DIR        Directory that contains documents_incr_*.tar.gz
  RESTORE_TMP_DIR        Default: /tmp/tdyw_documents_restore_<timestamp>
  CLEAR_TARGET=YES       Default: YES. Clear target directory before copying restored files.
  FORCE_RESTORE=YES      Required to write into the container.

Important:
  - Database backup and documents backup MUST come from the same backup cycle.
    Restoring only the database (without matching documents full+incremental archives)
    will leave phantom records visible in the UI but fail on preview/download.
  - Incremental archives whose filename timestamp is >= the full backup's timestamp
    are applied in filename (chronological) order.
  - Without FORCE_RESTORE=YES the script only validates archives and prints the plan.
  - If a .manifest exists next to each backup archive, a post-restore verification is
    performed and a missing-file checklist is written next to the restore temp dir.
EOF
}

# 从备份文件名提取时间戳：documents_(full|incr)_YYYYmmdd_HHMMSS.tar.gz -> YYYYmmdd_HHMMSS
extract_backup_ts() {
    basename "$1" | sed -n -E 's/.*_([0-9]{8}_[0-9]{6})\.tar\.gz$/\1/p'
}

preflight() {
    if [ -z "${FULL_BACKUP_FILE}" ]; then
        usage
        exit 2
    fi
    if [ ! -f "${FULL_BACKUP_FILE}" ]; then
        log "ERROR: full backup file not found: ${FULL_BACKUP_FILE}"
        exit 1
    fi
    if ! command -v docker >/dev/null 2>&1; then
        log "ERROR: docker command not found."
        exit 1
    fi
    if [ "$(docker inspect -f '{{.State.Running}}' "${APP_CONTAINER}" 2>/dev/null || echo false)" != "true" ]; then
        log "ERROR: container ${APP_CONTAINER} is not running."
        exit 1
    fi
    if ! docker exec "${APP_CONTAINER}" test -d "${DOCUMENTS_PATH}" 2>/dev/null; then
        log "ERROR: target documents path does not exist in container: ${DOCUMENTS_PATH}"
        exit 1
    fi

    if [ -z "${INCREMENTAL_DIR}" ]; then
        INCREMENTAL_DIR="$(cd "$(dirname "${FULL_BACKUP_FILE}")/.." && pwd)/incremental"
    fi

    # 校验全量与所有增量归档完整性（在破坏目标目录之前完成）
    validate_archives
}

# 列出待应用的增量包：文件名时间戳 >= 全量包时间戳，按文件名升序（即时间顺序）
list_incrementals() {
    if [ "${APPLY_INCREMENTALS}" != "YES" ] || [ ! -d "${INCREMENTAL_DIR}" ]; then
        return 0
    fi

    local full_ts incr_ts incr
    full_ts="$(extract_backup_ts "${FULL_BACKUP_FILE}")"

    if [ -z "${full_ts}" ]; then
        # 无法解析全量时间戳，回退：列出全部增量包按文件名排序
        find "${INCREMENTAL_DIR}" -name 'documents_incr_*.tar.gz' -type f 2>/dev/null | sort
        return 0
    fi

    while IFS= read -r incr; do
        [ -z "$incr" ] && continue
        incr_ts="$(extract_backup_ts "$incr")"
        # 时间戳无法解析，或时间戳 >= 全量时间戳，则纳入
        if [ -z "$incr_ts" ] || [[ "$incr_ts" > "$full_ts" ]] || [ "$incr_ts" = "$full_ts" ]; then
            printf '%s\n' "$incr"
        fi
    done < <(find "${INCREMENTAL_DIR}" -name 'documents_incr_*.tar.gz' -type f 2>/dev/null | sort)
}

# 校验全量与增量 tar 包完整性
validate_archives() {
    log "Validating full backup archive..."
    if ! tar tzf "${FULL_BACKUP_FILE}" >/dev/null 2>&1; then
        log "ERROR: full backup archive is corrupted: ${FULL_BACKUP_FILE}"
        exit 1
    fi
    log "  OK: $(basename "${FULL_BACKUP_FILE}")"

    local incr
    while IFS= read -r incr; do
        [ -z "$incr" ] && continue
        log "Validating incremental archive: $(basename "$incr")"
        if ! tar tzf "$incr" >/dev/null 2>&1; then
            log "ERROR: incremental archive is corrupted: $incr"
            exit 1
        fi
        log "  OK"
    done < <(list_incrementals)
}

print_plan() {
    local incr_count=0 incr
    while IFS= read -r incr; do
        [ -z "$incr" ] && continue
        incr_count=$((incr_count + 1))
    done < <(list_incrementals)
    INCREMENTAL_COUNT="${incr_count}"

    log "Documents restore plan:"
    log "  container:           ${APP_CONTAINER}"
    log "  target:              ${DOCUMENTS_PATH}"
    log "  full backup:         ${FULL_BACKUP_FILE}"
    log "  temp dir:            ${RESTORE_TMP_DIR}"
    log "  clear target:        ${CLEAR_TARGET}"
    log "  apply incrementals:  ${APPLY_INCREMENTALS}"
    log "  incremental dir:     ${INCREMENTAL_DIR}"
    log "  incremental count:   ${INCREMENTAL_COUNT}"
    log "Full + incremental archives that will be used:"
    log "  - ${FULL_BACKUP_FILE}"
    if [ "${APPLY_INCREMENTALS}" = "YES" ]; then
        while IFS= read -r incr; do
            [ -z "$incr" ] && continue
            log "  - ${incr}"
        done < <(list_incrementals)
    fi
    log "Reminder: database backup and documents backup must come from the same backup cycle."
}

restore_to_temp() {
    mkdir -p "${RESTORE_TMP_DIR}"
    log "Extracting full backup -> ${RESTORE_TMP_DIR}"
    tar xzf "${FULL_BACKUP_FILE}" -C "${RESTORE_TMP_DIR}"

    if [ "${APPLY_INCREMENTALS}" = "YES" ]; then
        local incr
        while IFS= read -r incr; do
            [ -z "$incr" ] && continue
            log "Applying incremental backup (in order): ${incr}"
            tar xzf "${incr}" -C "${RESTORE_TMP_DIR}"
        done < <(list_incrementals)
    fi
}

copy_to_container() {
    if [ "${CLEAR_TARGET}" = "YES" ]; then
        log "Clearing target documents directory in container..."
        docker exec "${APP_CONTAINER}" sh -c "find '${DOCUMENTS_PATH}' -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +"
    fi

    log "Copying restored files into container..."
    docker cp "${RESTORE_TMP_DIR}/." "${APP_CONTAINER}:${DOCUMENTS_PATH}/"

    # 收集目标目录实际文件清单（相对路径），供报告与 manifest 校验复用
    ACTUAL_LIST_FILE="$(mktemp)"
    docker exec "${APP_CONTAINER}" find "${DOCUMENTS_PATH}" -type f -printf '%P\n' 2>/dev/null \
        | sort -u > "${ACTUAL_LIST_FILE}" || true
    RESTORED_FILE_COUNT="$(wc -l < "${ACTUAL_LIST_FILE}" | tr -d ' ')"
    log "Documents restore completed. File count in target: ${RESTORED_FILE_COUNT}"
}

# 收集本次将使用的全量包 + 增量包旁的 manifest 路径
collect_manifest_paths() {
    local full_base incr incr_base
    full_base="${FULL_BACKUP_FILE%.tar.gz}"

    if [ -f "${full_base}.manifest" ]; then
        printf '%s\n' "${full_base}.manifest"
    fi

    if [ "${APPLY_INCREMENTALS}" = "YES" ]; then
        while IFS= read -r incr; do
            [ -z "$incr" ] && continue
            incr_base="${incr%.tar.gz}"
            if [ -f "${incr_base}.manifest" ]; then
                printf '%s\n' "${incr_base}.manifest"
            fi
        done < <(list_incrementals)
    fi
}

# 若存在 manifest，则恢复后比对：manifest 预期文件 vs 实际存在文件
verify_manifests() {
    local manifest_list
    manifest_list="$(mktemp)"
    collect_manifest_paths > "${manifest_list}"

    if [ ! -s "${manifest_list}" ]; then
        log "No manifest found alongside backups, skipping manifest verification."
        rm -f "${manifest_list}"
        return 0
    fi

    # 汇总所有 manifest 的相对路径（第一列），去重排序
    local expected_list
    expected_list="$(mktemp)"
    local m
    while IFS= read -r m; do
        [ -z "$m" ] && continue
        cut -f1 "$m" 2>/dev/null >> "${expected_list}"
    done < "${manifest_list}"
    sort -u "${expected_list}" -o "${expected_list}"
    MANIFEST_EXPECTED_COUNT="$(wc -l < "${expected_list}" | tr -d ' ')"
    rm -f "${manifest_list}"

    # 实际文件清单（已由 copy_to_container 写入 ACTUAL_LIST_FILE）
    local actual_sorted
    actual_sorted="$(mktemp)"
    if [ -z "${ACTUAL_LIST_FILE}" ] || [ ! -s "${ACTUAL_LIST_FILE}" ]; then
        : > "${actual_sorted}"
    else
        sort -u "${ACTUAL_LIST_FILE}" -o "${actual_sorted}"
    fi

    # 缺失 = 预期中存在但实际不存在
    MANIFEST_MISSING_LIST="${RESTORE_TMP_DIR}/manifest_missing.txt"
    comm -23 "${expected_list}" "${actual_sorted}" > "${MANIFEST_MISSING_LIST}" || true
    MANIFEST_MISSING_COUNT="$(wc -l < "${MANIFEST_MISSING_LIST}" | tr -d ' ')"

    rm -f "${expected_list}" "${actual_sorted}"

    log "Manifest verification:"
    log "  expected files (union of manifests): ${MANIFEST_EXPECTED_COUNT}"
    log "  actual files in target:              ${RESTORED_FILE_COUNT}"
    log "  missing files:                       ${MANIFEST_MISSING_COUNT}"
    if [ "${MANIFEST_MISSING_COUNT}" -gt 0 ]; then
        log "  missing checklist: ${MANIFEST_MISSING_LIST}"
    else
        rm -f "${MANIFEST_MISSING_LIST}"
        MANIFEST_MISSING_LIST=""
    fi
}

print_report() {
    log "================ Restore Report ================"
    log "  full backup:            ${FULL_BACKUP_FILE}"
    log "  incremental count:      ${INCREMENTAL_COUNT}"
    log "  restored file count:    ${RESTORED_FILE_COUNT}"
    log "  manifest expected:      ${MANIFEST_EXPECTED_COUNT}"
    log "  manifest missing count: ${MANIFEST_MISSING_COUNT}"
    if [ -n "${MANIFEST_MISSING_LIST}" ]; then
        log "  missing checklist:      ${MANIFEST_MISSING_LIST}"
    fi
    log "  target path:            ${DOCUMENTS_PATH}"
    log "  temp dir:               ${RESTORE_TMP_DIR}"
    log "================================================"
    if [ "${MANIFEST_MISSING_COUNT}" -gt 0 ]; then
        log "WARNING: ${MANIFEST_MISSING_COUNT} file(s) listed in manifest are missing in target."
        log "         Inspect: ${MANIFEST_MISSING_LIST}"
        log "         Recommended: run document consistency check."
    else
        log "OK: all manifest-listed files are present in target."
    fi
}

main() {
    preflight
    print_plan

    if [ "${FORCE_RESTORE}" != "YES" ]; then
        log "Dry run only. Set FORCE_RESTORE=YES to restore files into the container."
        exit 2
    fi

    restore_to_temp
    copy_to_container
    verify_manifests
    print_report
}

main "$@"
