#!/bin/bash
# Extract and prepare a physical MariaDB backup generated by mariabackup_backup.sh.
# Full volume restore is guarded by FORCE_PHYSICAL_RESTORE=YES.

set -euo pipefail
umask 027

DB_CONTAINER="${DB_CONTAINER:-tdyw-db}"
APP_CONTAINER="${APP_CONTAINER:-tdyw}"
PHYSICAL_BACKUP_FILE="${PHYSICAL_BACKUP_FILE:-${1:-}}"
RESTORE_WORK_DIR="${RESTORE_WORK_DIR:-/tmp/tdyw_mariabackup_restore_$(date +%Y%m%d_%H%M%S)}"
DB_IMAGE="${DB_IMAGE:-}"
DB_VOLUME_NAME="${DB_VOLUME_NAME:-}"
FORCE_PHYSICAL_RESTORE="${FORCE_PHYSICAL_RESTORE:-NO}"
STOP_APP_CONTAINER="${STOP_APP_CONTAINER:-YES}"
START_AFTER_RESTORE="${START_AFTER_RESTORE:-NO}"

log() {
    printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}

usage() {
    cat <<EOF
Usage:
  PHYSICAL_BACKUP_FILE=/data/backups/tdyw/mariadb/physical/tdyw_physical_YYYYmmdd_HHMMSS.tar.gz \\
  ./mariabackup_prepare_restore.sh

Prepare only:
  ./mariabackup_prepare_restore.sh /path/to/physical.tar.gz

Full physical restore into Docker volume:
  PHYSICAL_BACKUP_FILE=/path/to/physical.tar.gz \\
  FORCE_PHYSICAL_RESTORE=YES \\
  START_AFTER_RESTORE=YES \\
  ./mariabackup_prepare_restore.sh

Options:
  DB_CONTAINER             Default: tdyw-db
  APP_CONTAINER            Default: tdyw
  DB_IMAGE                 Auto-detected from DB_CONTAINER when empty
  DB_VOLUME_NAME           Auto-detected from /var/lib/mysql mount when empty
  RESTORE_WORK_DIR         Default: /tmp/tdyw_mariabackup_restore_<timestamp>
  FORCE_PHYSICAL_RESTORE   Default: NO. Required for destructive volume restore
  STOP_APP_CONTAINER       Default: YES
  START_AFTER_RESTORE      Default: NO

Notes:
  - This script always extracts and runs mariabackup --prepare first.
  - Restoring into the Docker volume deletes current /var/lib/mysql contents.
  - Run a restore drill in a test environment before using this in production.
EOF
}

preflight() {
    if [ -z "${PHYSICAL_BACKUP_FILE}" ]; then
        usage
        exit 2
    fi
    if [ ! -f "${PHYSICAL_BACKUP_FILE}" ]; then
        log "ERROR: physical backup file not found: ${PHYSICAL_BACKUP_FILE}"
        exit 1
    fi
    if ! command -v docker >/dev/null 2>&1; then
        log "ERROR: docker command not found."
        exit 1
    fi
    tar tzf "${PHYSICAL_BACKUP_FILE}" >/dev/null
}

detect_docker_settings() {
    if [ -z "${DB_IMAGE}" ]; then
        DB_IMAGE="$(docker inspect -f '{{.Config.Image}}' "${DB_CONTAINER}")"
    fi
    if [ -z "${DB_VOLUME_NAME}" ]; then
        DB_VOLUME_NAME="$(docker inspect -f '{{range .Mounts}}{{if eq .Destination "/var/lib/mysql"}}{{.Name}}{{end}}{{end}}' "${DB_CONTAINER}")"
    fi
    if [ -z "${DB_IMAGE}" ]; then
        log "ERROR: unable to detect database image. Set DB_IMAGE manually."
        exit 1
    fi
    if [ -z "${DB_VOLUME_NAME}" ]; then
        log "ERROR: unable to detect database volume. Set DB_VOLUME_NAME manually."
        exit 1
    fi
}

extract_and_prepare() {
    mkdir -p "${RESTORE_WORK_DIR}"
    log "Extracting physical backup into: ${RESTORE_WORK_DIR}"
    tar xzf "${PHYSICAL_BACKUP_FILE}" -C "${RESTORE_WORK_DIR}"

    log "Preparing mariabackup files with image: ${DB_IMAGE}"
    docker run --rm \
        -v "${RESTORE_WORK_DIR}:/restore" \
        "${DB_IMAGE}" \
        mariabackup --prepare --target-dir=/restore

    log "Prepare completed: ${RESTORE_WORK_DIR}"
}

restore_volume() {
    if [ "${FORCE_PHYSICAL_RESTORE}" != "YES" ]; then
        log "Prepare only. Set FORCE_PHYSICAL_RESTORE=YES to overwrite the database volume."
        log "Detected DB image: ${DB_IMAGE}"
        log "Detected DB volume: ${DB_VOLUME_NAME}"
        exit 2
    fi

    log "Starting destructive physical restore."
    log "DB volume to overwrite: ${DB_VOLUME_NAME}"

    if [ "${STOP_APP_CONTAINER}" = "YES" ]; then
        docker stop "${APP_CONTAINER}" >/dev/null 2>&1 || true
    fi
    docker stop "${DB_CONTAINER}" >/dev/null 2>&1 || true

    docker run --rm \
        -v "${DB_VOLUME_NAME}:/var/lib/mysql" \
        -v "${RESTORE_WORK_DIR}:/restore" \
        "${DB_IMAGE}" \
        sh -c "rm -rf /var/lib/mysql/* && mariabackup --copy-back --target-dir=/restore && chown -R mysql:mysql /var/lib/mysql"

    log "Physical restore copied back into volume."

    if [ "${START_AFTER_RESTORE}" = "YES" ]; then
        docker start "${DB_CONTAINER}" >/dev/null
        if [ "${STOP_APP_CONTAINER}" = "YES" ]; then
            docker start "${APP_CONTAINER}" >/dev/null
        fi
        log "Containers started."
    else
        log "Containers were not restarted. Start them manually after verification:"
        log "  docker start ${DB_CONTAINER}"
        log "  docker start ${APP_CONTAINER}"
    fi
}

main() {
    preflight
    detect_docker_settings
    extract_and_prepare
    restore_volume
}

main "$@"
