#!/bin/bash
# Restore a MariaDB logical dump generated by backup_set_create.sh.
# Intended to run on a Linux host that can access the Docker container tdyw-db.
# Database credentials are read only from a 0600/0400 client cnf file.

set -euo pipefail
umask 027

DB_CONTAINER="${DB_CONTAINER:-tdyw-db}"
RESTORE_CLIENT_CNF="${RESTORE_CLIENT_CNF:-/etc/tdyw-backup/tdyw_restore.cnf}"
SOURCE_DB_NAME="${SOURCE_DB_NAME:-tdyw}"
RESTORE_DB="${RESTORE_DB:-tdyw_restore}"
BACKUP_FILE="${BACKUP_FILE:-${1:-}}"
DROP_EXISTING="${DROP_EXISTING:-NO}"
ALLOW_RESTORE_TO_PRODUCTION="${ALLOW_RESTORE_TO_PRODUCTION:-NO}"
CONTAINER_CNF=""

log() {
    printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}

usage() {
    cat <<EOF
Usage:
  BACKUP_FILE=/data/backups/tdyw/mariadb/dump/tdyw_dump_YYYYmmdd_HHMMSS.sql.gz \\
  RESTORE_DB=tdyw_restore \\
  ./mariadump_restore.sh

Or:
  RESTORE_DB=tdyw_restore ./mariadump_restore.sh /path/to/backup.sql.gz

Options:
  DB_CONTAINER                  Default: tdyw-db
  RESTORE_CLIENT_CNF            Default: /etc/tdyw-backup/tdyw_restore.cnf
  RESTORE_DB                    Default: tdyw_restore
  DROP_EXISTING=YES             Drop RESTORE_DB before importing
  ALLOW_RESTORE_TO_PRODUCTION=YES
                               Required if RESTORE_DB equals SOURCE_DB_NAME

Notes:
  - The cnf is the only username/password source and must have mode 0600 or 0400.
  - By default this script restores into tdyw_restore, not the production tdyw DB.
EOF
}

cleanup() {
    if [ -n "${CONTAINER_CNF}" ]; then
        docker exec "${DB_CONTAINER}" rm -f -- "${CONTAINER_CNF}" >/dev/null 2>&1 || true
    fi
}
trap cleanup EXIT INT TERM

preflight() {
    if [ -z "${BACKUP_FILE}" ]; then
        usage
        exit 2
    fi
    if [ ! -f "${BACKUP_FILE}" ]; then
        log "ERROR: backup file not found: ${BACKUP_FILE}"
        exit 1
    fi
    if [ ! -f "${RESTORE_CLIENT_CNF}" ] || [ ! -r "${RESTORE_CLIENT_CNF}" ]; then
        log "ERROR: restore client cnf is missing or unreadable: ${RESTORE_CLIENT_CNF}"
        exit 1
    fi
    local cnf_mode
    cnf_mode="$(stat -c '%a' "${RESTORE_CLIENT_CNF}" 2>/dev/null || true)"
    case "${cnf_mode}" in
        600|400) ;;
        *) log "ERROR: restore client cnf must have mode 0600 or 0400"; exit 1 ;;
    esac
    if ! command -v docker >/dev/null 2>&1; then
        log "ERROR: docker command not found."
        exit 1
    fi
    if [ "$(docker inspect -f '{{.State.Running}}' "${DB_CONTAINER}" 2>/dev/null || echo false)" != "true" ]; then
        log "ERROR: container ${DB_CONTAINER} is not running."
        exit 1
    fi
    if [ "${RESTORE_DB}" = "${SOURCE_DB_NAME}" ] && [ "${ALLOW_RESTORE_TO_PRODUCTION}" != "YES" ]; then
        log "ERROR: refusing to restore directly into production database '${SOURCE_DB_NAME}'."
        log "Set ALLOW_RESTORE_TO_PRODUCTION=YES only after a tested rollback plan exists."
        exit 1
    fi
    case "${BACKUP_FILE}" in
        *.gz)
            gzip -t "${BACKUP_FILE}"
            ;;
    esac
    [[ "${RESTORE_DB}" =~ ^[A-Za-z0-9_]+$ ]] || {
        log "ERROR: RESTORE_DB contains unsupported characters"
        exit 1
    }
    [[ "${SOURCE_DB_NAME}" =~ ^[A-Za-z0-9_]+$ ]] || {
        log "ERROR: SOURCE_DB_NAME contains unsupported characters"
        exit 1
    }
    CONTAINER_CNF="/tmp/tdyw_restore_$$_${RANDOM}.cnf"
    docker cp "${RESTORE_CLIENT_CNF}" "${DB_CONTAINER}:${CONTAINER_CNF}" >/dev/null
    docker exec "${DB_CONTAINER}" chmod 600 "${CONTAINER_CNF}"
    docker exec "${DB_CONTAINER}" mariadb --defaults-extra-file="${CONTAINER_CNF}" \
        --host=127.0.0.1 --port=3306 -NBe 'SELECT 1' >/dev/null
}

database_exists() {
    docker exec "${DB_CONTAINER}" mariadb \
        --defaults-extra-file="${CONTAINER_CNF}" --host=127.0.0.1 --port=3306 -N -B \
        -e "SELECT SCHEMA_NAME FROM information_schema.SCHEMATA WHERE SCHEMA_NAME='${RESTORE_DB}';" \
        | grep -qx "${RESTORE_DB}"
}

restore_dump() {
    log "Restore target database: ${RESTORE_DB}"
    log "Backup file: ${BACKUP_FILE}"

    if database_exists; then
        if [ "${DROP_EXISTING}" = "YES" ]; then
            log "Dropping existing database: ${RESTORE_DB}"
            docker exec "${DB_CONTAINER}" mariadb \
                --defaults-extra-file="${CONTAINER_CNF}" --host=127.0.0.1 --port=3306 \
                -e "DROP DATABASE \`${RESTORE_DB}\`;"
        else
            log "ERROR: database ${RESTORE_DB} already exists. Set DROP_EXISTING=YES to replace it."
            exit 1
        fi
    fi

    log "Creating database: ${RESTORE_DB}"
    docker exec "${DB_CONTAINER}" mariadb \
        --defaults-extra-file="${CONTAINER_CNF}" --host=127.0.0.1 --port=3306 \
        -e "CREATE DATABASE \`${RESTORE_DB}\` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

    log "Importing dump..."
    case "${BACKUP_FILE}" in
        *.gz)
            gzip -dc "${BACKUP_FILE}" | docker exec -i "${DB_CONTAINER}" mariadb \
                --defaults-extra-file="${CONTAINER_CNF}" --host=127.0.0.1 --port=3306 "${RESTORE_DB}"
            ;;
        *)
            docker exec -i "${DB_CONTAINER}" mariadb \
                --defaults-extra-file="${CONTAINER_CNF}" --host=127.0.0.1 --port=3306 "${RESTORE_DB}" < "${BACKUP_FILE}"
            ;;
    esac

    local table_count
    table_count="$(docker exec "${DB_CONTAINER}" mariadb \
        --defaults-extra-file="${CONTAINER_CNF}" --host=127.0.0.1 --port=3306 -N -B \
        -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${RESTORE_DB}';")"
    log "Restore completed. Table count in ${RESTORE_DB}: ${table_count}"
}

main() {
    preflight
    restore_dump
}

main "$@"
