"""
# Copyright: (c) OpenSpug Organization. https://github.com/openspug/spug
# Copyright: (c) <spug.dev@gmail.com>
# Released under the AGPL-3.0 License.

Django settings for spug project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import re

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY: Read SECRET_KEY from environment variable
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if os.environ.get('DEBUG', 'False').lower() == 'true':
        SECRET_KEY = 'dev-only-insecure-key-do-not-use-in-production'
    else:
        raise ValueError(
            "DJANGO_SECRET_KEY environment variable is required in production! "
            "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
        )

# Read from environment, default to safe values
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# Parse ALLOWED_HOSTS from environment variable (comma-separated)
_allowed_hosts = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',') if h.strip()]

# Parse ALLOWED_ORIGINS from environment variable (comma-separated)
# 用于 Origin/Referer 验证，支持多域名/多IP访问
_allowed_origins = os.environ.get('ALLOWED_ORIGINS', '')
ALLOWED_ORIGINS = [h.strip() for h in _allowed_origins.split(',') if h.strip()] if _allowed_origins else []

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'libs',
    'apps.account',
    'apps.setting',
    'apps.fault',
    'apps.duty',
    'apps.device',
    'apps.interference',
    'apps.home',
    'apps.runlog',
    'apps.document',
    'apps.upgrade',
    'apps.logs',
    'apps.radio_license',
    'apps.contract_agreement',
    'apps.evidence',
    'apps.regulation',
    'apps.signature',
    'apps.department_duty_log',
    'channels',
    'django_celery_results',  # Celery results backend
    'django_celery_beat',     # Celery Beat定时任务调度
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'libs.middleware.AuthenticationMiddleware',
    'libs.csrf_protection.OriginCheckMiddleware',  # Origin/Referer validation
    'libs.tenant_middleware.TenantMiddleware',
    'apps.logs.middleware.AuditLogMiddleware',
    'libs.middleware.HandleExceptionMiddleware',
]

ROOT_URLCONF = 'spug.urls'

WSGI_APPLICATION = 'spug.wsgi.application'
ASGI_APPLICATION = 'spug.routing.application'

# Default primary key field type
# 使用 BigAutoField（BIGINT，上限 922 亿亿）防主键溢出。
# 项目尚未进生产（2026-07-22），此时升级主键类型为零风险窗口：
# 空表/小数据 ALTER 秒级完成，进生产后永远不用再碰主键类型。
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MYSQL_DATABASE'),
        'USER': os.environ.get('MYSQL_USER'),
        'PASSWORD': os.environ.get('MYSQL_PASSWORD'),
        'HOST': os.environ.get('MYSQL_HOST'),
        'PORT': os.environ.get('MYSQL_PORT'),
        'CONN_MAX_AGE': 0,  # 【gevent兼容】禁用连接池，每个请求后关闭连接
        # 优化说明：
        # - gevent使用协程而非线程，Django默认连接池(thread-local)与协程不兼容
        # - 协程切换可能导致连接混用，引发数据混乱
        # - 设置为0确保每个请求使用独立连接，避免并发问题
        # - 后续可安装 django-db-geventpool 实现协程安全的连接池
        'OPTIONS': {
            'charset': 'utf8mb4',
            # sql_mode 与 mysqlnew.cnf 保持一致，避免 Django 连接覆盖全局配置导致保护失效
            'sql_mode': 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',
            'connect_timeout': 10,              # 连接超时10秒
            'read_timeout': 30,                 # 读超时30秒
            'write_timeout': 30,                # 写超时30秒
            'max_allowed_packet': 268435456,    # 256MB，与MySQL配置匹配（大文件上传）
        }
    }
}

# ==================== Redis 配置 ====================
# Redis connection with optional password support
_REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD', '')
_REDIS_HOST = os.environ.get('REDIS_HOST', '127.0.0.1')
_REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
_REDIS_URL = (
    f"redis://:{_REDIS_PASSWORD}@{_REDIS_HOST}:{_REDIS_PORT}"
    if _REDIS_PASSWORD
    else f"redis://{_REDIS_HOST}:{_REDIS_PORT}"
)

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{_REDIS_URL}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,
            "RETRY_ON_TIMEOUT": True,
        }
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [f"{_REDIS_URL}/0"],
            "capacity": 1000,
            "expiry": 120,
        },
    },
}

# ==================== Celery 配置 ====================
# 【核心配置】消息队列和结果后端
CELERY_BROKER_URL = f'{_REDIS_URL}/2'  # Broker（消息队列）
CELERY_RESULT_BACKEND = f'{_REDIS_URL}/3'  # Result Backend（结果存储）

# 序列化配置
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# 时区配置
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_ENABLE_UTC = True
# 【修复】禁用 Celery Beat 的时区感知，与 Django USE_TZ=False 保持一致
DJANGO_CELERY_BEAT_TZ_AWARE = False

# 任务跟踪配置
CELERY_TASK_TRACK_STARTED = True

# 结果过期时间（7天）
CELERY_RESULT_EXPIRES = 7 * 24 * 60 * 60

# Worker 并发配置
CELERY_WORKER_CONCURRENCY = 4
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# 任务执行超时配置（资料库大文件合并需要更长时间）
CELERY_TASK_SOFT_TIME_LIMIT = 600  # 软超时10分钟
CELERY_TASK_TIME_LIMIT = 900       # 硬超时15分钟

# 任务重试配置
CELERY_TASK_DEFAULT_MAX_RETRIES = 3
CELERY_TASK_DEFAULT_RETRY_DELAY = 60

# 队列路由配置
CELERY_TASK_ROUTES = {
    # 文件合并任务使用专用队列
    'apps.document.tasks.merge_file_chunks': {'queue': 'document.merge'},
    # 批量操作任务使用批处理队列
    'apps.document.tasks.batch_delete_transfers': {'queue': 'document.batch'},
    'apps.document.tasks.batch_cancel_transfers': {'queue': 'document.batch'},
    # 清理任务使用清理队列
    'apps.document.tasks.cleanup_old_chunks': {'queue': 'document.cleanup'},
    'apps.document.tasks.cleanup_expired_transfers': {'queue': 'document.cleanup'},
    # 【P0修复】待清理文件重试任务
    'apps.document.tasks.cleanup.retry_clean_pending_files': {'queue': 'document.cleanup'},
    # 【优化10】孤儿传输记录清理
    'apps.document.tasks.cleanup.orphan_transfers.cleanup_orphan_transfers': {'queue': 'document.cleanup'},
    # 【缩略图异步化】缩略图生成任务使用专用队列，避免 Pillow 吃 CPU 拖慢上传/合并
    # 由独立 thumbnail worker（start-celery-thumbnail.sh）消费
    # 若未部署独立 worker，需让 cleanup/default worker 兼听 document.thumbnail 队列
    'apps.document.tasks.thumbnail.generate_document_thumbnail': {'queue': 'document.thumbnail'},
    # 【新增】无线电台执照到期扫描任务
    'apps.radio_license.tasks.scan_radio_license_expiration': {'queue': 'radio_license'},
    'apps.contract_agreement.tasks.scan_contract_agreement_expiration': {'queue': 'contract_agreement'},
    # 【新增】审计日志归档清理任务（使用 default 队列）
    'apps.logs.tasks.cleanup_old_audit_logs': {'queue': 'default'},
}

# 【P0修复】Celery Beat 定时任务配置
from celery.schedules import crontab
from apps.document.celery_beat_schedule import DOCUMENT_BEAT_SCHEDULE
from apps.radio_license.celery_beat_schedule import RADIO_LICENSE_BEAT_SCHEDULE
from apps.contract_agreement.celery_beat_schedule import CONTRACT_AGREEMENT_BEAT_SCHEDULE
from apps.logs.celery_beat_schedule import LOGS_BEAT_SCHEDULE
from apps.home.celery_beat_schedule import HOME_BEAT_SCHEDULE

CELERY_BEAT_SCHEDULE = {
    # 每小时重试清理标记为待清理的物理文件（上传链路，非回收站）
    'retry-clean-pending-files': {
        'task': 'apps.document.tasks.cleanup.retry_clean_pending_files',
        'schedule': 3600.0,  # 每小时执行一次
        'options': {'queue': 'document.cleanup'},
    },
}

# 合并 Document 模块的定时任务配置
CELERY_BEAT_SCHEDULE.update(DOCUMENT_BEAT_SCHEDULE)

# 合并 RadioLicense 模块的定时任务配置
CELERY_BEAT_SCHEDULE.update(RADIO_LICENSE_BEAT_SCHEDULE)

CELERY_BEAT_SCHEDULE.update(CONTRACT_AGREEMENT_BEAT_SCHEDULE)

# 合并 Logs 模块的定时任务配置（审计日志归档清理）
CELERY_BEAT_SCHEDULE.update(LOGS_BEAT_SCHEDULE)

# 合并公告模块的定时任务配置（过期状态同步）
CELERY_BEAT_SCHEDULE.update(HOME_BEAT_SCHEDULE)

# 【新增】默认租户ID配置
DEFAULT_TENANT_ID = os.environ.get('DEFAULT_TENANT_ID', 'default')

# ==================== 回收站配置 ====================
# 【V3新增】回收站功能配置
RECYCLE_BIN_RETENTION_DAYS = 30     # 文件保留天数（默认30天）
RECYCLE_BIN_BATCH_LIMIT = 50        # 批量操作最大数量
RECYCLE_BIN_PAGE_SIZE = 20          # 默认分页大小
RECYCLE_BIN_CACHE_TTL = 60          # 列表缓存时间（秒）
RECYCLE_BIN_LARGE_FILE_THRESHOLD = 104857600  # 大文件阈值：100MB

# ==================== 文件预览配置 ====================
# 文本预览最大文件大小（默认2MB）
# Document transfer cleanup. Terminal transfer rows are retained briefly and
# removed by the scheduled cleanup task.
DOCUMENT_TRANSFER_RETENTION_DAYS = int(os.environ.get('DOCUMENT_TRANSFER_RETENTION_DAYS', '30'))
DOCUMENT_TRANSFER_CLEANUP_BATCH_SIZE = int(os.environ.get('DOCUMENT_TRANSFER_CLEANUP_BATCH_SIZE', '1000'))

TEXT_PREVIEW_MAX_SIZE = 2 * 1024 * 1024

# kkFileView 配置（Office文档在线预览）
# KKFILEVIEW_API_URL: kkFileView服务的访问地址（前端通过此地址访问kkFileView）
# KKFILEVIEW_SERVER_URL: kkFileView访问spug API的地址（kkFileView通过此地址下载文件）
# Docker部署示例：
#   KKFILEVIEW_API_URL = 'http://your-server:8012'
#   KKFILEVIEW_SERVER_URL = 'http://spug-api:80'  (Docker内部网络)
# 本地开发示例：
#   KKFILEVIEW_API_URL = 'http://127.0.0.1:8012'
#   KKFILEVIEW_SERVER_URL = 'http://127.0.0.1:80'
KKFILEVIEW_API_URL = os.environ.get('KKFILEVIEW_API_URL', '')
KKFILEVIEW_SERVER_URL = os.environ.get('KKFILEVIEW_SERVER_URL', '')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': False,
    },
]

TOKEN_TTL = 8 * 3600

TRANSFER_DIR = os.path.join(BASE_DIR, 'storage', 'transfer')

# Media files settings
# 生产环境默认 /data/spug/spug_api/media（Docker 容器内 BASE_DIR 即为 /data/spug/spug_api）
# 可通过环境变量 MEDIA_ROOT 覆盖
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))
MEDIA_URL = '/media/'

# Static files settings
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False

AUTHENTICATION_EXCLUDES = (
    '/account/login/',
    '/setting/basic/',
    re.compile('/apis/.*'),
    # 【H-4修复】仅排除公开探活端点，避免误伤需要登录的详细监控接口
    # 详细健康检查接口（DatabasePoolStatusView / DatabasePoolMetricsView）需要 @auth 认证
    re.compile('/document/health/$'),
    re.compile('/document/health/celery/$'),
    re.compile('/api/document/health/$'),
    re.compile('/api/document/health/celery/$'),
)

# IP绑定检查排除列表：这些端点仍需token认证，但跳过IP校验
# kkFileView从Docker内网发起文件下载请求，其IP与用户浏览器IP不同
# 使用 fnmatch 模式匹配（* 匹配任意字符包括 /）
IP_CHECK_EXCLUDES = (
    '/document/preview/*',
    '/api/document/preview/*',
    # 附件预览回调端点（kkFileView 通过此端点下载附件文件流）
    '*/attachments/*/preview-file/*',
)

SPUG_VERSION = 'v3.3.3'

# ==================== 日志配置 ====================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
            'maxBytes': 50 * 1024 * 1024,  # 50MB
            'backupCount': 10,
            'encoding': 'utf-8',
        },
        'document_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'document.log'),
            'formatter': 'verbose',
            'maxBytes': 50 * 1024 * 1024,  # 50MB
            'backupCount': 5,
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.document': {
            'handlers': ['console', 'file', 'document_file'],  # 【双写模式】同时写入 django.log 和 document.log
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# 确保日志目录存在
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# ==================== 告警配置 ====================
# 内网 SMTP 邮件告警（未配置 host 时跳过邮件，仅写 DB + 日志）
ALERT_SMTP = {
    'host': os.environ.get('SMTP_HOST', ''),
    'port': int(os.environ.get('SMTP_PORT', '25')),
    'username': os.environ.get('SMTP_USER', ''),
    'password': os.environ.get('SMTP_PASSWORD', ''),
    'from': os.environ.get('SMTP_FROM', 'spug-alert@internal'),
    'to': os.environ.get('SMTP_TO', '').split(',') if os.environ.get('SMTP_TO') else [],
}

# override default config
try:
    from spug.overrides import *
except ImportError:
    pass
