# Generated by Django 4.2.30 on 2026-07-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulation', '0004_alter_regulation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='regulation',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'retired'])), name='reg_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='regulation',
            constraint=models.CheckConstraint(check=models.Q(('effective_date__gte', models.F('publish_date')), ('effective_date__isnull', True), ('publish_date__isnull', True), _connector='OR'), name='reg_effective_after_publish'),
        ),
    ]
