# Generated by Django 4.2.30 on 2026-08-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulation', '0005_regulation_reg_status_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
