; ========================================
; Redis 缓存服务
; ========================================

[program:redis]
command = redis-server /etc/redis/redis.conf
autostart = true
autorestart = true
priority=15
