; ========================================
; Celery Worker: 合并任务队列 (document.merge)
; 职责: 文件分片合并任务
; ========================================

[program:spug-celery-merge]
command = celery -A spug worker -l info -Q document.merge -n merge-worker@%%h -c 2 --prefetch-multiplier=1 --max-tasks-per-child=200
directory = /data/spug/spug_api
autostart = true
autorestart = true
stdout_logfile = /data/spug/spug_api/logs/celery_merge.log
stderr_logfile = /data/spug/spug_api/logs/celery_merge_error.log
environment = DJANGO_SETTINGS_MODULE="spug.settings",PYTHONPATH="/data/spug/spug_api"
priority=36
