; ========================================
; Celery Worker: 默认队列 (celery) - 核心业务
; 职责: 其他所有异步任务（定时任务、消息通知等）
; ========================================

[program:spug-celery-default]
command = celery -A spug worker -l info -Q celery -n default-worker@%%h -c 2 --prefetch-multiplier=1 --max-tasks-per-child=1000
directory = /data/spug/spug_api
autostart = true
autorestart = true
stdout_logfile = /data/spug/spug_api/logs/celery_default.log
stderr_logfile = /data/spug/spug_api/logs/celery_default_error.log
environment = DJANGO_SETTINGS_MODULE="spug.settings",PYTHONPATH="/data/spug/spug_api"
priority=38
