# Generated by Django 2.2.28

from django.db import migrations, models
import libs.mixins
import libs.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('login', '登录'), ('logout', '登出'), ('export', '导出'), ('import', '导入'), ('approve', '审批'), ('other', '其他')], max_length=20)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=50, null=True)),
                ('target_name', models.CharField(max_length=255, null=True)),
                ('detail', models.TextField(null=True)),
                ('ip', models.CharField(max_length=50)),
                ('is_success', models.BooleanField(default=True)),
                ('tenant_id', models.CharField(default='default', max_length=50, null=True)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ('-id',),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
    ]
