# Generated by Django 4.2.30 on 2026-06-28 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_audit_tenant_ctime_id_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
