# Generated by Django 4.2.30 on 2026-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_alter_auditlog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='detail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
