# Generated by Codex on 2026-07-10

from django.db import migrations, models
import django.db.models.deletion
import libs
import libs.tenant_base_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_role_tenant_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('contract_name', models.CharField(help_text='合同名称', max_length=200)),
                ('contract_type', models.CharField(choices=[('device_purchase', '设备采购合同'), ('info_access', '信息引接合同'), ('service_guarantee', '服务保障协议')], help_text='类型', max_length=30)),
                ('valid_start_date', models.DateField(help_text='起始日期')),
                ('valid_end_date', models.DateField(help_text='截止日期')),
                ('has_fee', models.BooleanField(default=False, help_text='是否有费用')),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, help_text='费用金额', max_digits=12, null=True)),
                ('fee_currency', models.CharField(default='人民币', help_text='币种', max_length=10)),
                ('fee_detail', models.TextField(blank=True, default='', help_text='费用详细数据')),
                ('signing_party', models.CharField(help_text='签约方', max_length=500)),
                ('status', models.CharField(choices=[('active', '在用'), ('expired', '过期')], default='active', help_text='状态', max_length=20)),
                ('remark', models.TextField(blank=True, default='', help_text='备注')),
                ('last_remind_at', models.CharField(blank=True, help_text='最近提醒扫描时间', max_length=20, null=True)),
                ('created_at', models.CharField(default=libs.human_datetime, max_length=20)),
                ('updated_at', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'verbose_name': '合同协议',
                'verbose_name_plural': '合同协议',
                'db_table': 'tdyw_contract_agreement',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ContractAgreementReminderAck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('user_id', models.IntegerField(help_text='确认处理的用户ID')),
                ('user_name', models.CharField(default='', help_text='确认处理的用户名称', max_length=100)),
                ('ack_valid_end_date', models.DateField(help_text='确认时合同的截止日期')),
                ('created_at', models.CharField(default=libs.human_datetime, max_length=20)),
                ('agreement', models.ForeignKey(help_text='合同协议', on_delete=django.db.models.deletion.CASCADE, related_name='reminder_acks', to='contract_agreement.ContractAgreement')),
            ],
            options={
                'verbose_name': '合同协议提醒确认',
                'verbose_name_plural': '合同协议提醒确认',
                'db_table': 'tdyw_contract_agreement_reminder_ack',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='contractagreement',
            index=models.Index(fields=['tenant_id', '-created_at', '-id'], name='tdyw_contra_tenant_8811a0_idx'),
        ),
        migrations.AddIndex(
            model_name='contractagreement',
            index=models.Index(fields=['tenant_id', 'contract_type'], name='tdyw_contra_tenant_f8adba_idx'),
        ),
        migrations.AddIndex(
            model_name='contractagreement',
            index=models.Index(fields=['tenant_id', 'status'], name='tdyw_contra_tenant_1880dc_idx'),
        ),
        migrations.AddIndex(
            model_name='contractagreement',
            index=models.Index(fields=['tenant_id', 'valid_end_date'], name='tdyw_contra_tenant_f97a10_idx'),
        ),
        migrations.AddIndex(
            model_name='contractagreement',
            index=models.Index(fields=['tenant_id', 'has_fee'], name='tdyw_contra_tenant_a34e30_idx'),
        ),
        migrations.AddIndex(
            model_name='contractagreementreminderack',
            index=models.Index(fields=['tenant_id', 'user_id', 'agreement'], name='tdyw_cara_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractagreementreminderack',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'agreement_id', 'user_id', 'ack_valid_end_date'), name='uniq_contract_user_valid_end'),
        ),
    ]
