# Generated by Django 4.2.30 on 2026-07-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_agreement', '0003_alter_contractagreement_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractagreement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contractagreement',
            name='last_remind_at',
            field=models.DateTimeField(blank=True, help_text='最近提醒扫描时间', null=True),
        ),
        migrations.AlterField(
            model_name='contractagreement',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractagreementreminderack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
