# Generated by Django 4.2.30 on 2026-07-24 06:37

from django.db import migrations, models
from django.db.models import F, Q


def audit_contract_constraints(apps, schema_editor):
    Contract = apps.get_model('contract_agreement', 'ContractAgreement')
    records = Contract.objects.using(schema_editor.connection.alias)
    valid = records.filter(
        contract_type__in=['device_purchase', 'info_access', 'service_guarantee'],
        status__in=['normal', 'expiring', 'expired'],
        valid_end_date__gte=F('valid_start_date'),
    ).filter(Q(has_fee=False) | Q(fee_amount__isnull=False, fee_amount__gte=0))
    invalid = records.count() - valid.count()
    if invalid:
        raise RuntimeError(f'Contract integrity audit failed: invalid rows={invalid}')


class Migration(migrations.Migration):

    dependencies = [
        ('contract_agreement', '0004_alter_contractagreement_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(audit_contract_constraints, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contractagreement',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('expiring', '即将到期'), ('expired', '已过期')], default='normal', help_text='状态: normal/expiring/expired', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='contractagreement',
            constraint=models.CheckConstraint(check=models.Q(('contract_type__in', ['device_purchase', 'info_access', 'service_guarantee'])), name='contract_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='contractagreement',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['normal', 'expiring', 'expired'])), name='contract_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='contractagreement',
            constraint=models.CheckConstraint(check=models.Q(('valid_end_date__gte', models.F('valid_start_date'))), name='contract_date_order_valid'),
        ),
        migrations.AddConstraint(
            model_name='contractagreement',
            constraint=models.CheckConstraint(check=models.Q(('has_fee', False), models.Q(('fee_amount__gte', 0), ('fee_amount__isnull', False)), _connector='OR'), name='contract_fee_valid'),
        ),
    ]
