# Generated by Django 4.2.30 on 2026-09-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_agreement', '0006_contract_no_and_status_two_state'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contractagreement',
            name='contract_status_valid',
        ),
        migrations.AlterField(
            model_name='contractagreement',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('expiring', '即将到期'), ('expired', '已关闭')], default='normal', help_text='状态: normal/expiring/expired（expired 显示为已关闭）', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='contractagreement',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['normal', 'expiring', 'expired'])), name='contract_status_valid'),
        ),
    ]
