# Generated by Django 2.2.28 on 2026-05-29 22:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_add_tenant_id_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTransfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, default='', help_text='租户标识', max_length=50)),
                ('transfer_type', models.CharField(choices=[('UPLOAD', '上传'), ('DOWNLOAD', '下载')], db_index=True, max_length=20, verbose_name='传输类型')),
                ('status', models.CharField(choices=[('PENDING', '等待中'), ('UPLOADING', '上传中'), ('DOWNLOADING', '下载中'), ('PAUSED', '已暂停'), ('COMPLETED', '已完成'), ('FAILED', '失败'), ('CANCELED', '已取消')], db_index=True, default='PENDING', max_length=20, verbose_name='状态')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='文件大小(字节)')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件存储路径')),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='文件哈希(MD5)')),
                ('folder_id', models.IntegerField(blank=True, null=True, verbose_name='目标文件夹ID')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公共空间')),
                ('total_chunks', models.IntegerField(default=0, verbose_name='总分片数')),
                ('uploaded_chunks', models.IntegerField(default=0, verbose_name='已上传分片数')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('transferred_size', models.BigIntegerField(default=0, verbose_name='已传输大小(字节)')),
                ('speed', models.FloatField(default=0, verbose_name='传输速度(字节/秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, help_text='分片合并任务的Celery任务ID', max_length=100, null=True, verbose_name='Celery任务ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '文件传输记录',
                'verbose_name_plural': '文件传输记录',
                'db_table': 'tdyw_document_transfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFolderPublic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文件夹名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除（软删除）', verbose_name='删除标记')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User', verbose_name='创建人')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_folders_public', to='account.User', verbose_name='删除人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.DocumentFolderPublic', verbose_name='父文件夹')),
            ],
            options={
                'verbose_name': '文档文件夹(公共)',
                'verbose_name_plural': '文档文件夹(公共)',
                'db_table': 'tdyw_document_folder_public',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFolderPrivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文件夹名称')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除（软删除）', verbose_name='删除标记')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User', verbose_name='创建人')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_folders_private', to='account.User', verbose_name='删除人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.DocumentFolderPrivate', verbose_name='父文件夹')),
            ],
            options={
                'verbose_name': '文档文件夹(私有)',
                'verbose_name_plural': '文档文件夹(私有)',
                'db_table': 'tdyw_document_folder_private',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFilePublic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_name', models.CharField(blank=True, editable=False, help_text='物理文件名（存储用），生成后终身不可修改', max_length=100, null=True, verbose_name='物理文件名')),
                ('file_path', models.CharField(editable=False, help_text='完整存储路径，生成后不可修改', max_length=500, verbose_name='文件存储路径')),
                ('name', models.CharField(help_text='逻辑文件名（API交互用）', max_length=100, verbose_name='逻辑文件名')),
                ('display_name', models.CharField(help_text='显示名称（用户看到的文件名）', max_length=128, verbose_name='显示名称')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(max_length=100, verbose_name='文件类型')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除（软删除，默认查询已过滤）', verbose_name='删除标记')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('is_pending_clean', models.BooleanField(default=False, help_text='标记为待清理（物理文件删除失败时设置）', verbose_name='待清理标记')),
                ('clean_retry_count', models.IntegerField(default=0, help_text='清理重试次数', verbose_name='清理重试次数')),
                ('last_clean_attempt', models.DateTimeField(blank=True, help_text='上次清理尝试时间', null=True, verbose_name='上次清理尝试时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User', verbose_name='上传人')),
                ('folder', models.ForeignKey(blank=True, help_text='NULL表示文件在根目录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='document.DocumentFolderPublic', verbose_name='所属文件夹')),
            ],
            options={
                'verbose_name': '文档文件(公共)',
                'verbose_name_plural': '文档文件(公共)',
                'db_table': 'tdyw_document_file_public',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFilePrivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_name', models.CharField(blank=True, editable=False, help_text='物理文件名（存储用），生成后终身不可修改', max_length=100, null=True, verbose_name='物理文件名')),
                ('file_path', models.CharField(editable=False, help_text='完整存储路径，生成后不可修改', max_length=500, verbose_name='文件存储路径')),
                ('name', models.CharField(help_text='逻辑文件名（API交互用）', max_length=100, verbose_name='逻辑文件名')),
                ('display_name', models.CharField(help_text='显示名称（用户看到的文件名）', max_length=128, verbose_name='显示名称')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(max_length=100, verbose_name='文件类型')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除（软删除，默认查询已过滤）', verbose_name='删除标记')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('is_pending_clean', models.BooleanField(default=False, help_text='标记为待清理（物理文件删除失败时设置）', verbose_name='待清理标记')),
                ('clean_retry_count', models.IntegerField(default=0, help_text='清理重试次数', verbose_name='清理重试次数')),
                ('last_clean_attempt', models.DateTimeField(blank=True, help_text='上次清理尝试时间', null=True, verbose_name='上次清理尝试时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User', verbose_name='上传人')),
                ('folder', models.ForeignKey(blank=True, help_text='NULL表示文件在根目录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='document.DocumentFolderPrivate', verbose_name='所属文件夹')),
            ],
            options={
                'verbose_name': '文档文件(私有)',
                'verbose_name_plural': '文档文件(私有)',
                'db_table': 'tdyw_document_file_private',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documenttransfer',
            index=models.Index(fields=['tenant_id', 'user'], name='idx_transfer_tenant_user'),
        ),
        migrations.AddIndex(
            model_name='documenttransfer',
            index=models.Index(fields=['tenant_id', 'status'], name='idx_transfer_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='documenttransfer',
            index=models.Index(fields=['tenant_id', 'file_hash'], name='idx_transfer_tenant_hash'),
        ),
        migrations.AddIndex(
            model_name='documenttransfer',
            index=models.Index(fields=['user', 'status'], name='idx_transfer_user_status'),
        ),
        migrations.AddIndex(
            model_name='documenttransfer',
            index=models.Index(fields=['created_at'], name='idx_transfer_created'),
        ),
        migrations.AddConstraint(
            model_name='documentfolderpublic',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_folder_name_parent_public'),
        ),
        migrations.AddConstraint(
            model_name='documentfilepublic',
            constraint=models.UniqueConstraint(fields=('name', 'folder'), name='unique_file_name_folder_public'),
        ),
    ]
