# Generated by Django 2.2.28 on 2026-06-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfileprivate',
            name='thumbnail_path',
            field=models.CharField(blank=True, editable=False, help_text='缩略图存储路径', max_length=500, null=True, verbose_name='缩略图路径'),
        ),
        migrations.AddField(
            model_name='documentfilepublic',
            name='thumbnail_path',
            field=models.CharField(blank=True, editable=False, help_text='缩略图存储路径', max_length=500, null=True, verbose_name='缩略图路径'),
        ),
    ]
