# Generated by Django 2.2.28 on 2026-06-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_folder_unique_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfileprivate',
            options={'verbose_name': '文档文件(私有)', 'verbose_name_plural': '文档文件(私有)'},
        ),
        migrations.AlterModelOptions(
            name='documentfilepublic',
            options={'verbose_name': '文档文件(公共)', 'verbose_name_plural': '文档文件(公共)'},
        ),
        migrations.AlterModelOptions(
            name='documentfolderprivate',
            options={'verbose_name': '文档文件夹(私有)', 'verbose_name_plural': '文档文件夹(私有)'},
        ),
        migrations.AlterModelOptions(
            name='documentfolderpublic',
            options={'verbose_name': '文档文件夹(公共)', 'verbose_name_plural': '文档文件夹(公共)'},
        ),
        migrations.AlterModelOptions(
            name='documenttransfer',
            options={'verbose_name': '文件传输记录', 'verbose_name_plural': '文件传输记录'},
        ),
    ]
