# Generated by Django 4.2.30 on 2026-07-24 06:37

from django.db import migrations, models
from django.db.models import F, Q


def audit_document_transfer_constraints(apps, schema_editor):
    Transfer = apps.get_model('document', 'DocumentTransfer')
    records = Transfer.objects.using(schema_editor.connection.alias)
    valid = records.filter(
        Q(transfer_type__in=['UPLOAD', 'DOWNLOAD']) &
        Q(status__in=[
            'PENDING', 'UPLOADING', 'DOWNLOADING', 'PAUSED',
            'MERGING', 'COMPLETED', 'FAILED', 'CANCELED',
        ]) &
        Q(file_size__gte=0, total_chunks__gte=0, uploaded_chunks__gte=0) &
        Q(transferred_size__gte=0, speed__gte=0) &
        Q(progress__gte=0, progress__lte=100) &
        (Q(total_chunks=0) | Q(uploaded_chunks__lte=F('total_chunks')))
    )
    invalid = records.count() - valid.count()
    if invalid:
        raise RuntimeError(f'Document-transfer integrity audit failed: invalid rows={invalid}')


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_alter_documentfileprivate_id_and_more'),
    ]

    operations = [
        migrations.RunPython(audit_document_transfer_constraints, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='documenttransfer',
            constraint=models.CheckConstraint(check=models.Q(('transfer_type__in', ['UPLOAD', 'DOWNLOAD'])), name='doc_transfer_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='documenttransfer',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['PENDING', 'UPLOADING', 'DOWNLOADING', 'PAUSED', 'MERGING', 'COMPLETED', 'FAILED', 'CANCELED'])), name='doc_transfer_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='documenttransfer',
            constraint=models.CheckConstraint(check=models.Q(('file_size__gte', 0), ('total_chunks__gte', 0), ('uploaded_chunks__gte', 0), ('transferred_size__gte', 0), ('speed__gte', 0)), name='doc_transfer_counts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='documenttransfer',
            constraint=models.CheckConstraint(check=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='doc_transfer_progress_range'),
        ),
        migrations.AddConstraint(
            model_name='documenttransfer',
            constraint=models.CheckConstraint(check=models.Q(('total_chunks', 0), ('uploaded_chunks__lte', models.F('total_chunks')), _connector='OR'), name='doc_transfer_chunks_order'),
        ),
    ]
