# Generated by Django 4.2.30 on 2026-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_documenttransfer_doc_transfer_type_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttransfer',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='documenttransfer',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='文件哈希(MD5)'),
        ),
    ]
