# Generated by Django 4.2.30 on 2026-07-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_remove_null_from_string_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentfileprivate',
            constraint=models.UniqueConstraint(fields=('name', 'folder'), name='unique_file_name_folder_private'),
        ),
    ]
