# Generated by Django 4.2.30 on 2026-07-30 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0017_add_private_file_unique_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documenttransfer',
            name='doc_transfer_counts_nonnegative',
        ),
        migrations.RemoveIndex(
            model_name='documentfileprivate',
            name='doc_pri_file_list_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentfileprivate',
            name='doc_pri_file_diskusage_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentfilepublic',
            name='doc_pub_file_list_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentfolderprivate',
            name='doc_pri_folder_list_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentfolderpublic',
            name='doc_pub_folder_list_idx',
        ),
        migrations.RemoveField(
            model_name='documentfileprivate',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='documentfileprivate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='documentfilepublic',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='documentfilepublic',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='documentfolderprivate',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='documentfolderprivate',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='documentfolderprivate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='documentfolderpublic',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='documentfolderpublic',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='documentfolderpublic',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='documentfolderprivate',
            name='unique_key',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='唯一标识键（MD5哈希）', max_length=32, null=True, unique=True, verbose_name='唯一标识键'),
        ),
        migrations.AlterField(
            model_name='documentfolderpublic',
            name='unique_key',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='唯一标识键（MD5哈希）', max_length=32, null=True, unique=True, verbose_name='唯一标识键'),
        ),
        migrations.AlterField(
            model_name='documenttransfer',
            name='file_size',
            field=models.BigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='文件大小(字节)'),
        ),
        migrations.AddIndex(
            model_name='documentfileprivate',
            index=models.Index(fields=['folder_id', 'tenant_id', '-created_at', '-id'], name='doc_pri_file_list_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfileprivate',
            index=models.Index(fields=['tenant_id', 'file_size'], name='doc_pri_file_diskusage_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfilepublic',
            index=models.Index(fields=['folder_id', '-created_at', '-id'], name='doc_pub_file_list_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfolderprivate',
            index=models.Index(fields=['parent_id', 'tenant_id', '-created_at', '-id'], name='doc_pri_folder_list_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfolderpublic',
            index=models.Index(fields=['parent_id', '-created_at', '-id'], name='doc_pub_folder_list_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttransfer',
            constraint=models.CheckConstraint(check=models.Q(('file_size__gte', 1), ('total_chunks__gte', 0), ('uploaded_chunks__gte', 0), ('transferred_size__gte', 0), ('speed__gte', 0)), name='doc_transfer_counts_nonnegative'),
        ),
    ]
