# Generated by Django 4.2.30 on 2026-08-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_remove_soft_delete_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documenttransfer',
            name='doc_transfer_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='documenttransfer',
            name='doc_transfer_status_valid',
        ),
        migrations.AddField(
            model_name='documenttransfer',
            name='conflict_action',
            field=models.CharField(blank=True, default='', help_text='复制冲突处理：keep/replace/skip', max_length=10, verbose_name='冲突处理动作'),
        ),
        migrations.AddField(
            model_name='documenttransfer',
            name='source_file_id',
            field=models.BigIntegerField(blank=True, help_text='异步复制任务中源文件的数据库记录ID', null=True, verbose_name='源文件记录ID'),
        ),
        migrations.AddField(
            model_name='documenttransfer',
            name='source_file_path',
            field=models.CharField(blank=True, default='', help_text='异步复制任务中源文件的物理路径', max_length=500, verbose_name='源文件物理路径'),
        ),
        migrations.AlterField(
            model_name='documenttransfer',
            name='status',
            field=models.CharField(choices=[('PENDING', '等待中'), ('UPLOADING', '上传中'), ('DOWNLOADING', '下载中'), ('PAUSED', '已暂停'), ('MERGING', '合并中'), ('COPYING', '复制中'), ('COMPLETED', '已完成'), ('FAILED', '失败'), ('CANCELED', '已取消')], db_index=True, default='PENDING', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='documenttransfer',
            name='transfer_type',
            field=models.CharField(choices=[('UPLOAD', '上传'), ('DOWNLOAD', '下载'), ('COPY', '复制')], db_index=True, max_length=20, verbose_name='传输类型'),
        ),
        migrations.AddConstraint(
            model_name='documenttransfer',
            constraint=models.CheckConstraint(check=models.Q(('transfer_type__in', ['UPLOAD', 'DOWNLOAD', 'COPY'])), name='doc_transfer_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='documenttransfer',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['PENDING', 'UPLOADING', 'DOWNLOADING', 'PAUSED', 'MERGING', 'COPYING', 'COMPLETED', 'FAILED', 'CANCELED'])), name='doc_transfer_status_valid'),
        ),
    ]
