# Generated by Django 4.2.30 on 2026-08-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_add_copy_transfer_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfolderprivate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='documentfolderprivate',
            name='parent',
        ),
        migrations.DeleteModel(
            name='DocumentFilePrivate',
        ),
        migrations.DeleteModel(
            name='DocumentFolderPrivate',
        ),
    ]
