# Generated by Django 4.2.30 on 2026-08-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0020_remove_documentfolderprivate_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttransfer',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='是否公共空间'),
        ),
    ]
