# Generated by Django 4.2.30 on 2026-08-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0021_alter_documenttransfer_is_public'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentfilepublic',
            index=models.Index(fields=['folder_id', 'display_name', 'id'], name='doc_pub_file_name_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfolderpublic',
            index=models.Index(fields=['parent_id', 'name', 'id'], name='doc_pub_folder_name_idx'),
        ),
    ]
