# Generated by Django 4.2.30 on 2026-07-09 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_role_tenant_system'),
        ('document', '0009_document_system_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='规章名称')),
                ('rule_no', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='规章编号')),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='规章类别')),
                ('issuing_authority', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='发布单位')),
                ('applicable_scope', models.CharField(blank=True, default='', max_length=255, verbose_name='适用范围')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('effective_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='生效日期')),
                ('repeal_date', models.DateField(blank=True, null=True, verbose_name='废止日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('upcoming', '即将生效'), ('active', '现行'), ('retired', '已废止')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('version', models.CharField(blank=True, default='', max_length=50, verbose_name='版本')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_industry_rules', to='account.user', verbose_name='创建人')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_industry_rules', to='account.user', verbose_name='更新人')),
            ],
            options={
                'verbose_name': '行业规章',
                'verbose_name_plural': '行业规章',
                'db_table': 'tdyw_industry_rule',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndustryRuleAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关联时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_rule_attachments', to='account.user', verbose_name='关联人')),
                ('document_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_rule_attachments', to='document.documentfilepublic', verbose_name='关联文件')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='industry_rule.industryrule', verbose_name='所属规章')),
            ],
            options={
                'verbose_name': '行业规章附件',
                'verbose_name_plural': '行业规章附件',
                'db_table': 'tdyw_industry_rule_attachment',
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('rule', 'document_file')},
            },
        ),
    ]
