# Generated by Django 2.2.28 on 2026-05-29 22:17

from django.db import migrations, models
import django.db.models.deletion
import libs.mixins
import libs.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_add_tenant_id_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('system_name', models.CharField(max_length=100)),
                ('device_code', models.CharField(max_length=100)),
                ('fault_date', models.CharField(max_length=20)),
                ('handler', models.CharField(max_length=100)),
                ('recorder', models.CharField(max_length=100)),
                ('fault_level', models.CharField(max_length=50)),
                ('fault_phenomenon', models.TextField()),
                ('handling_process', models.TextField()),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(max_length=20, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'tdyw_fault_records',
                'ordering': ('-fault_date', '-id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='FaultPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('system_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('fault_date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('fault_sent_date', models.CharField(blank=True, max_length=20, null=True)),
                ('test_return_date', models.CharField(blank=True, max_length=20, null=True)),
                ('archive_date', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(max_length=20, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'tdyw_fault_parts',
                'ordering': ('-date', '-id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
    ]
