# Generated by Django 2.2.28 on 2026-06-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fault', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faultpart',
            options={'ordering': ('-date', '-id'), 'verbose_name': '故障件', 'verbose_name_plural': '故障件'},
        ),
        migrations.AlterModelOptions(
            name='faultrecord',
            options={'ordering': ('-fault_date', '-id'), 'verbose_name': '故障处置记录', 'verbose_name_plural': '故障处置记录'},
        ),
    ]
