# Generated by Django 4.2.30 on 2026-07-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault', '0004_alter_faultpart_archive_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='faultpart',
            index=models.Index(fields=['tenant_id', '-date', '-id'], name='fault_part_t_date_idx'),
        ),
        migrations.AddIndex(
            model_name='faultrecord',
            index=models.Index(fields=['tenant_id', '-fault_date', '-id'], name='fault_rec_t_date_idx'),
        ),
    ]
