# Generated by Django 4.2.30 on 2026-07-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault', '0005_faultpart_fault_part_t_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultpart',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultpart',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='faultrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultrecord',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
