CREATE TABLE IF NOT EXISTS exec_upgrade_records (
    id INT(11) NOT NULL AUTO_INCREMENT,
    upgrade_no VARCHAR(50) NOT NULL,
    system VARCHAR(100) NOT NULL,
    upgrade_type VARCHAR(50) NOT NULL,
    version VARCHAR(100) NOT NULL,
    plan_time VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT '待处理',
    result VARCHAR(20) NULL,
    owner VARCHAR(100) NOT NULL,
    actual_time VARCHAR(20) NULL,
    duration VARCHAR(50) NULL,
    checklist TEXT,
    dependencies TEXT,
    issues TEXT,
    lessons TEXT,
    created_at VARCHAR(20) NOT NULL,
    created_by_id INT(11) NOT NULL,
    updated_at VARCHAR(20) NULL,
    updated_by_id INT(11) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY upgrade_no (upgrade_no),
    KEY system (system),
    KEY status (status),
    KEY plan_time (plan_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
