# Generated by Django 2.2.28 on 2026-05-29 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSheetTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100, verbose_name='项目名称')),
                ('check_items', models.TextField(default='[]', verbose_name='检查项目列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '检查表模板',
                'verbose_name_plural': '检查表模板',
                'db_table': 'tdyw_checksheet_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckSheetDailySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='年份')),
                ('month', models.CharField(max_length=2, verbose_name='月份')),
                ('day', models.IntegerField(verbose_name='日期')),
                ('operator', models.CharField(blank=True, max_length=50, null=True, verbose_name='值班人员')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('rectification', models.TextField(blank=True, null=True, verbose_name='发现问题及整改情况')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '每日检查汇总',
                'verbose_name_plural': '每日检查汇总',
                'db_table': 'tdyw_checksheet_daily_summary',
                'unique_together': {('year', 'month', 'day')},
            },
        ),
        migrations.CreateModel(
            name='CheckSheetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='年份')),
                ('month', models.CharField(max_length=2, verbose_name='月份')),
                ('day', models.IntegerField(verbose_name='日期')),
                ('item_index', models.IntegerField(verbose_name='检查项索引')),
                ('status', models.CharField(choices=[('NORMAL', '正常'), ('ABNORMAL', '异常'), ('UNCHECKED', '未检查')], default='UNCHECKED', max_length=10, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('rectification', models.TextField(blank=True, null=True, verbose_name='发现问题及整改情况')),
                ('operator', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checksheet.CheckSheetTemplate', verbose_name='检查模板')),
            ],
            options={
                'verbose_name': '检查记录',
                'verbose_name_plural': '检查记录',
                'db_table': 'tdyw_checksheet_record',
                'ordering': ['year', 'month', 'day', 'item_index'],
                'unique_together': {('template', 'year', 'month', 'day', 'item_index')},
            },
        ),
    ]
