# Generated by Django 2.2.28 on 2026-06-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checksheettemplate',
            options={'ordering': ['created_at'], 'verbose_name': '检查表模板', 'verbose_name_plural': '检查表模板'},
        ),
        migrations.AlterField(
            model_name='checksheettemplate',
            name='project',
            field=models.CharField(max_length=100, unique=True, verbose_name='项目名称'),
        ),
    ]
