# Generated by Django 4.2.30 on 2026-07-24 06:37

from django.db import migrations, models
from django.db.models import Count, Q


VALID_MONTHS = [f'{month:02d}' for month in range(1, 13)]


def audit_checksheet_constraints(apps, schema_editor):
    database = schema_editor.connection.alias
    Submission = apps.get_model('checksheet', 'CheckSheetSubmission')
    Record = apps.get_model('checksheet', 'CheckSheetRecord')
    Summary = apps.get_model('checksheet', 'CheckSheetDailySummary')
    submissions = Submission.objects.using(database)
    records = Record.objects.using(database)
    summaries = Summary.objects.using(database)

    violations = {
        'duplicate submission periods': submissions.values(
            'tenant_id', 'project', 'year', 'month'
        ).annotate(row_count=Count('id')).filter(row_count__gt=1).count(),
        'invalid submission status': submissions.exclude(
            status__in=['draft', 'submitted', 'reviewed', 'closed', 'voided']
        ).count(),
        'invalid submission month': submissions.exclude(month__in=VALID_MONTHS).count(),
        'incomplete submit fields': submissions.filter(
            status__in=['submitted', 'reviewed', 'closed']
        ).filter(
            Q(submitted_by_id__isnull=True) | Q(submitted_at__isnull=True) |
            Q(submitted_by_name='') | Q(snapshot_hash='')
        ).count(),
        'incomplete review fields': submissions.filter(
            status__in=['reviewed', 'closed']
        ).filter(
            Q(reviewed_by_id__isnull=True) | Q(reviewed_at__isnull=True) |
            Q(reviewed_by_name='')
        ).count(),
        'incomplete void fields': submissions.filter(status='voided').filter(
            Q(voided_by_id__isnull=True) | Q(voided_at__isnull=True) |
            Q(voided_by_name='') | Q(void_reason='')
        ).count(),
        'invalid record values': records.filter(
            Q(month__in=VALID_MONTHS) & Q(day__gte=1, day__lte=31) &
            Q(item_index__gte=0) & Q(status__in=['NORMAL', 'ABNORMAL', 'UNCHECKED'])
        ).count() != records.count(),
        'invalid summary values': summaries.filter(
            Q(month__in=VALID_MONTHS) & Q(day__gte=1, day__lte=31)
        ).count() != summaries.count(),
    }
    failed = [f'{name}={count}' for name, count in violations.items() if count]
    if failed:
        raise RuntimeError('Checksheet integrity audit failed: ' + ', '.join(failed))


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0004_alter_checksheetdailysummary_id_and_more'),
    ]

    operations = [
        migrations.RunPython(audit_checksheet_constraints, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='checksheetdailysummary',
            constraint=models.CheckConstraint(check=models.Q(('month__in', ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12'])), name='cs_summary_month_valid'),
        ),
        migrations.AddConstraint(
            model_name='checksheetdailysummary',
            constraint=models.CheckConstraint(check=models.Q(('day__gte', 1), ('day__lte', 31)), name='cs_summary_day_valid'),
        ),
        migrations.AddConstraint(
            model_name='checksheetrecord',
            constraint=models.CheckConstraint(check=models.Q(('month__in', ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12'])), name='cs_record_month_valid'),
        ),
        migrations.AddConstraint(
            model_name='checksheetrecord',
            constraint=models.CheckConstraint(check=models.Q(('day__gte', 1), ('day__lte', 31)), name='cs_record_day_valid'),
        ),
        migrations.AddConstraint(
            model_name='checksheetrecord',
            constraint=models.CheckConstraint(check=models.Q(('item_index__gte', 0)), name='cs_record_item_index_valid'),
        ),
        migrations.AddConstraint(
            model_name='checksheetrecord',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['NORMAL', 'ABNORMAL', 'UNCHECKED'])), name='cs_record_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='checksheetsubmission',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'project', 'year', 'month'), name='uniq_cs_submission_period'),
        ),
        migrations.AddConstraint(
            model_name='checksheetsubmission',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'submitted', 'reviewed', 'closed', 'voided'])), name='cs_submission_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='checksheetsubmission',
            constraint=models.CheckConstraint(check=models.Q(('month__in', ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12'])), name='cs_submission_month_valid'),
        ),
        migrations.AddConstraint(
            model_name='checksheetsubmission',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'voided']), models.Q(('submitted_by_id__isnull', False), ('submitted_at__isnull', False), models.Q(('submitted_by_name', ''), _negated=True), models.Q(('snapshot_hash', ''), _negated=True)), _connector='OR'), name='cs_submission_submit_fields'),
        ),
        migrations.AddConstraint(
            model_name='checksheetsubmission',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status__in', ['reviewed', 'closed']), _negated=True), models.Q(('reviewed_by_id__isnull', False), ('reviewed_at__isnull', False), models.Q(('reviewed_by_name', ''), _negated=True)), _connector='OR'), name='cs_submission_review_fields'),
        ),
        migrations.AddConstraint(
            model_name='checksheetsubmission',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'voided'), _negated=True), models.Q(('voided_by_id__isnull', False), ('voided_at__isnull', False), models.Q(('voided_by_name', ''), _negated=True), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='cs_submission_void_fields'),
        ),
    ]
