# Generated by Django 2.2.28 on 2026-06-16 12:46

from django.db import migrations, models
import django.db.models.deletion
import libs.tenant_base_model
import libs.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_populate_tenants'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('station_name', models.CharField(help_text='台站名称', max_length=100)),
                ('purpose', models.CharField(default='', help_text='用途', max_length=500)),
                ('valid_from', models.DateField(help_text='起始日期')),
                ('valid_to', models.DateField(help_text='截止日期')),
                ('responsible_user_id', models.IntegerField(help_text='责任人ID', null=True)),
                ('responsible_user_name', models.CharField(default='', help_text='责任人姓名', max_length=100)),
                ('status', models.CharField(default='normal', help_text='状态: normal/expiring/expired', max_length=20)),
                ('last_remind_at', models.CharField(help_text='最近提醒时间', max_length=20, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除')),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(max_length=20, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'verbose_name': '无线电台执照',
                'verbose_name_plural': '无线电台执照',
                'db_table': 'tdyw_radio_license',
                'ordering': ('-created_at', '-id'),
            },
            bases=(models.Model, libs.tenant_base_model.TenantModelMixin),
        ),
        migrations.CreateModel(
            name='RadioLicenseFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('frequency_value', models.DecimalField(decimal_places=4, help_text='频率数值', max_digits=12)),
                ('frequency_unit', models.CharField(default='MHz', help_text='频率单位: MHz/kHz/GHz', max_length=20)),
                ('frequency_text', models.CharField(default='', help_text='原始显示文本', max_length=100)),
                ('remark', models.CharField(default='', help_text='备注', max_length=200)),
                ('sort_order', models.IntegerField(default=0, help_text='排序')),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('license', models.ForeignKey(help_text='执照', on_delete=django.db.models.deletion.CASCADE, related_name='frequencies', to='radio_license.RadioLicense')),
            ],
            options={
                'verbose_name': '执照频率明细',
                'verbose_name_plural': '执照频率明细',
                'db_table': 'tdyw_radio_license_frequency',
                'ordering': ('license', 'sort_order', 'id'),
            },
            bases=(models.Model, libs.tenant_base_model.TenantModelMixin),
        ),
        migrations.AddIndex(
            model_name='radiolicensefrequency',
            index=models.Index(fields=['tenant_id', 'license'], name='tdyw_radio__tenant__b1deda_idx'),
        ),
        migrations.AddIndex(
            model_name='radiolicense',
            index=models.Index(fields=['tenant_id', '-created_at', '-id'], name='tdyw_radio__tenant__f59744_idx'),
        ),
        migrations.AddIndex(
            model_name='radiolicense',
            index=models.Index(fields=['tenant_id', 'valid_to'], name='tdyw_radio__tenant__fe3ab2_idx'),
        ),
    ]
