# Generated by Django 2.2.28 on 2026-06-16 13:25

from django.db import migrations, models
import django.db.models.deletion
import libs.tenant_base_model
import libs.utils


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_populate_tenants'),
        ('radio_license', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioLicenseAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('attachment_type', models.CharField(choices=[('license', '执照'), ('permit', '许可证'), ('approval', '许可批复'), ('other', '其他')], default='other', help_text='附件类型', max_length=30)),
                ('file_name', models.CharField(help_text='原始文件名', max_length=255)),
                ('file_path', models.CharField(help_text='存储路径', max_length=500)),
                ('file_size', models.BigIntegerField(default=0, help_text='文件大小(字节)')),
                ('file_ext', models.CharField(default='', help_text='文件扩展名', max_length=20)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('license', models.ForeignKey(help_text='执照', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='radio_license.RadioLicense')),
                ('uploaded_by', models.ForeignKey(help_text='上传人', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'verbose_name': '执照附件',
                'verbose_name_plural': '执照附件',
                'db_table': 'tdyw_radio_license_attachment',
                'ordering': ('-created_at',),
            },
            bases=(models.Model, libs.tenant_base_model.TenantModelMixin),
        ),
        migrations.AddIndex(
            model_name='radiolicenseattachment',
            index=models.Index(fields=['tenant_id', 'license'], name='tdyw_radio__tenant__315929_idx'),
        ),
    ]
