# Generated by Django 2.2.28 on 2026-06-16 19:59

from django.db import migrations, models
import django.db.models.deletion
import libs.tenant_base_model
import libs.utils


class Migration(migrations.Migration):

    dependencies = [
        ('radio_license', '0002_add_attachment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioLicenseReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('remind_type', models.CharField(help_text='提醒类型: expiring_45/expiring_30/.../expired', max_length=30)),
                ('remind_date', models.DateField(help_text='提醒日期')),
                ('days_left', models.IntegerField(help_text='剩余天数')),
                ('title', models.CharField(help_text='标题', max_length=200)),
                ('content', models.TextField(default='', help_text='内容')),
                ('receiver_user_id', models.IntegerField(help_text='接收人ID')),
                ('receiver_user_name', models.CharField(default='', help_text='接收人姓名', max_length=100)),
                ('is_read', models.BooleanField(default=False, help_text='是否已读')),
                ('is_handled', models.BooleanField(default=False, help_text='是否已处理')),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('license', models.ForeignKey(help_text='执照', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='radio_license.RadioLicense')),
            ],
            options={
                'verbose_name': '执照提醒',
                'verbose_name_plural': '执照提醒',
                'db_table': 'tdyw_radio_license_reminder',
                'ordering': ('-created_at',),
            },
            bases=(models.Model, libs.tenant_base_model.TenantModelMixin),
        ),
        migrations.AddIndex(
            model_name='radiolicensereminder',
            index=models.Index(fields=['tenant_id', 'license'], name='tdyw_radio__tenant__735d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='radiolicensereminder',
            index=models.Index(fields=['tenant_id', 'receiver_user_id', 'is_read'], name='tdyw_radio__tenant__b5d714_idx'),
        ),
        migrations.AddIndex(
            model_name='radiolicensereminder',
            index=models.Index(fields=['tenant_id', 'license', 'remind_type', 'receiver_user_id'], name='tdyw_radio__tenant__bb5447_idx'),
        ),
    ]
