# Generated by Django 2.2.28 on 2026-06-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_license', '0005_add_reminder_ack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiolicensereminder',
            name='content',
            field=models.TextField(default='', help_text='内容（生成时快照，非实时）'),
        ),
        migrations.AlterField(
            model_name='radiolicensereminder',
            name='days_left',
            field=models.IntegerField(help_text='剩余天数（生成时快照，非实时）'),
        ),
        migrations.AlterField(
            model_name='radiolicensereminder',
            name='is_handled',
            field=models.BooleanField(default=False, help_text='是否已处理（历史字段，新逻辑用 LicenseReminderAck）'),
        ),
        migrations.AlterField(
            model_name='radiolicensereminder',
            name='remind_type',
            field=models.CharField(help_text='提醒类型: expiring_daily/expired（历史含 expiring_45/30/15/7/1）', max_length=30),
        ),
    ]
