# Generated by Django 4.2.30 on 2026-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_license', '0011_alter_licensereminderack_id_alter_radiolicense_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensereminderack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='radiolicense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='radiolicense',
            name='last_remind_at',
            field=models.DateTimeField(blank=True, help_text='最近提醒时间', null=True),
        ),
        migrations.AlterField(
            model_name='radiolicense',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radiolicensefrequency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='radiolicenseversion',
            name='changed_at',
            field=models.DateTimeField(blank=True, help_text='修改时间', null=True),
        ),
        migrations.AlterField(
            model_name='stationfrequencyapproval',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stationfrequencyapproval',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationfrequencyapprovalreminderack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
