# Generated by Django 4.2.30 on 2026-07-24 06:37

from django.db import migrations, models
from django.db.models import F


def audit_radio_license_constraints(apps, schema_editor):
    database = schema_editor.connection.alias
    License = apps.get_model('radio_license', 'RadioLicense')
    Frequency = apps.get_model('radio_license', 'RadioLicenseFrequency')
    Approval = apps.get_model('radio_license', 'StationFrequencyApproval')
    licenses = License.objects.using(database)
    frequencies = Frequency.objects.using(database)
    approvals = Approval.objects.using(database)
    valid_statuses = ['normal', 'expiring', 'expired']
    violations = {
        'invalid licenses': licenses.count() - licenses.filter(
            status__in=valid_statuses, valid_to__gte=F('valid_from')
        ).count(),
        'invalid frequencies': frequencies.count() - frequencies.filter(
            frequency_value__gt=0, sort_order__gte=0
        ).count(),
        'invalid approvals': approvals.count() - approvals.filter(
            status__in=valid_statuses, valid_to__gte=F('valid_from')
        ).count(),
    }
    failed = [f'{name}={count}' for name, count in violations.items() if count]
    if failed:
        raise RuntimeError('Radio-license integrity audit failed: ' + ', '.join(failed))


class Migration(migrations.Migration):

    dependencies = [
        ('radio_license', '0012_alter_licensereminderack_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(audit_radio_license_constraints, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='radiolicense',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('expiring', '即将到期'), ('expired', '已过期')], default='normal', help_text='状态: normal/expiring/expired', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='radiolicense',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['normal', 'expiring', 'expired'])), name='radio_license_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='radiolicense',
            constraint=models.CheckConstraint(check=models.Q(('valid_to__gte', models.F('valid_from'))), name='radio_license_date_order'),
        ),
        migrations.AddConstraint(
            model_name='radiolicensefrequency',
            constraint=models.CheckConstraint(check=models.Q(('frequency_value__gt', 0)), name='radio_frequency_positive'),
        ),
        migrations.AddConstraint(
            model_name='radiolicensefrequency',
            constraint=models.CheckConstraint(check=models.Q(('sort_order__gte', 0)), name='radio_frequency_sort_valid'),
        ),
        migrations.AddConstraint(
            model_name='stationfrequencyapproval',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['normal', 'expiring', 'expired'])), name='sfa_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='stationfrequencyapproval',
            constraint=models.CheckConstraint(check=models.Q(('valid_to__gte', models.F('valid_from'))), name='sfa_date_order_valid'),
        ),
    ]
