# Generated by Django 4.2.30 on 2026-07-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evidenceattachment',
            index=models.Index(fields=['tenant_id', 'module', 'object_type', 'object_id', 'is_deleted', 'uploaded_at', 'id'], name='ev_att_obj_del_time_idx'),
        ),
    ]
