# Generated by Django 4.2.30 on 2026-07-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_evidenceattachment_ev_att_obj_del_time_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evidenceevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
