# Generated by Django 4.2.30 on 2026-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_alter_evidenceattachment_id_alter_evidenceevent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceattachment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='删除时间', null=True),
        ),
        migrations.AlterField(
            model_name='evidenceattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='上传时间'),
        ),
        migrations.AlterField(
            model_name='evidenceevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='服务器时间'),
        ),
    ]
