# Generated by Django 4.2.30 on 2026-07-24 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0004_alter_evidenceattachment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='服务器时间'),
        ),
    ]
