# Generated by Django 4.2.30 on 2026-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0005_alter_evidenceevent_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceevent',
            name='actor_device',
            field=models.CharField(blank=True, default='', help_text='设备信息，可为空', max_length=255),
        ),
        migrations.AlterField(
            model_name='evidenceevent',
            name='after_snapshot',
            field=models.TextField(blank=True, default='', help_text='修改后快照 JSON，可为空'),
        ),
        migrations.AlterField(
            model_name='evidenceevent',
            name='attachment_hashes',
            field=models.TextField(blank=True, default='', help_text='附件哈希清单 JSON'),
        ),
        migrations.AlterField(
            model_name='evidenceevent',
            name='before_snapshot',
            field=models.TextField(blank=True, default='', help_text='修改前快照 JSON，可为空'),
        ),
        migrations.AlterField(
            model_name='evidenceevent',
            name='object_snapshot',
            field=models.TextField(blank=True, default='', help_text='业务对象快照 JSON'),
        ),
    ]
