# Generated by Django 4.2.30 on 2026-07-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0006_remove_null_from_string_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='evidenceevent',
            constraint=models.CheckConstraint(check=models.Q(('event_type__in', ['submit', 'approve', 'reject', 'close', 'correct', 'delete', 'export', 'void', 'other'])), name='ev_event_type_valid'),
        ),
    ]
