# Generated by Django 2.2.28 on 2026-05-29 22:17

from django.db import migrations, models
import django.db.models.deletion
import libs.mixins
import libs.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_add_tenant_id_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('serial_number', models.IntegerField(default=0)),
                ('frequency', models.CharField(max_length=100)),
                ('report_dept', models.CharField(max_length=100)),
                ('datetime', models.CharField(max_length=20)),
                ('coordinates', models.CharField(max_length=200)),
                ('interference_type', models.CharField(max_length=100)),
                ('phenomenon', models.TextField()),
                ('flight_number', models.CharField(blank=True, max_length=100, null=True)),
                ('aircraft_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_reported', models.CharField(default='否', max_length=10)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(max_length=20, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'tdyw_interferences',
                'ordering': ('serial_number', '-datetime', '-id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
    ]
