# Generated by Django 2.2.28 on 2026-06-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interference', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interference',
            options={'ordering': ('serial_number', '-datetime', '-id'), 'verbose_name': '干扰记录', 'verbose_name_plural': '干扰记录'},
        ),
    ]
