# Generated by Django 4.2.30 on 2026-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interference', '0004_alter_interference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interference',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='关闭时间', null=True),
        ),
        migrations.AlterField(
            model_name='interference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='interference',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interference',
            name='handled_at',
            field=models.DateTimeField(blank=True, help_text='处置时间', null=True),
        ),
        migrations.AlterField(
            model_name='interference',
            name='reported_at',
            field=models.DateTimeField(blank=True, help_text='上报时间', null=True),
        ),
        migrations.AlterField(
            model_name='interference',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='复核时间', null=True),
        ),
        migrations.AlterField(
            model_name='interference',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='提交时间', null=True),
        ),
        migrations.AlterField(
            model_name='interference',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interference',
            name='voided_at',
            field=models.DateTimeField(blank=True, help_text='作废时间', null=True),
        ),
    ]
