# Generated by Django 4.2.30 on 2026-07-24 06:37

from django.db import migrations, models
from django.db.models import Q


def audit_interference_constraints(apps, schema_editor):
    Interference = apps.get_model('interference', 'Interference')
    records = Interference.objects.using(schema_editor.connection.alias)
    valid_submit = Q(status__in=['draft', 'voided']) | (
        Q(submitted_by_id__isnull=False) & Q(submitted_at__isnull=False) &
        ~Q(submitted_by_name='') & ~Q(snapshot_hash='')
    )
    valid_review = ~Q(status__in=['reviewed', 'reported', 'handled', 'closed']) | (
        Q(reviewed_by_id__isnull=False) & Q(reviewed_at__isnull=False) & ~Q(reviewed_by_name='')
    )
    valid_report = ~Q(status__in=['reported', 'handled', 'closed']) | (
        Q(reported_by_id__isnull=False) & Q(reported_at__isnull=False) & ~Q(reported_by_name='')
    )
    valid_handle = ~Q(status__in=['handled', 'closed']) | (
        Q(handled_by_id__isnull=False) & Q(handled_at__isnull=False) & ~Q(handled_by_name='')
    )
    valid_close = ~Q(status='closed') | (
        Q(closed_by_id__isnull=False) & Q(closed_at__isnull=False) &
        ~Q(closed_by_name='') & Q(close_summary__isnull=False) & ~Q(close_summary='')
    )
    valid_void = ~Q(status='voided') | (
        Q(voided_by_id__isnull=False) & Q(voided_at__isnull=False) &
        ~Q(voided_by_name='') & ~Q(void_reason='')
    )
    valid = records.filter(
        Q(status__in=['draft', 'submitted', 'reviewed', 'reported', 'handled', 'closed', 'voided']) &
        valid_submit & valid_review & valid_report & valid_handle & valid_close & valid_void
    )
    invalid = records.count() - valid.count()
    if invalid:
        raise RuntimeError(f'Interference integrity audit failed: invalid rows={invalid}')


class Migration(migrations.Migration):

    dependencies = [
        ('interference', '0005_alter_interference_closed_at_and_more'),
    ]

    operations = [
        migrations.RunPython(audit_interference_constraints, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='interference',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'submitted', 'reviewed', 'reported', 'handled', 'closed', 'voided'])), name='interference_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='interference',
            constraint=models.CheckConstraint(check=models.Q(('status', 'draft'), ('status', 'voided'), models.Q(('submitted_by_id__isnull', False), ('submitted_at__isnull', False), models.Q(('submitted_by_name', ''), _negated=True), models.Q(('snapshot_hash', ''), _negated=True)), _connector='OR'), name='interference_submit_fields'),
        ),
        migrations.AddConstraint(
            model_name='interference',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status__in', ['reviewed', 'reported', 'handled', 'closed']), _negated=True), models.Q(('reviewed_by_id__isnull', False), ('reviewed_at__isnull', False), models.Q(('reviewed_by_name', ''), _negated=True)), _connector='OR'), name='interference_review_fields'),
        ),
        migrations.AddConstraint(
            model_name='interference',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status__in', ['reported', 'handled', 'closed']), _negated=True), models.Q(('reported_by_id__isnull', False), ('reported_at__isnull', False), models.Q(('reported_by_name', ''), _negated=True)), _connector='OR'), name='interference_report_fields'),
        ),
        migrations.AddConstraint(
            model_name='interference',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status__in', ['handled', 'closed']), _negated=True), models.Q(('handled_by_id__isnull', False), ('handled_at__isnull', False), models.Q(('handled_by_name', ''), _negated=True)), _connector='OR'), name='interference_handle_fields'),
        ),
        migrations.AddConstraint(
            model_name='interference',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'closed'), _negated=True), models.Q(('closed_by_id__isnull', False), ('closed_at__isnull', False), models.Q(('closed_by_name', ''), _negated=True), models.Q(('close_summary__isnull', True), _negated=True), models.Q(('close_summary', ''), _negated=True)), _connector='OR'), name='interference_close_fields'),
        ),
        migrations.AddConstraint(
            model_name='interference',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'voided'), _negated=True), models.Q(('voided_by_id__isnull', False), ('voided_at__isnull', False), models.Q(('voided_by_name', ''), _negated=True), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='interference_void_fields'),
        ),
    ]
