# Generated by Django 4.2.30 on 2026-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interference', '0006_interference_interference_status_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interference',
            name='aircraft_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='interference',
            name='close_summary',
            field=models.TextField(blank=True, default='', help_text='关闭总结'),
        ),
        migrations.AlterField(
            model_name='interference',
            name='flight_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='interference',
            name='review_comment',
            field=models.TextField(blank=True, default='', help_text='复核意见'),
        ),
    ]
