# Generated by Django 4.2.30 on 2026-07-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interference', '0007_remove_null_from_string_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='interference',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='删除时间', null=True),
        ),
        migrations.AddField(
            model_name='interference',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='软删除标识'),
        ),
    ]
