# Generated by Django 4.2.30 on 2026-08-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interference', '0008_interference_deleted_at_interference_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interference',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
