# Generated by Django 4.2.30 on 2026-08-30 21:28

from django.db import migrations, models
import django.db.models.deletion
import libs.tenant_base_model


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_tenant_is_active'),
        ('interference', '0009_alter_interference_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirInterferenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('datetime', models.DateTimeField(verbose_name='日期时间')),
                ('flight_number', models.CharField(blank=True, default='', max_length=100, verbose_name='航班号')),
                ('aircraft_type', models.CharField(blank=True, default='', max_length=100, verbose_name='机型')),
                ('phenomenon', models.TextField(verbose_name='现象')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标识')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='删除时间', null=True)),
                ('status', models.CharField(choices=[('draft', '已登记'), ('submitted', '已提交'), ('handled', '已处置'), ('closed', '已关闭')], default='draft', help_text='状态：draft 已登记 / submitted 已提交 / handled 已处置 / closed 已关闭', max_length=20)),
                ('route', models.CharField(blank=True, default='', max_length=200, verbose_name='航线')),
                ('runway', models.CharField(blank=True, default='', max_length=100, verbose_name='使用跑道')),
                ('approach_procedure', models.CharField(blank=True, default='', max_length=100, verbose_name='使用进近程序')),
                ('alert_form', models.CharField(blank=True, default='', max_length=100, verbose_name='告警形式')),
                ('alert_altitude', models.DecimalField(blank=True, decimal_places=2, help_text='原始录入数值，不换算；单位见 alert_altitude_unit', max_digits=8, null=True, verbose_name='告警高度')),
                ('alert_altitude_unit', models.CharField(choices=[('m', '米'), ('ft', '英尺')], default='m', max_length=10, verbose_name='告警高度单位')),
                ('alert_segment', models.CharField(blank=True, default='', max_length=200, verbose_name='告警航段')),
                ('duration', models.DecimalField(blank=True, decimal_places=2, help_text='原始录入数值，不换算；单位见 duration_unit', max_digits=10, null=True, verbose_name='持续时间')),
                ('duration_unit', models.CharField(choices=[('s', '秒'), ('min', '分钟'), ('h', '小时')], default='min', max_length=10, verbose_name='持续时间单位')),
                ('handling_method', models.TextField(blank=True, default='', help_text='首次登记可留空，处置（handled）前必填', verbose_name='处置方式')),
                ('cause_analysis', models.TextField(blank=True, default='', help_text='首次登记可留空，关闭（closed）前必填', verbose_name='原因分析')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.user')),
            ],
            options={
                'verbose_name': '空中干扰记录',
                'verbose_name_plural': '空中干扰记录',
                'db_table': 'tdyw_air_interference_records',
                'ordering': ('-datetime', '-id'),
            },
            bases=(models.Model, libs.tenant_base_model.TenantModelMixin),
        ),
        migrations.CreateModel(
            name='BridgeInterferenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('datetime', models.DateTimeField(verbose_name='日期时间')),
                ('flight_number', models.CharField(blank=True, default='', max_length=100, verbose_name='航班号')),
                ('aircraft_type', models.CharField(blank=True, default='', max_length=100, verbose_name='机型')),
                ('phenomenon', models.TextField(verbose_name='现象')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标识')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='删除时间', null=True)),
                ('status', models.CharField(choices=[('draft', '已登记'), ('submitted', '已提交'), ('closed', '已关闭')], default='draft', help_text='状态：draft 已登记 / submitted 已提交 / closed 已关闭', max_length=20)),
                ('aircraft_no', models.CharField(blank=True, default='', max_length=100, verbose_name='机号')),
                ('location', models.CharField(blank=True, default='', help_text='廊桥/航站楼等位置描述', max_length=200, verbose_name='位置')),
                ('stand_no', models.CharField(blank=True, default='', help_text='具体机位编号', max_length=100, verbose_name='机位')),
                ('frequency', models.CharField(blank=True, default='', max_length=100, verbose_name='频率')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.user')),
            ],
            options={
                'verbose_name': '廊桥航班无线电通信异常/干扰记录',
                'verbose_name_plural': '廊桥航班无线电通信异常/干扰记录',
                'db_table': 'tdyw_bridge_interference_records',
                'ordering': ('-datetime', '-id'),
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='bridge_status_idx'), models.Index(fields=['tenant_id', '-datetime', '-id'], name='bridge_time_idx')],
            },
            bases=(models.Model, libs.tenant_base_model.TenantModelMixin),
        ),
        migrations.AddConstraint(
            model_name='bridgeinterferencerecord',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'submitted', 'closed'])), name='bridge_interference_status_valid'),
        ),
        migrations.AddIndex(
            model_name='airinterferencerecord',
            index=models.Index(fields=['tenant_id', 'status'], name='air_status_idx'),
        ),
        migrations.AddIndex(
            model_name='airinterferencerecord',
            index=models.Index(fields=['tenant_id', '-datetime', '-id'], name='air_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='airinterferencerecord',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'submitted', 'handled', 'closed'])), name='air_interference_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='airinterferencerecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status__in', ['handled', 'closed']), _negated=True), models.Q(('handling_method', ''), _negated=True), _connector='OR'), name='air_interference_handle_fields'),
        ),
        migrations.AddConstraint(
            model_name='airinterferencerecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'closed'), _negated=True), models.Q(('cause_analysis', ''), _negated=True), _connector='OR'), name='air_interference_close_fields'),
        ),
        migrations.AddConstraint(
            model_name='airinterferencerecord',
            constraint=models.CheckConstraint(check=models.Q(('alert_altitude__isnull', True), models.Q(('alert_altitude_unit', ''), _negated=True), _connector='OR'), name='air_interference_altitude_unit'),
        ),
        migrations.AddConstraint(
            model_name='airinterferencerecord',
            constraint=models.CheckConstraint(check=models.Q(('alert_altitude__isnull', True), ('alert_altitude__gt', 0), _connector='OR'), name='air_interference_altitude_positive'),
        ),
        migrations.AddConstraint(
            model_name='airinterferencerecord',
            constraint=models.CheckConstraint(check=models.Q(('duration__isnull', True), models.Q(('duration_unit', ''), _negated=True), _connector='OR'), name='air_interference_duration_unit'),
        ),
        migrations.AddConstraint(
            model_name='airinterferencerecord',
            constraint=models.CheckConstraint(check=models.Q(('duration__isnull', True), ('duration__gt', 0), _connector='OR'), name='air_interference_duration_positive'),
        ),
    ]
