# Generated by Django 4.2.30 on 2026-08-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interference', '0010_airinterferencerecord_bridgeinterferencerecord_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='airinterferencerecord',
            name='air_interference_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='airinterferencerecord',
            name='air_interference_handle_fields',
        ),
        migrations.RemoveConstraint(
            model_name='airinterferencerecord',
            name='air_interference_close_fields',
        ),
        migrations.RemoveConstraint(
            model_name='bridgeinterferencerecord',
            name='bridge_interference_status_valid',
        ),
        migrations.RemoveIndex(
            model_name='airinterferencerecord',
            name='air_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='bridgeinterferencerecord',
            name='bridge_status_idx',
        ),
        migrations.RemoveField(
            model_name='airinterferencerecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bridgeinterferencerecord',
            name='status',
        ),
        migrations.AlterField(
            model_name='airinterferencerecord',
            name='cause_analysis',
            field=models.TextField(blank=True, default='', verbose_name='原因分析'),
        ),
        migrations.AlterField(
            model_name='airinterferencerecord',
            name='handling_method',
            field=models.TextField(blank=True, default='', verbose_name='处置方式'),
        ),
    ]
