# Generated by Django 4.2.30 on 2026-08-30 23:56
#
# 廊桥记录「位置」与「机位」合并为单字段 location（展示名：位置/机位）。
# 先把既有 stand_no 数据无损合并进 location，再移除 stand_no 列：
# - location 为空：直接取 stand_no；
# - 两者均有值：按展示约定以「位置/机位」格式拼接；
# - 回滚不拆分已合并文本（location 保留合并值），避免丢失信息。
from django.db import migrations, models


def merge_stand_no_into_location(apps, schema_editor):
    Bridge = apps.get_model('interference', 'BridgeInterferenceRecord')
    for row in Bridge.objects.all().iterator():
        location = (row.location or '').strip()
        stand_no = (row.stand_no or '').strip()
        if not stand_no:
            continue
        if not location:
            row.location = stand_no
        else:
            row.location = '%s/%s' % (location, stand_no)
        row.save(update_fields=['location'])


class Migration(migrations.Migration):

    dependencies = [
        ('interference', '0011_remove_airinterferencerecord_air_interference_status_valid_and_more'),
    ]

    operations = [
        migrations.RunPython(
            merge_stand_no_into_location,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='bridgeinterferencerecord',
            name='stand_no',
        ),
        migrations.AlterField(
            model_name='bridgeinterferencerecord',
            name='location',
            field=models.CharField(blank=True, default='', help_text='廊桥/航站楼位置或具体机位编号', max_length=200, verbose_name='位置/机位'),
        ),
    ]
