# Generated by Django 4.2.30 on 2026-08-31 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interference', '0012_remove_bridgeinterferencerecord_stand_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bridgeinterferencerecord',
            options={'ordering': ('-datetime', '-id'), 'verbose_name': '地面无线电通信异常/干扰记录', 'verbose_name_plural': '地面无线电通信异常/干扰记录'},
        ),
    ]
