# Generated by Django 4.2.30 on 2026-08-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interference', '0013_alter_bridgeinterferencerecord_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airinterferencerecord',
            name='alert_form',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='被扰频率'),
        ),
    ]
