# Generated by Django 4.2.30 on 2026-09-01 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interference', '0014_alter_airinterferencerecord_alert_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airinterferencerecord',
            name='approach_procedure',
        ),
        migrations.RemoveField(
            model_name='airinterferencerecord',
            name='runway',
        ),
    ]
