# Generated by Django 4.2.30 on 2026-09-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interference', '0015_remove_airinterferencerecord_approach_procedure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgeinterferencerecord',
            name='cause_analysis',
            field=models.TextField(blank=True, default='', verbose_name='原因分析'),
        ),
        migrations.AddField(
            model_name='bridgeinterferencerecord',
            name='handling_method',
            field=models.TextField(blank=True, default='', verbose_name='处置方式'),
        ),
    ]
