# Generated by Django 4.2.30 on 2026-07-30 14:09

from django.db import migrations, models
import django.db.models.deletion
import libs.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0013_alter_user_access_token_alter_role_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('level', models.CharField(choices=[('error', '严重'), ('warning', '警告'), ('info', '提示')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('active', '待处理'), ('resolved', '已处理')], db_index=True, default='active', max_length=10)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('alert_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.user')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ('-created_at', '-id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='AlertRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='alert.alert')),
            ],
            options={
                'db_table': 'alert_reads',
                'ordering': ('-read_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='alertread',
            constraint=models.UniqueConstraint(fields=('alert_id', 'user_id'), name='uniq_alert_read_user'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'created_at'], name='alert_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['level', 'status'], name='alert_level_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(check=models.Q(('level__in', ['error', 'warning', 'info'])), name='alert_level_valid'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'resolved'])), name='alert_status_valid'),
        ),
    ]
