# Copyright: (c) OpenSpug Organization. https://github.com/openspug/spug
# Copyright: (c) <spug.dev@gmail.com>
# Released under the AGPL-3.0 License.
"""
缩略图生成服务
使用 Pillow 生成图片缩略图

【2026-06-07 M2 修复】并发生成保护：
- 加 per-file 文件锁（fcntl）防止首次并发 4 worker 全打 Pillow
- fcntl 是 POSIX 锁（Django 部署在 Linux 上 OK）
- Windows 上用 msvcrt 替代
"""
import os
import logging
import time
import threading
from PIL import Image

logger = logging.getLogger(__name__)

# 缩略图配置
THUMBNAIL_SIZE = (200, 200)  # 最大尺寸，保持比例
THUMBNAIL_QUALITY = 85  # JPEG 质量
THUMBNAIL_FORMAT = 'JPEG'  # 输出格式

# 支持的图片格式
SUPPORTED_IMAGE_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.gif', '.bmp', '.webp'}

# 【M2 修复】锁获取/释放超时（秒）
THUMBNAIL_LOCK_TIMEOUT = 30
# 【M2 修复】轮询检查"其他进程是否已生成"的间隔（秒）
THUMBNAIL_POLL_INTERVAL = 0.2
# 【M2 修复】最大轮询次数（30 / 0.2 = 150 次 = 30 秒）
THUMBNAIL_POLL_MAX_TIMES = 150

# 【M2 修复】进程内锁字典（同一进程内多次调用复用锁）
_thumbnail_locks = {}
_thumbnail_locks_mutex = threading.Lock()


def _get_thumbnail_lock(lock_path):
    """
    【M2 修复】获取进程内的 thumbnail 锁对象（同一文件复用同一锁）

    锁按 lock_path 维度，避免不同缩略图互相阻塞
    """
    with _thumbnail_locks_mutex:
        if lock_path not in _thumbnail_locks:
            _thumbnail_locks[lock_path] = threading.Lock()
        return _thumbnail_locks[lock_path]


def _acquire_file_lock(lock_path, timeout=THUMBNAIL_LOCK_TIMEOUT):
    """
    【M2 修复】获取跨进程文件锁（POSIX fcntl）
    防止多 worker 进程同时生成同一缩略图

    Returns:
        file object if acquired, None if timeout
    """
    try:
        # POSIX 锁
        import fcntl
        lock_file = open(lock_path, 'w')
        fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX)
        return lock_file
    except ImportError:
        # Windows 没有 fcntl，用 msvcrt 替代
        try:
            import msvcrt
            lock_file = open(lock_path, 'w')
            # msvcrt 锁整个文件
            msvcrt.locking(lock_file.fileno(), msvcrt.LK_LOCK, 1)
            return lock_file
        except (ImportError, OSError):
            # 没有锁机制时直接返回 None（让 caller 走"无锁"路径）
            return None
    except (OSError, IOError) as e:
        logger.warning(f'[Thumbnail] 获取文件锁失败: {lock_path}, error={e}')
        return None


def _wait_for_thumbnail(thumbnail_path, max_wait=THUMBNAIL_LOCK_TIMEOUT):
    """
    【M2 修复】轮询等待"其他进程已生成缩略图"

    适用场景：另一个进程已获取锁并正在生成
    """
    poll_count = max_wait / THUMBNAIL_POLL_INTERVAL
    poll_count = min(poll_count, THUMBNAIL_POLL_MAX_TIMES)
    for _ in range(int(poll_count)):
        if os.path.exists(thumbnail_path):
            return True
        time.sleep(THUMBNAIL_POLL_INTERVAL)
    return False


class ThumbnailGenerator:
    """缩略图生成器"""

    @staticmethod
    def is_supported_image(file_path):
        """判断是否为支持的图片格式"""
        ext = os.path.splitext(file_path)[1].lower()
        return ext in SUPPORTED_IMAGE_EXTENSIONS

    @staticmethod
    def generate_thumbnail(file_path, thumbnail_dir, physical_name):
        """
        生成缩略图

        【2026-06-07 M2 修复】并发生成保护：
        1. 进程内锁：同进程多次调用复用锁
        2. 文件锁（fcntl/msvcrt）：跨进程互斥
        3. 轮询等待：拿到锁前先看缩略图是否已存在
        4. 双重检查：拿锁后再检查一次（防"等锁过程中别人已生成"）

        Args:
            file_path: 原始图片路径
            thumbnail_dir: 缩略图存储目录
            physical_name: 缩略图文件名（使用原文件的物理名）

        Returns:
            str: 缩略图路径，失败返回 None
        """
        try:
            # 检查是否支持
            if not ThumbnailGenerator.is_supported_image(file_path):
                logger.debug(f'[Thumbnail] Not a supported image: {file_path}')
                return None

            # 创建缩略图目录
            os.makedirs(thumbnail_dir, exist_ok=True)

            # 生成缩略图文件名：在物理名后加 _thumb
            name_without_ext, ext = os.path.splitext(physical_name)
            thumbnail_name = f"{name_without_ext}_thumb.jpg"
            thumbnail_path = os.path.join(thumbnail_dir, thumbnail_name)

            # 【M2 修复】第一道检查：未获取锁前先看是否已存在
            # 大多数请求会在这里直接返回（避免锁开销）
            if os.path.exists(thumbnail_path):
                logger.info(f'[Thumbnail] Thumbnail already exists: {thumbnail_path}')
                return thumbnail_path

            # 【M2 修复】第二道防护：进程内锁 + 文件锁
            lock_path = thumbnail_path + '.lock'
            in_process_lock = _get_thumbnail_lock(lock_path)

            with in_process_lock:
                # 进程内锁拿到后，再次检查（防同进程内并发）
                if os.path.exists(thumbnail_path):
                    logger.info(f'[Thumbnail] Thumbnail already exists (in-process check): {thumbnail_path}')
                    return thumbnail_path

                # 跨进程文件锁
                cross_proc_lock = _acquire_file_lock(lock_path)
                if cross_proc_lock is None:
                    # 拿不到文件锁时降级：轮询等待其他进程生成
                    if _wait_for_thumbnail(thumbnail_path):
                        logger.info(f'[Thumbnail] Thumbnail generated by other process: {thumbnail_path}')
                        return thumbnail_path
                    # 等待超时，继续生成（不阻塞业务）
                    logger.warning(f'[Thumbnail] Lock acquire timeout, generating without lock: {thumbnail_path}')

                try:
                    # 拿锁后再检查一次（防"等锁过程中其他进程已生成"）
                    if os.path.exists(thumbnail_path):
                        logger.info(f'[Thumbnail] Thumbnail already exists (post-lock check): {thumbnail_path}')
                        return thumbnail_path

                    # 打开并生成缩略图
                    with Image.open(file_path) as img:
                        # 转换为 RGB（JPEG 不支持 RGBA）
                        if img.mode in ('RGBA', 'P', 'LA'):
                            img = img.convert('RGB')

                        # 生成缩略图（保持比例）
                        img.thumbnail(THUMBNAIL_SIZE, Image.Resampling.LANCZOS)

                        # 保存缩略图
                        img.save(thumbnail_path, THUMBNAIL_FORMAT, quality=THUMBNAIL_QUALITY, optimize=True)

                    logger.info(f'[Thumbnail] Generated: {thumbnail_path}')
                    return thumbnail_path
                finally:
                    # 释放文件锁
                    if cross_proc_lock is not None:
                        try:
                            cross_proc_lock.close()
                        except Exception:
                            pass
                    # 清理 lock 文件（best-effort）
                    try:
                        if os.path.exists(lock_path):
                            os.remove(lock_path)
                    except OSError:
                        pass

        except Exception as e:
            logger.error(f'[Thumbnail] Failed to generate thumbnail for {file_path}: {e}')
            return None

    @staticmethod
    def delete_thumbnail(thumbnail_path):
        """删除缩略图"""
        try:
            if thumbnail_path and os.path.exists(thumbnail_path):
                os.remove(thumbnail_path)
                logger.info(f'[Thumbnail] Deleted: {thumbnail_path}')
                return True
        except Exception as e:
            logger.error(f'[Thumbnail] Failed to delete thumbnail {thumbnail_path}: {e}')
        return False


def get_thumbnail_dir(file_path):
    """
    获取缩略图存储目录
    缩略图存储在原图的同一目录的 thumbnails 子目录下

    Args:
        file_path: 原始文件路径

    Returns:
        str: 缩略图目录路径
    """
    return os.path.join(os.path.dirname(file_path), 'thumbnails')


def generate_thumbnail_for_file(file_path, physical_name):
    """
    为文件生成缩略图的便捷函数

    Args:
        file_path: 原始文件路径
        physical_name: 文件物理名

    Returns:
        str: 缩略图路径，失败返回 None
    """
    thumbnail_dir = get_thumbnail_dir(file_path)
    return ThumbnailGenerator.generate_thumbnail(file_path, thumbnail_dir, physical_name)