# Generated by Django 4.2.30 on 2026-07-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_alter_setting_id_alter_usersetting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='desc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
