# Generated by Django 4.2.30 on 2026-08-30 02:33

from django.db import migrations, models
import django.db.models.deletion
import libs.tenant_base_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoopTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('title', models.CharField(help_text='任务标题', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='任务说明与要求')),
                ('deadline', models.DateTimeField(help_text='交付截止时间')),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('completed', '已完成'), ('voided', '已作废')], default='in_progress', help_text='任务状态', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, help_text='完成时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('created_by_id', models.IntegerField(blank=True, help_text='创建人ID', null=True)),
                ('created_by_name', models.CharField(default='', help_text='创建人姓名快照', max_length=100)),
                ('updated_at', models.DateTimeField(blank=True, help_text='更新时间', null=True)),
                ('updated_by_id', models.IntegerField(blank=True, help_text='更新人ID', null=True)),
                ('updated_by_name', models.CharField(default='', help_text='更新人姓名快照', max_length=100)),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标识')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='删除时间', null=True)),
                ('deleted_by_id', models.IntegerField(blank=True, help_text='删除人ID', null=True)),
                ('deleted_by_name', models.CharField(default='', help_text='删除人姓名快照', max_length=100)),
            ],
            options={
                'verbose_name': '协作任务',
                'verbose_name_plural': '协作任务',
                'db_table': 'tdyw_coop_tasks',
                'ordering': ('-id',),
            },
            bases=(models.Model, libs.tenant_base_model.TenantModelMixin),
        ),
        migrations.CreateModel(
            name='CoopTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('target_tenant_id', models.CharField(help_text='交付科室ID', max_length=50)),
                ('target_tenant_name', models.CharField(default='', help_text='交付科室名称快照', max_length=100)),
                ('contact_user_id', models.IntegerField(blank=True, help_text='科室经办人账号ID（展示用）', null=True)),
                ('contact_user_name', models.CharField(default='', help_text='科室经办人姓名快照（展示用，上传仍使用科室账号）', max_length=100)),
                ('urge_count', models.IntegerField(default=0, help_text='催办次数')),
                ('last_urged_at', models.DateTimeField(blank=True, help_text='最近催办时间', null=True)),
                ('urge_read_at', models.DateTimeField(blank=True, help_text='交付方最近查看时间（用于催办未读标记）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('task', models.ForeignKey(help_text='所属任务', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='coop_task.cooptask')),
            ],
            options={
                'verbose_name': '协作任务分派',
                'verbose_name_plural': '协作任务分派',
                'db_table': 'tdyw_coop_task_assignments',
                'ordering': ('id',),
            },
            bases=(models.Model, libs.tenant_base_model.TenantModelMixin),
        ),
        migrations.CreateModel(
            name='CoopTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('name', models.CharField(help_text='材料名称', max_length=200)),
                ('remark', models.CharField(blank=True, default='', help_text='材料要求说明', max_length=500)),
                ('sort_order', models.IntegerField(default=0, help_text='排序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('task', models.ForeignKey(help_text='所属任务', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coop_task.cooptask')),
            ],
            options={
                'verbose_name': '协作任务材料',
                'verbose_name_plural': '协作任务材料',
                'db_table': 'tdyw_coop_task_items',
                'ordering': ('sort_order', 'id'),
            },
            bases=(models.Model, libs.tenant_base_model.TenantModelMixin),
        ),
        migrations.CreateModel(
            name='CoopTaskDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('status', models.CharField(choices=[('pending', '待交付'), ('submitted', '待验收'), ('accepted', '已验收'), ('rejected', '已退回')], default='pending', help_text='交付状态', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='最近提交时间', null=True)),
                ('submitter_id', models.IntegerField(blank=True, help_text='提交人账号ID', null=True)),
                ('submitter_name', models.CharField(default='', help_text='提交人姓名快照', max_length=100)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='验收时间', null=True)),
                ('accepted_by_id', models.IntegerField(blank=True, help_text='验收人账号ID', null=True)),
                ('accepted_by_name', models.CharField(default='', help_text='验收人姓名快照', max_length=100)),
                ('reject_reason', models.CharField(blank=True, default='', help_text='退回原因', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('assignment', models.ForeignKey(help_text='所属分派', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='coop_task.cooptaskassignment')),
                ('item', models.ForeignKey(help_text='对应材料', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='coop_task.cooptaskitem')),
            ],
            options={
                'verbose_name': '协作任务交付明细',
                'verbose_name_plural': '协作任务交付明细',
                'db_table': 'tdyw_coop_task_deliveries',
                'ordering': ('id',),
            },
            bases=(models.Model, libs.tenant_base_model.TenantModelMixin),
        ),
        migrations.AddIndex(
            model_name='cooptask',
            index=models.Index(fields=['tenant_id', 'is_deleted', 'status'], name='coop_task_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='cooptask',
            index=models.Index(fields=['status', 'deadline'], name='coop_task_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='cooptask',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['in_progress', 'completed', 'voided'])), name='coop_task_status_valid'),
        ),
        migrations.AddIndex(
            model_name='cooptaskitem',
            index=models.Index(fields=['task_id', 'sort_order', 'id'], name='coop_item_task_idx'),
        ),
        migrations.AddIndex(
            model_name='cooptaskdelivery',
            index=models.Index(fields=['assignment_id', 'status'], name='coop_dlvy_assign_idx'),
        ),
        migrations.AddIndex(
            model_name='cooptaskdelivery',
            index=models.Index(fields=['status'], name='coop_dlvy_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='cooptaskdelivery',
            constraint=models.UniqueConstraint(fields=('assignment', 'item'), name='uniq_coop_delivery_assignment_item'),
        ),
        migrations.AddConstraint(
            model_name='cooptaskdelivery',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'submitted', 'accepted', 'rejected'])), name='coop_delivery_status_valid'),
        ),
        migrations.AddIndex(
            model_name='cooptaskassignment',
            index=models.Index(fields=['target_tenant_id'], name='coop_assign_target_idx'),
        ),
        migrations.AddIndex(
            model_name='cooptaskassignment',
            index=models.Index(fields=['task_id', 'target_tenant_id'], name='coop_assign_task_idx'),
        ),
        migrations.AddConstraint(
            model_name='cooptaskassignment',
            constraint=models.UniqueConstraint(fields=('task', 'target_tenant_id'), name='uniq_coop_assignment_task_tenant'),
        ),
    ]
