# Generated by Django 4.2.30 on 2026-08-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooptaskassignment',
            name='contact_user_id',
            field=models.IntegerField(blank=True, help_text='交付科室账号ID（按账号分发的任务记录选定账号，旧数据为空）', null=True),
        ),
        migrations.AlterField(
            model_name='cooptaskassignment',
            name='contact_user_name',
            field=models.CharField(default='', help_text='交付科室账号人名快照（旧数据可能记录经办人备注）', max_length=100),
        ),
    ]
