# Generated by Django 2.2.28 on 2026-05-30 11:40

from django.db import migrations, models
import django.db.models.deletion
import libs.mixins
import libs.utils


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_add_tenant_id_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.CharField(help_text='租户标识', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='租户名称', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='租户描述')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'verbose_name': '租户',
                'verbose_name_plural': '租户',
                'db_table': 'tenants',
                'ordering': ('id',),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
    ]
