# Generated by Django 2.2.28 on 2026-05-30 11:40

from django.db import migrations


def populate_tenants(apps, schema_editor):
    """从现有 User.tenant_id 中提取所有租户ID并创建 Tenant 记录"""
    User = apps.get_model('account', 'User')
    Tenant = apps.get_model('account', 'Tenant')

    # 提取所有已存在的租户ID
    existing_tenant_ids = set(
        User.objects.exclude(tenant_id='')
        .exclude(tenant_id__isnull=True)
        .values_list('tenant_id', flat=True)
        .distinct()
    )

    tenants_to_create = []
    for tid in existing_tenant_ids:
        tenant = Tenant(
            id=tid,
            name=tid,  # 暂时以ID作为名称
            description='自动创建',
            is_active=True,
        )
        tenants_to_create.append(tenant)

    if tenants_to_create:
        Tenant.objects.bulk_create(tenants_to_create, ignore_conflicts=True)


def reverse_populate(apps, schema_editor):
    """反向迁移：删除所有自动创建的 Tenant 记录"""
    Tenant = apps.get_model('account', 'Tenant')
    Tenant.objects.filter(description='自动创建').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_tenant_model'),
    ]

    operations = [
        migrations.RunPython(populate_tenants, reverse_populate),
    ]
