# Generated by Django 4.2.30 on 2026-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_active_username_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='agent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='deploy_perms',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='role',
            name='desc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='group_perms',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='role',
            name='page_perms',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='role',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='wx_token',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
