# Generated by Django 4.2.30 on 2026-07-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_fix_user_created_by_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('tenant_id', 'name')},
        ),
    ]
