# Generated by Django 4.2.30 on 2026-07-29 19:22

import uuid

from django.db import migrations, models


def fill_empty_access_tokens(apps, schema_editor):
    """给空 access_token 的用户生成唯一 UUID，防止加唯一约束时冲突"""
    User = apps.get_model('account', 'User')
    for user in User.objects.filter(access_token=''):
        user.access_token = uuid.uuid4().hex
        user.save(update_fields=['access_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_fix_user_created_by_null'),
    ]

    operations = [
        migrations.RunPython(
            fill_empty_access_tokens,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('tenant_id', 'name')},
        ),
    ]
