CREATE TABLE IF NOT EXISTS exec_schedule_swap (
    id INT(11) NOT NULL AUTO_INCREMENT,
    from_staff_id INT(11) NOT NULL,
    from_staff_name VARCHAR(100) NOT NULL,
    to_staff_id INT(11) NOT NULL,
    to_staff_name VARCHAR(100) NOT NULL,
    schedule_date VARCHAR(20) NOT NULL,
    from_shift_id INT(11) NOT NULL,
    from_shift_name VARCHAR(100) NOT NULL,
    to_shift_id INT(11) NOT NULL,
    to_shift_name VARCHAR(100) NOT NULL,
    reason TEXT DEFAULT NULL,
    status VARCHAR(20) DEFAULT 'pending',
    approved_by_id INT(11) DEFAULT NULL,
    approved_by_name VARCHAR(100) DEFAULT NULL,
    approved_at VARCHAR(20) DEFAULT NULL,
    remarks TEXT DEFAULT NULL,
    created_at VARCHAR(20) NOT NULL,
    created_by_id INT(11) NOT NULL,
    updated_at VARCHAR(20) NULL,
    updated_by_id INT(11) NULL,
    PRIMARY KEY (id),
    KEY schedule_date (schedule_date),
    KEY status (status),
    KEY from_staff_id (from_staff_id),
    KEY to_staff_id (to_staff_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS exec_schedule_substitute (
    id INT(11) NOT NULL AUTO_INCREMENT,
    original_staff_id INT(11) NOT NULL,
    original_staff_name VARCHAR(100) NOT NULL,
    substitute_staff_id INT(11) NOT NULL,
    substitute_staff_name VARCHAR(100) NOT NULL,
    schedule_date VARCHAR(20) NOT NULL,
    shift_id INT(11) NOT NULL,
    shift_name VARCHAR(100) NOT NULL,
    reason TEXT DEFAULT NULL,
    status VARCHAR(20) DEFAULT 'pending',
    approved_by_id INT(11) DEFAULT NULL,
    approved_by_name VARCHAR(100) DEFAULT NULL,
    approved_at VARCHAR(20) DEFAULT NULL,
    remarks TEXT DEFAULT NULL,
    created_at VARCHAR(20) NOT NULL,
    created_by_id INT(11) NOT NULL,
    updated_at VARCHAR(20) NULL,
    updated_by_id INT(11) NULL,
    PRIMARY KEY (id),
    KEY schedule_date (schedule_date),
    KEY status (status),
    KEY original_staff_id (original_staff_id),
    KEY substitute_staff_id (substitute_staff_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
