# Generated by Django 2.2.28 on 2026-05-29 22:59

from django.db import migrations, models
import django.db.models.deletion
import libs.mixins
import libs.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_add_tenant_id_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunLogUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('runlog_id', models.IntegerField(help_text='关联事件ID')),
                ('event_title', models.CharField(help_text='事件标题（冗余）', max_length=200)),
                ('update_date', models.CharField(help_text='动态日期（精确到日）', max_length=20)),
                ('sequence', models.IntegerField(default=0, help_text='同一天内的序号')),
                ('recorder', models.CharField(help_text='记录人', max_length=100)),
                ('detail_content', models.TextField(help_text='详细记录')),
                ('attachments', models.TextField(blank=True, help_text='附件JSON，存储图片路径列表', null=True)),
                ('editable_until', models.CharField(help_text='可修改截止时间（创建后24小时内）', max_length=20)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'tdyw_run_log_updates',
                'ordering': ('update_date', 'sequence', 'id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('event_title', models.CharField(help_text='事件标题', max_length=200)),
                ('event_type', models.CharField(help_text='事件类型：运行异常/设备故障/安全事件/其他', max_length=50)),
                ('system_name', models.CharField(help_text='关联系统名称', max_length=100)),
                ('severity', models.CharField(default='P2', help_text='事件级别：P0紧急/P1重要/P2一般', max_length=10)),
                ('status', models.CharField(default='in_progress', help_text='事件状态：in_progress处理中/resolved已解决', max_length=20)),
                ('responsible_user_id', models.IntegerField(blank=True, null=True)),
                ('responsible_user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution', models.TextField(blank=True, help_text='处理措施总结（事件解决后的最终方案总结，与动态记录不同，此处填写结案报告）', null=True)),
                ('verifier_id', models.IntegerField(blank=True, null=True)),
                ('verifier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_at', models.CharField(blank=True, max_length=20, null=True)),
                ('closed_at', models.CharField(blank=True, max_length=20, null=True)),
                ('update_count', models.IntegerField(default=0, help_text='动态数量')),
                ('first_update_date', models.CharField(blank=True, help_text='首次动态日期', max_length=20, null=True)),
                ('last_update_date', models.CharField(blank=True, help_text='最后动态日期', max_length=20, null=True)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(max_length=20, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'tdyw_run_logs',
                'ordering': ('-created_at', '-id'),
                'managed': True,
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.AddIndex(
            model_name='runlogupdate',
            index=models.Index(fields=['runlog_id'], name='tdyw_run_lo_runlog__f96268_idx'),
        ),
        migrations.AddIndex(
            model_name='runlogupdate',
            index=models.Index(fields=['tenant_id', 'runlog_id'], name='tdyw_run_lo_tenant__ef3bce_idx'),
        ),
        migrations.AddIndex(
            model_name='runlogupdate',
            index=models.Index(fields=['update_date'], name='tdyw_run_lo_update__bbd520_idx'),
        ),
        migrations.AddIndex(
            model_name='runlog',
            index=models.Index(fields=['tenant_id', 'status'], name='tdyw_run_lo_tenant__8c613c_idx'),
        ),
        migrations.AddIndex(
            model_name='runlog',
            index=models.Index(fields=['tenant_id', 'severity'], name='tdyw_run_lo_tenant__c21b90_idx'),
        ),
    ]
