# Generated by Django 2.2.28 on 2026-06-04 11:40

from django.db import migrations, models
import django.db.models.deletion
import libs.utils


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('name', models.CharField(help_text='类型名称', max_length=50, unique=True)),
                ('color', models.CharField(default='#1890ff', help_text='前端显示颜色', max_length=20)),
                ('sort_order', models.IntegerField(default=0, help_text='排序顺序，数字越小越靠前')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'verbose_name': '事件类型配置',
                'verbose_name_plural': '事件类型配置',
                'db_table': 'tdyw_run_log_event_types',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='eventtypeconfig',
            index=models.Index(fields=['tenant_id', 'is_active'], name='tdyw_run_e_tenant_idx'),
        ),
    ]
