# Generated by Django 2.2.28 on 2026-06-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0003_add_event_type_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runlog',
            options={'managed': True, 'ordering': ('-created_at', '-id'), 'verbose_name': '运行日志', 'verbose_name_plural': '运行日志'},
        ),
        migrations.AlterModelOptions(
            name='runlogupdate',
            options={'ordering': ('update_date', 'sequence', 'id'), 'verbose_name': '运行日志动态', 'verbose_name_plural': '运行日志动态'},
        ),
        migrations.RemoveIndex(
            model_name='eventtypeconfig',
            name='tdyw_run_e_tenant_idx',
        ),
        migrations.RemoveField(
            model_name='eventtypeconfig',
            name='tenant_id',
        ),
        migrations.AddIndex(
            model_name='eventtypeconfig',
            index=models.Index(fields=['is_active'], name='tdyw_run_lo_is_acti_02d1c0_idx'),
        ),
    ]
