# Generated by Django 2.2.28 on 2026-06-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0004_remove_event_type_tenant_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtypeconfig',
            options={'ordering': ('id',), 'verbose_name': '事件类型配置', 'verbose_name_plural': '事件类型配置'},
        ),
        migrations.RemoveField(
            model_name='eventtypeconfig',
            name='color',
        ),
        migrations.RemoveField(
            model_name='eventtypeconfig',
            name='sort_order',
        ),
    ]
