# Generated by Django 2.2.28 on 2026-06-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0005_auto_20260604_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='runlogupdate',
            name='duty_person',
            field=models.CharField(blank=True, help_text='值班人', max_length=128, null=True),
        ),
    ]
