# Generated by Django 4.2.30 on 2026-06-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0007_evidence_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runlog',
            name='status',
            field=models.CharField(default='in_progress', help_text='事件状态：in_progress处理中/resolved已解决/verified已验证/closed已归档/voided已作废', max_length=20),
        ),
    ]
