# Generated by Django 4.2.30 on 2026-06-28 20:44

from django.db import migrations, models
import django.utils.timezone


def clean_empty_time_strings(apps, schema_editor):
    """把时间字段中的空字符串 '' 清洗为 NULL。

    背景：varchar(20) 阶段部分可空时间字段被写入了空字符串 ''，
    直接 ALTER 到 DATETIME/DATE 会失败或产生 '0000-00-00' 垃圾值。
    本函数在改字段类型前把空串统一转为 NULL，保证 ALTER 安全。
    """
    RunLog = apps.get_model('runlog', 'RunLog')
    # verified_at / closed_at 历史数据中存在空字符串
    RunLog.objects.filter(verified_at='').update(verified_at=None)
    RunLog.objects.filter(closed_at='').update(closed_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0008_alter_runlog_status'),
    ]

    operations = [
        # 第一步：清洗空字符串为 NULL，确保后续 AlterField 安全
        migrations.RunPython(clean_empty_time_strings,
                             migrations.RunPython.noop),
        # 第二步：改字段类型
        migrations.AlterField(
            model_name='eventtypeconfig',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='first_update_date',
            field=models.DateField(blank=True, help_text='首次动态日期', null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='last_update_date',
            field=models.DateField(blank=True, help_text='最后动态日期', null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runlogupdate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='runlogupdate',
            name='editable_until',
            field=models.DateTimeField(help_text='可修改截止时间（创建后24小时内）'),
        ),
        migrations.AlterField(
            model_name='runlogupdate',
            name='update_date',
            field=models.DateField(help_text='动态日期（精确到日）'),
        ),
    ]
