# Generated by Django 4.2.30 on 2026-07-24 06:37

from django.db import migrations, models
from django.db.models import F, Q


def audit_runlog_constraints(apps, schema_editor):
    database = schema_editor.connection.alias
    RunLog = apps.get_model('runlog', 'RunLog')
    Update = apps.get_model('runlog', 'RunLogUpdate')
    logs = RunLog.objects.using(database)
    updates = Update.objects.using(database)
    valid_logs = logs.filter(
        Q(severity__in=['P0', 'P1', 'P2']) &
        Q(status__in=['in_progress', 'resolved', 'verified', 'closed', 'voided']) &
        Q(update_count__gte=0) &
        (
            Q(last_update_date__isnull=True) | Q(first_update_date__isnull=True) |
            Q(last_update_date__gte=F('first_update_date'))
        )
    )
    valid_updates = updates.filter(
        Q(sequence__gte=0) &
        Q(update_type__in=['normal', 'correction', 'supplement', 'system']) &
        (Q(is_voided=False) | ~Q(void_reason=''))
    )
    violations = {
        'invalid run logs': logs.count() - valid_logs.count(),
        'invalid run-log updates': updates.count() - valid_updates.count(),
    }
    failed = [f'{name}={count}' for name, count in violations.items() if count]
    if failed:
        raise RuntimeError('Run-log integrity audit failed: ' + ', '.join(failed))


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0010_alter_eventtypeconfig_id_alter_runlog_id_and_more'),
    ]

    operations = [
        migrations.RunPython(audit_runlog_constraints, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='runlog',
            constraint=models.CheckConstraint(check=models.Q(('severity__in', ['P0', 'P1', 'P2'])), name='runlog_severity_valid'),
        ),
        migrations.AddConstraint(
            model_name='runlog',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['in_progress', 'resolved', 'verified', 'closed', 'voided'])), name='runlog_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='runlog',
            constraint=models.CheckConstraint(check=models.Q(('update_count__gte', 0)), name='runlog_update_count_valid'),
        ),
        migrations.AddConstraint(
            model_name='runlog',
            constraint=models.CheckConstraint(check=models.Q(('last_update_date__isnull', True), ('first_update_date__isnull', True), ('last_update_date__gte', models.F('first_update_date')), _connector='OR'), name='runlog_update_date_order'),
        ),
        migrations.AddConstraint(
            model_name='runlogupdate',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 0)), name='runlog_update_sequence_valid'),
        ),
        migrations.AddConstraint(
            model_name='runlogupdate',
            constraint=models.CheckConstraint(check=models.Q(('update_type__in', ['normal', 'correction', 'supplement', 'system'])), name='runlog_update_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='runlogupdate',
            constraint=models.CheckConstraint(check=models.Q(('is_voided', False), models.Q(('void_reason', ''), _negated=True), _connector='OR'), name='runlog_update_void_reason'),
        ),
    ]
