# Generated by Django 4.2.30 on 2026-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0011_runlog_runlog_severity_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runlog',
            name='resolution',
            field=models.TextField(blank=True, default='', help_text='处理措施总结（事件解决后的最终方案总结，与动态记录不同，此处填写结案报告）'),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='responsible_user_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='verifier_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='runlogupdate',
            name='attachments',
            field=models.TextField(blank=True, default='', help_text='附件JSON，存储图片路径列表'),
        ),
        migrations.AlterField(
            model_name='runlogupdate',
            name='duty_person',
            field=models.CharField(blank=True, default='', help_text='值班人', max_length=128),
        ),
    ]
