# Generated by Django 4.2.30 on 2026-07-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0012_remove_null_from_string_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='runlogupdate',
            name='tdyw_run_lo_runlog__f96268_idx',
        ),
        migrations.AddIndex(
            model_name='runlog',
            index=models.Index(fields=['tenant_id', '-created_at', '-id'], name='runlog_t_ctime_idx'),
        ),
    ]
