# Generated by Django 4.2.30 on 2026-07-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0013_remove_runlogupdate_tdyw_run_lo_runlog__f96268_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='删除时间', null=True),
        ),
        migrations.AddField(
            model_name='runlog',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='软删除标识'),
        ),
    ]
