# Generated by Django 4.2.30 on 2026-07-22 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0003_alter_accountsignature_id_alter_signatureusage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsignature',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='最近一次赋予/替换时间'),
        ),
        migrations.AlterField(
            model_name='accountsignature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='accountsignature',
            name='disabled_at',
            field=models.DateTimeField(blank=True, help_text='停用时间', null=True),
        ),
        migrations.AlterField(
            model_name='accountsignature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='更新时间'),
        ),
        migrations.AlterField(
            model_name='signatureusage',
            name='signed_at',
            field=models.DateTimeField(help_text='服务器签署时间'),
        ),
    ]
