# Generated by Django 4.2.30 on 2026-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0004_alter_accountsignature_assigned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsignature',
            name='disabled_by_name',
            field=models.CharField(blank=True, default='', help_text='停用操作人姓名快照', max_length=100),
        ),
        migrations.AlterField(
            model_name='signatureusage',
            name='business_snapshot',
            field=models.TextField(blank=True, default='', help_text='业务快照 JSON 字符串（最小必要摘要）'),
        ),
    ]
