# Generated by Django 2.2.28 on 2026-05-29 22:17

from django.db import migrations, models
import django.db.models.deletion
import libs.mixins
import libs.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_add_tenant_id_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSwap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('from_staff_id', models.IntegerField()),
                ('from_staff_name', models.CharField(max_length=100)),
                ('to_staff_id', models.IntegerField()),
                ('to_staff_name', models.CharField(max_length=100)),
                ('from_date', models.CharField(help_text='申请人换班日期', max_length=20)),
                ('to_date', models.CharField(help_text='被换人换班日期', max_length=20)),
                ('schedule_date', models.CharField(blank=True, help_text='兼容旧字段', max_length=20, null=True)),
                ('from_shift_id', models.IntegerField()),
                ('from_shift_name', models.CharField(max_length=100)),
                ('to_shift_id', models.IntegerField()),
                ('to_shift_name', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', help_text='pending待审批, approved已通过, rejected已拒绝, cancelled已取消', max_length=20)),
                ('approved_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(max_length=20, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.User')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'tdyw_schedule_swap',
                'ordering': ('-created_at', '-id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='ScheduleSubstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('original_staff_id', models.IntegerField()),
                ('original_staff_name', models.CharField(max_length=100)),
                ('substitute_staff_id', models.IntegerField()),
                ('substitute_staff_name', models.CharField(max_length=100)),
                ('schedule_date', models.CharField(max_length=20)),
                ('shift_id', models.IntegerField()),
                ('shift_name', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', help_text='pending待审批, approved已通过, rejected已拒绝, cancelled已取消', max_length=20)),
                ('approved_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(max_length=20, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.User')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'tdyw_schedule_substitute',
                'ordering': ('-created_at', '-id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='ScheduleStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unavailable_dates', models.TextField(default='[]', help_text='JSON数组，不可值班日期列表')),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(max_length=20, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'tdyw_schedule_staff',
                'ordering': ('-id',),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='ScheduleShiftTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('shift_id', models.IntegerField()),
                ('shift_name', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(max_length=20, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'tdyw_schedule_shift_time',
                'ordering': ('sort_order', 'id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='ScheduleShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('work_days', models.IntegerField(blank=True, help_text='工作天数', null=True)),
                ('rest_days', models.IntegerField(blank=True, help_text='休息天数', null=True)),
                ('shift_type', models.CharField(help_text='班次类型: work_rest(上X休Y), custom(自定义)', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, help_text='颜色标记', max_length=20, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(max_length=20, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'tdyw_schedule_shift',
                'ordering': ('-id',),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('staff_id', models.IntegerField()),
                ('staff_name', models.CharField(max_length=100)),
                ('schedule_date', models.CharField(max_length=20)),
                ('shift_id', models.IntegerField()),
                ('shift_name', models.CharField(max_length=100)),
                ('shift_time_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(max_length=20, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'tdyw_schedule',
                'ordering': ('schedule_date', 'id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.AddIndex(
            model_name='scheduleswap',
            index=models.Index(fields=['tenant_id', 'from_date', 'to_date'], name='idx_swap_tnt_dates'),
        ),
        migrations.AddIndex(
            model_name='scheduleswap',
            index=models.Index(fields=['from_staff_id', 'to_staff_id'], name='idx_swap_staffs'),
        ),
        migrations.AddIndex(
            model_name='scheduleswap',
            index=models.Index(fields=['status'], name='idx_swap_status'),
        ),
        migrations.AddIndex(
            model_name='scheduleswap',
            index=models.Index(fields=['from_date', 'to_date'], name='idx_swap_dates'),
        ),
        migrations.AddIndex(
            model_name='schedulesubstitute',
            index=models.Index(fields=['tenant_id', 'schedule_date', 'status'], name='idx_sub_tnt_date_stat'),
        ),
        migrations.AddIndex(
            model_name='schedulesubstitute',
            index=models.Index(fields=['original_staff_id', 'substitute_staff_id'], name='idx_sub_staffs'),
        ),
        migrations.AddIndex(
            model_name='schedulesubstitute',
            index=models.Index(fields=['schedule_date'], name='idx_sub_date'),
        ),
        migrations.AddIndex(
            model_name='schedulesubstitute',
            index=models.Index(fields=['status'], name='idx_sub_status'),
        ),
        migrations.AddIndex(
            model_name='schedulestaff',
            index=models.Index(fields=['tenant_id', 'is_active'], name='idx_staff_tnt_active'),
        ),
        migrations.AddIndex(
            model_name='schedulestaff',
            index=models.Index(fields=['user_id'], name='idx_staff_user'),
        ),
        migrations.AddIndex(
            model_name='scheduleshifttime',
            index=models.Index(fields=['tenant_id', 'shift_id'], name='idx_st_tnt_shift'),
        ),
        migrations.AddIndex(
            model_name='scheduleshifttime',
            index=models.Index(fields=['shift_id'], name='idx_st_shift'),
        ),
        migrations.AddIndex(
            model_name='scheduleshift',
            index=models.Index(fields=['tenant_id'], name='idx_shift_tnt'),
        ),
        migrations.AddIndex(
            model_name='scheduleshift',
            index=models.Index(fields=['is_default'], name='idx_shift_default'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['tenant_id', 'schedule_date', 'staff_id'], name='idx_sched_tnt_date_staff'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['schedule_date', 'staff_id'], name='idx_sched_date_staff'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['staff_id'], name='idx_sched_staff'),
        ),
    ]
