# Generated by Django 2.2.28 on 2026-06-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('schedule_date', 'id'), 'verbose_name': '排班表', 'verbose_name_plural': '排班表'},
        ),
        migrations.AlterModelOptions(
            name='scheduleshift',
            options={'ordering': ('-id',), 'verbose_name': '班次规则', 'verbose_name_plural': '班次规则'},
        ),
        migrations.AlterModelOptions(
            name='scheduleshifttime',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': '班次时间配置', 'verbose_name_plural': '班次时间配置'},
        ),
        migrations.AlterModelOptions(
            name='schedulestaff',
            options={'ordering': ('-id',), 'verbose_name': '排班人员', 'verbose_name_plural': '排班人员'},
        ),
        migrations.AlterModelOptions(
            name='schedulesubstitute',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': '替班记录', 'verbose_name_plural': '替班记录'},
        ),
        migrations.AlterModelOptions(
            name='scheduleswap',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': '换班记录', 'verbose_name_plural': '换班记录'},
        ),
    ]
