# Generated by Django 2.2.28 on 2026-05-29 22:17

from django.db import migrations, models
import django.db.models.deletion
import libs.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_add_tenant_id_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, default='', help_text='租户标识', max_length=50)),
                ('name', models.CharField(max_length=100, verbose_name='清单名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='清单描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认清单')),
                ('created_at', models.CharField(max_length=20, verbose_name='创建时间')),
                ('updated_at', models.CharField(blank=True, max_length=20, null=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'tdyw_upgrade_checklists',
                'ordering': ('-is_default', 'name', '-id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='UpgradeChecklistStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, default='', help_text='租户标识', max_length=50)),
                ('checklist_id', models.IntegerField(verbose_name='关联清单ID')),
                ('title', models.CharField(max_length=200, verbose_name='步骤标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='步骤描述')),
                ('sequence', models.IntegerField(default=0, verbose_name='排序序号')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必执行')),
                ('created_at', models.CharField(max_length=20, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'tdyw_upgrade_checklist_steps',
                'ordering': ('checklist_id', 'sequence', 'id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='UpgradeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, default='', help_text='租户标识', max_length=50)),
                ('upgrade_no', models.CharField(max_length=50)),
                ('system', models.CharField(max_length=100)),
                ('upgrade_type', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=100)),
                ('upgrade_time', models.CharField(max_length=20, verbose_name='升级时间')),
                ('status', models.CharField(default='处理中', max_length=20)),
                ('owner', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=20, verbose_name='创建时间')),
                ('updated_at', models.CharField(blank=True, max_length=20, null=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'tdyw_upgrade_records',
                'ordering': ('-upgrade_time', '-id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='UpgradeRecordStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, default='', help_text='租户标识', max_length=50)),
                ('upgrade_id', models.IntegerField(verbose_name='关联升级表单ID')),
                ('checklist_id', models.IntegerField(default=0, verbose_name='来源清单ID（0为手动添加）')),
                ('title', models.CharField(max_length=200, verbose_name='步骤标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='步骤描述')),
                ('sequence', models.IntegerField(default=0, verbose_name='排序序号')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必执行')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('completed', '已完成'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='执行状态')),
                ('completed_by', models.CharField(blank=True, default='', max_length=100, verbose_name='完成人')),
                ('completed_at', models.CharField(blank=True, default='', max_length=20, verbose_name='完成时间')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.CharField(max_length=20, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'tdyw_upgrade_record_steps',
                'ordering': ('upgrade_id', 'sequence', 'id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='UpgradeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, default='', help_text='租户标识', max_length=50)),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('system', models.CharField(blank=True, default='', max_length=100, verbose_name='系统')),
                ('upgrade_type', models.CharField(blank=True, default='', max_length=50, verbose_name='升级类型')),
                ('version', models.CharField(blank=True, default='', max_length=100, verbose_name='默认版本')),
                ('owner', models.CharField(blank=True, default='', max_length=100, verbose_name='负责人')),
                ('status', models.CharField(default='处理中', max_length=20, verbose_name='默认状态')),
                ('detail_content', models.TextField(blank=True, default='', verbose_name='默认记录内容')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认模板')),
                ('created_at', models.CharField(max_length=20, verbose_name='创建时间')),
                ('updated_at', models.CharField(blank=True, max_length=20, null=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'tdyw_upgrade_templates',
                'ordering': ('-is_default', 'name', '-id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.AddIndex(
            model_name='upgraderecordstep',
            index=models.Index(fields=['upgrade_id'], name='tdyw_upgrad_upgrade_e5a7f6_idx'),
        ),
        migrations.AddIndex(
            model_name='upgraderecordstep',
            index=models.Index(fields=['tenant_id', 'upgrade_id'], name='tdyw_upgrad_tenant__4a6b6b_idx'),
        ),
        migrations.AddField(
            model_name='upgraderecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User'),
        ),
        migrations.AddField(
            model_name='upgraderecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User'),
        ),
        migrations.AddIndex(
            model_name='upgradecheckliststep',
            index=models.Index(fields=['checklist_id'], name='tdyw_upgrad_checkli_3f30be_idx'),
        ),
        migrations.AddIndex(
            model_name='upgradecheckliststep',
            index=models.Index(fields=['tenant_id', 'checklist_id'], name='tdyw_upgrad_tenant__204500_idx'),
        ),
        migrations.AddField(
            model_name='upgradechecklist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User'),
        ),
        migrations.AddIndex(
            model_name='upgradetemplate',
            index=models.Index(fields=['tenant_id'], name='tdyw_upgrad_tenant__ceb441_idx'),
        ),
        migrations.AddIndex(
            model_name='upgraderecord',
            index=models.Index(fields=['tenant_id', 'status'], name='tdyw_upgrad_tenant__f711da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='upgraderecord',
            unique_together={('tenant_id', 'upgrade_no')},
        ),
        migrations.AddIndex(
            model_name='upgradechecklist',
            index=models.Index(fields=['tenant_id'], name='tdyw_upgrad_tenant__2298e2_idx'),
        ),
    ]
