# Generated by Django 2.2.28 on 2026-06-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upgradechecklist',
            options={'ordering': ('-is_default', 'name', '-id'), 'verbose_name': '升级步骤清单', 'verbose_name_plural': '升级步骤清单'},
        ),
        migrations.AlterModelOptions(
            name='upgradecheckliststep',
            options={'ordering': ('checklist_id', 'sequence', 'id'), 'verbose_name': '清单步骤项', 'verbose_name_plural': '清单步骤项'},
        ),
        migrations.AlterModelOptions(
            name='upgraderecord',
            options={'ordering': ('-upgrade_time', '-id'), 'verbose_name': '升级记录', 'verbose_name_plural': '升级记录'},
        ),
        migrations.AlterModelOptions(
            name='upgraderecordstep',
            options={'ordering': ('upgrade_id', 'sequence', 'id'), 'verbose_name': '升级记录步骤', 'verbose_name_plural': '升级记录步骤'},
        ),
        migrations.AlterModelOptions(
            name='upgradetemplate',
            options={'ordering': ('-is_default', 'name', '-id'), 'verbose_name': '升级模板', 'verbose_name_plural': '升级模板'},
        ),
        migrations.AlterField(
            model_name='upgraderecord',
            name='tenant_id',
            field=models.CharField(default='', help_text='租户标识', max_length=50),
        ),
    ]
