# Generated by Django 4.2.30 on 2026-07-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0008_status_log_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgradestatuslog',
            name='action',
            field=models.CharField(choices=[('start', '升级启动'), ('backup', '备份完成'), ('gray_release', '灰度发布完成'), ('full_release', '全量发布完成'), ('test', '升级测试完成'), ('test_pass', '测试通过'), ('test_fail', '测试失败'), ('rollback', '回退'), ('pause', '暂停'), ('resume', '继续'), ('observe', '观察完成'), ('complete', '升级完成')], max_length=20, verbose_name='动作类型'),
        ),
    ]
