# Generated by Codex on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0009_status_log_action_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgradestatuslog',
            name='action',
            field=models.CharField(
                choices=[
                    ('start', '升级启动'),
                    ('backup', '备份完成'),
                    ('gray_release', '灰度发布完成'),
                    ('full_release', '全量发布完成'),
                    ('test', '升级测试完成'),
                    ('test_pass', '升级测试通过'),
                    ('test_fail', '升级测试失败'),
                    ('rollback', '回退'),
                    ('pause', '暂停'),
                    ('resume', '继续'),
                    ('observe', '观察完成'),
                    ('complete', '升级完成'),
                ],
                max_length=20,
                verbose_name='动作类型',
            ),
        ),
    ]
