# Generated by Django 4.2.30 on 2026-07-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0012_upgrade_system'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='upgradeplanstep',
            index=models.Index(fields=['tenant_id', 'template_id', 'sequence', 'id'], name='upg_plan_tenant_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='upgraderecord',
            index=models.Index(fields=['tenant_id', 'upgrade_time', 'id'], name='upg_rec_time_idx'),
        ),
        migrations.AddIndex(
            model_name='upgraderecord',
            index=models.Index(fields=['tenant_id', 'status', 'upgrade_time', 'id'], name='upg_rec_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='upgraderecord',
            index=models.Index(fields=['tenant_id', 'upgrade_type', 'upgrade_time', 'id'], name='upg_rec_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='upgraderecordstep',
            index=models.Index(fields=['tenant_id', 'upgrade_id', 'sequence', 'id'], name='upg_step_tenant_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='upgradestatuslog',
            index=models.Index(fields=['tenant_id', 'upgrade_id', 'event_seq', 'id'], name='upg_log_tenant_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='upgradesystem',
            index=models.Index(fields=['tenant_id', 'is_active', 'sort_order', 'name'], name='upg_sys_active_idx'),
        ),
        migrations.AddIndex(
            model_name='upgradetemplate',
            index=models.Index(fields=['tenant_id', 'is_default', 'name', 'id'], name='upg_tpl_default_idx'),
        ),
    ]
