# Generated by Django 4.2.30 on 2026-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0015_alter_upgradeplanstep_id_alter_upgraderecord_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgradeplanstep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='upgraderecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='upgraderecord',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='upgraderecord',
            name='upgrade_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='计划升级时间'),
        ),
        migrations.AlterField(
            model_name='upgraderecordstep',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='upgraderecordstep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='upgradestatuslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='upgradesystem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='upgradesystem',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='upgradetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='upgradetemplate',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新时间'),
        ),
    ]
