# Generated by Django 4.2.30 on 2026-07-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0018_status_log_phase_outcome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upgradetemplate',
            options={'ordering': ('name', '-id'), 'verbose_name': '升级方案', 'verbose_name_plural': '升级方案'},
        ),
        migrations.RemoveIndex(
            model_name='upgradetemplate',
            name='upg_tpl_default_idx',
        ),
        migrations.RemoveField(
            model_name='upgraderecord',
            name='version',
        ),
        migrations.RemoveField(
            model_name='upgradetemplate',
            name='detail_content',
        ),
        migrations.RemoveField(
            model_name='upgradetemplate',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='upgradetemplate',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='upgradetemplate',
            name='status',
        ),
        migrations.RemoveField(
            model_name='upgradetemplate',
            name='version',
        ),
        migrations.AddIndex(
            model_name='upgradetemplate',
            index=models.Index(fields=['tenant_id', 'name', 'id'], name='upg_tpl_name_idx'),
        ),
    ]
