# Generated by Django 4.2.30 on 2026-07-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0019_alter_upgradetemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgraderecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='删除时间', null=True),
        ),
        migrations.AddField(
            model_name='upgraderecord',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='软删除标识'),
        ),
        migrations.AddField(
            model_name='upgraderecordstep',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='删除时间', null=True),
        ),
        migrations.AddField(
            model_name='upgraderecordstep',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='软删除标识'),
        ),
        migrations.AddField(
            model_name='upgradesystem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='删除时间', null=True),
        ),
        migrations.AddField(
            model_name='upgradesystem',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='软删除标识'),
        ),
    ]
