# Generated by Django 4.2.30 on 2026-07-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0020_upgraderecord_deleted_at_upgraderecord_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='upgraderecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='upgraderecord',
            name='upgrade_no',
        ),
    ]
