# Generated by Django 2.2.28 on 2026-05-29 22:17

from django.db import migrations, models
import django.db.models.deletion
import libs.mixins
import libs.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_add_tenant_id_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('device_sn', models.CharField(help_text='设备资产编号，全局唯一', max_length=50, unique=True)),
                ('device_name', models.CharField(help_text='设备名称', max_length=50)),
                ('device_model', models.CharField(help_text='设备型号', max_length=50)),
                ('frequency', models.CharField(blank=True, help_text='工作频率', max_length=30, null=True)),
                ('call_sign', models.CharField(blank=True, help_text='设备呼号', max_length=30, null=True)),
                ('install_location', models.CharField(help_text='安装地点', max_length=200)),
                ('geo_coordinate', models.CharField(blank=True, help_text='安装经纬度，格式: 经度,纬度', max_length=100, null=True)),
                ('device_purpose', models.TextField(blank=True, help_text='设备用途', max_length=500, null=True)),
                ('manufacturer', models.CharField(help_text='生产厂家', max_length=100)),
                ('install_unit', models.CharField(help_text='安装单位', max_length=100)),
                ('use_unit', models.CharField(help_text='使用单位', max_length=100)),
                ('install_time', models.CharField(help_text='安装时间', max_length=20)),
                ('enable_time', models.CharField(help_text='启用时间', max_length=20)),
                ('current_status', models.CharField(help_text='当前设备状况：1=正常，2=故障，3=维修中，4=停用，5=报废', max_length=20)),
                ('responsible_user_id', models.IntegerField(help_text='设备负责人ID')),
                ('responsible_user_name', models.CharField(help_text='设备负责人姓名', max_length=100)),
                ('remark', models.TextField(blank=True, help_text='备注', max_length=1000, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除')),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(max_length=20, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'tdyw_device_resume',
                'ordering': ('-created_at', '-id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('device_resume_id', models.IntegerField(help_text='关联设备档案ID')),
                ('device_name', models.CharField(help_text='设备名称（冗余字段，便于查询）', max_length=100)),
                ('device_sn', models.CharField(help_text='设备编号（冗余字段，便于查询）', max_length=50)),
                ('event_type', models.IntegerField(help_text='事件类型：1=重大故障维修，2=设备更新，3=设备检修')),
                ('event_time', models.CharField(help_text='事件时间', max_length=20)),
                ('event_title', models.CharField(help_text='事件标题', max_length=100)),
                ('fault_part', models.CharField(blank=True, help_text='故障件（仅检修类型）', max_length=100, null=True)),
                ('fault_phenomenon_cause', models.TextField(blank=True, help_text='故障现象及原因（仅检修类型）', max_length=1000, null=True)),
                ('maintenance_measures', models.TextField(blank=True, help_text='检修措施（仅检修类型）', max_length=2000, null=True)),
                ('related_user_id', models.IntegerField(help_text='记录人ID')),
                ('related_user_name', models.CharField(help_text='记录人姓名', max_length=100)),
                ('repair_time', models.CharField(blank=True, help_text='修复时间（仅检修类型）', max_length=20, null=True)),
                ('remark', models.TextField(blank=True, help_text='备注', max_length=500, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除')),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'tdyw_device_event',
                'ordering': ('-event_time', '-id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.AddIndex(
            model_name='deviceresume',
            index=models.Index(fields=['tenant_id', 'current_status'], name='tdyw_device_tenant__c5b9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceresume',
            index=models.Index(fields=['tenant_id', '-created_at', '-id'], name='tdyw_device_tenant__817230_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['tenant_id', 'device_resume_id'], name='tdyw_device_tenant__808d01_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['tenant_id', '-event_time', '-id'], name='tdyw_device_tenant__384ccf_idx'),
        ),
    ]
