# Generated by Django 2.2.28 on 2026-05-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceevent',
            options={'ordering': ('-event_time', '-id'), 'verbose_name': '设备事件', 'verbose_name_plural': '设备事件'},
        ),
        migrations.AlterModelOptions(
            name='deviceresume',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': '设备档案', 'verbose_name_plural': '设备档案'},
        ),
        migrations.AlterField(
            model_name='deviceresume',
            name='responsible_user_id',
            field=models.IntegerField(blank=True, help_text='设备负责人ID（已废弃，使用负责人姓名字段）', null=True),
        ),
    ]
