# Generated by Django 2.2.28 on 2026-05-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_fix_responsible_user_id_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceevent',
            name='related_user_id',
            field=models.IntegerField(blank=True, help_text='记录人ID（已废弃，使用记录人姓名字段）', null=True),
        ),
    ]
