# Generated by Django 4.2.30 on 2026-06-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_fix_related_user_id_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceevent',
            name='device_resume_id',
            field=models.IntegerField(help_text='关联设备档案ID（逻辑外键，未使用DB外键约束）'),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='event_type',
            field=models.IntegerField(choices=[(1, '重大故障维修'), (2, '设备更新'), (3, '设备检修')], help_text='事件类型：1=重大故障维修，2=设备更新，3=设备检修'),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='是否已删除（当前为硬删除，字段预留）'),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='related_user_id',
            field=models.IntegerField(blank=True, help_text='记录人ID（已废弃，保留以兼容旧数据，新建/编辑请使用 related_user_name）', null=True),
        ),
        migrations.AlterField(
            model_name='deviceresume',
            name='current_status',
            field=models.CharField(choices=[('1', '正常'), ('2', '故障'), ('3', '维修中'), ('4', '停用'), ('5', '报废')], help_text='当前设备状况：1=正常，2=故障，3=维修中，4=停用，5=报废', max_length=20),
        ),
        migrations.AlterField(
            model_name='deviceresume',
            name='device_sn',
            field=models.CharField(help_text='设备资产编号，租户内唯一', max_length=50),
        ),
        migrations.AlterField(
            model_name='deviceresume',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='是否已删除（当前为硬删除，字段预留）'),
        ),
        migrations.AlterField(
            model_name='deviceresume',
            name='responsible_user_id',
            field=models.IntegerField(blank=True, help_text='设备负责人ID（已废弃，保留以兼容旧数据，新建/编辑请使用 responsible_user_name）', null=True),
        ),
        migrations.AddConstraint(
            model_name='deviceresume',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'device_sn'), name='uniq_device_resume_tenant_sn'),
        ),
    ]
