# Generated by Django 4.2.30 on 2026-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_alter_deviceevent_id_alter_deviceresume_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceevent',
            name='corrected_at',
            field=models.DateTimeField(blank=True, help_text='更正时间', null=True),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='event_time',
            field=models.DateTimeField(blank=True, help_text='事件时间', null=True),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='repair_time',
            field=models.DateTimeField(blank=True, help_text='修复时间（仅检修类型）', null=True),
        ),
        migrations.AlterField(
            model_name='deviceresume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deviceresume',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='删除时间', null=True),
        ),
        migrations.AlterField(
            model_name='deviceresume',
            name='enable_time',
            field=models.DateTimeField(blank=True, help_text='启用时间', null=True),
        ),
        migrations.AlterField(
            model_name='deviceresume',
            name='install_time',
            field=models.DateTimeField(blank=True, help_text='安装时间', null=True),
        ),
        migrations.AlterField(
            model_name='deviceresume',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
