# Generated by Django 4.2.30 on 2026-07-24 06:37

from django.db import migrations, models
from django.db.models import Q


def audit_device_constraints(apps, schema_editor):
    database = schema_editor.connection.alias
    Device = apps.get_model('device', 'DeviceResume')
    Event = apps.get_model('device', 'DeviceEvent')
    devices = Device.objects.using(database)
    events = Event.objects.using(database)
    valid_devices = devices.filter(
        Q(current_status__in=['1', '2', '3', '4', '5']) &
        (
            Q(is_deleted=False) |
            (Q(deleted_at__isnull=False) & Q(deleted_by_id__isnull=False) & ~Q(delete_reason=''))
        )
    )
    violations = {
        'invalid devices': devices.count() - valid_devices.count(),
        'invalid event types': events.exclude(event_type__in=[1, 2, 3]).count(),
    }
    failed = [f'{name}={count}' for name, count in violations.items() if count]
    if failed:
        raise RuntimeError('Device integrity audit failed: ' + ', '.join(failed))


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_alter_deviceevent_corrected_at_and_more'),
    ]

    operations = [
        migrations.RunPython(audit_device_constraints, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='deviceevent',
            constraint=models.CheckConstraint(check=models.Q(('event_type__in', [1, 2, 3])), name='device_event_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='deviceresume',
            constraint=models.CheckConstraint(check=models.Q(('current_status__in', ['1', '2', '3', '4', '5'])), name='device_current_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='deviceresume',
            constraint=models.CheckConstraint(check=models.Q(('is_deleted', False), models.Q(('deleted_at__isnull', False), ('deleted_by_id__isnull', False), models.Q(('delete_reason', ''), _negated=True)), _connector='OR'), name='device_delete_fields_valid'),
        ),
    ]
