# Generated by Django 4.2.30 on 2026-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_deviceevent_device_event_type_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceevent',
            name='fault_part',
            field=models.CharField(blank=True, default='', help_text='故障件（仅检修类型）', max_length=100),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='fault_phenomenon_cause',
            field=models.TextField(blank=True, default='', help_text='故障现象及原因（仅检修类型）', max_length=1000),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='maintenance_measures',
            field=models.TextField(blank=True, default='', help_text='检修措施（仅检修类型）', max_length=2000),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='remark',
            field=models.TextField(blank=True, default='', help_text='备注', max_length=500),
        ),
        migrations.AlterField(
            model_name='deviceresume',
            name='call_sign',
            field=models.CharField(blank=True, default='', help_text='设备呼号', max_length=30),
        ),
        migrations.AlterField(
            model_name='deviceresume',
            name='device_purpose',
            field=models.TextField(blank=True, default='', help_text='设备用途', max_length=500),
        ),
        migrations.AlterField(
            model_name='deviceresume',
            name='frequency',
            field=models.CharField(blank=True, default='', help_text='工作频率', max_length=30),
        ),
        migrations.AlterField(
            model_name='deviceresume',
            name='geo_coordinate',
            field=models.CharField(blank=True, default='', help_text='安装经纬度，格式: 经度,纬度', max_length=100),
        ),
        migrations.AlterField(
            model_name='deviceresume',
            name='remark',
            field=models.TextField(blank=True, default='', help_text='备注', max_length=1000),
        ),
    ]
