# Generated by Django 4.2.30 on 2026-07-17 20:44

from django.db import migrations, models
import django.db.models.deletion
import libs.mixins
import libs.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_role_tenant_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentDutyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_date', models.DateField(help_text='值班日期 YYYY-MM-DD')),
                ('duty_person_name', models.CharField(help_text='值班员姓名快照', max_length=100)),
                ('department_name', models.CharField(help_text='部门名称快照', max_length=100)),
                ('mains_voltage', models.CharField(blank=True, help_text='市电情况原文', max_length=50, null=True)),
                ('ups_voltage', models.CharField(blank=True, help_text='UPS 情况原文', max_length=50, null=True)),
                ('weather', models.CharField(blank=True, help_text='天气简述', max_length=50, null=True)),
                ('duty_record', models.TextField(help_text='当班情况，必填')),
                ('remark', models.TextField(blank=True, help_text='补充说明', null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('signed', '已签署'), ('void', '已作废')], default='draft', help_text='签署状态', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, help_text='乐观锁版本号，每次编辑/签署加 1')),
                ('signature_usage_id', models.BigIntegerField(blank=True, help_text='关联不可变 SignatureUsage.id', null=True, unique=True)),
                ('signed_by_name', models.CharField(blank=True, help_text='签署人姓名快照', max_length=100, null=True)),
                ('signed_at', models.CharField(blank=True, help_text='服务器签署时间', max_length=20, null=True)),
                ('signature_version', models.PositiveIntegerField(blank=True, help_text='签署时签名版本', null=True)),
                ('signature_sha256', models.CharField(blank=True, help_text='签名图片 SHA256 快照', max_length=64, null=True)),
                ('business_snapshot_hash', models.CharField(blank=True, help_text='业务快照哈希', max_length=64, null=True)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(blank=True, max_length=20, null=True)),
                ('deleted_at', models.CharField(blank=True, help_text='非空表示已软删除', max_length=20, null=True)),
                ('voided_at', models.CharField(blank=True, max_length=20, null=True)),
                ('void_reason', models.CharField(blank=True, help_text='作废原因，必填', max_length=500, null=True)),
                ('created_by', models.ForeignKey(help_text='创建人', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.user')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.user')),
                ('duty_person', models.ForeignKey(help_text='值班员，固定为创建时的当前登录用户', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.user')),
                ('signed_by', models.ForeignKey(blank=True, help_text='签署人，必须与值班员一致', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.user')),
                ('supersedes', models.ForeignKey(blank=True, help_text='更正时指向被更正的已作废记录', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='department_duty_log.departmentdutylog')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.user')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.user')),
            ],
            options={
                'verbose_name': '部门值班日志',
                'verbose_name_plural': '部门值班日志',
                'db_table': 'tdyw_department_duty_log',
                'ordering': ('-duty_date', '-id'),
                'indexes': [models.Index(fields=['status', 'deleted_at', 'duty_date'], name='department_duty_status_date_ix'), models.Index(fields=['duty_person', 'duty_date'], name='department_duty_person_date_ix')],
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
    ]
