# Generated by Django 4.2.30 on 2026-07-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_duty_log', '0001_init_department_duty_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentdutylog',
            name='department_name',
        ),
        migrations.AlterField(
            model_name='departmentdutylog',
            name='mains_voltage',
            field=models.CharField(blank=True, help_text='市电电压原文', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='departmentdutylog',
            name='ups_voltage',
            field=models.CharField(blank=True, help_text='UPS电压原文', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='departmentdutylog',
            name='weather',
            field=models.CharField(blank=True, help_text='天气情况简述', max_length=50, null=True),
        ),
    ]
