# Generated by Django 4.2.30 on 2026-07-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_duty_log', '0002_remove_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentdutylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
