# Generated by Django 4.2.30 on 2026-07-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_duty_log', '0003_alter_departmentdutylog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentdutylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='departmentdutylog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='非空表示已软删除', null=True),
        ),
        migrations.AlterField(
            model_name='departmentdutylog',
            name='signed_at',
            field=models.DateTimeField(blank=True, help_text='服务器签署时间', null=True),
        ),
        migrations.AlterField(
            model_name='departmentdutylog',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departmentdutylog',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
