# Generated by Django 4.2.30 on 2026-07-24 06:37

from django.db import migrations, models
from django.db.models import Q


def audit_duty_log_constraints(apps, schema_editor):
    DutyLog = apps.get_model('department_duty_log', 'DepartmentDutyLog')
    records = DutyLog.objects.using(schema_editor.connection.alias)
    valid_signature = (
        Q(status='draft') |
        (
            Q(signature_usage_id__isnull=False) & Q(signed_by_id__isnull=False) &
            Q(signed_at__isnull=False) & Q(signature_version__isnull=False) &
            Q(signed_by_name__isnull=False) & ~Q(signed_by_name='') &
            Q(signature_sha256__isnull=False) & ~Q(signature_sha256='') &
            Q(business_snapshot_hash__isnull=False) & ~Q(business_snapshot_hash='')
        )
    )
    valid_void = ~Q(status='void') | (
        Q(voided_at__isnull=False) & Q(voided_by_id__isnull=False) &
        Q(void_reason__isnull=False) & ~Q(void_reason='')
    )
    valid = records.filter(
        Q(status__in=['draft', 'signed', 'void']) & Q(version__gte=1) &
        valid_signature & valid_void
    )
    invalid = records.count() - valid.count()
    if invalid:
        raise RuntimeError(f'Duty-log integrity audit failed: invalid rows={invalid}')


class Migration(migrations.Migration):

    dependencies = [
        ('department_duty_log', '0004_alter_departmentdutylog_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(audit_duty_log_constraints, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='departmentdutylog',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'signed', 'void'])), name='duty_log_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='departmentdutylog',
            constraint=models.CheckConstraint(check=models.Q(('version__gte', 1)), name='duty_log_version_valid'),
        ),
        migrations.AddConstraint(
            model_name='departmentdutylog',
            constraint=models.CheckConstraint(check=models.Q(('status', 'draft'), models.Q(('signature_usage_id__isnull', False), ('signed_by_id__isnull', False), ('signed_at__isnull', False), ('signature_version__isnull', False), models.Q(('signed_by_name__isnull', True), _negated=True), models.Q(('signed_by_name', ''), _negated=True), models.Q(('signature_sha256__isnull', True), _negated=True), models.Q(('signature_sha256', ''), _negated=True), models.Q(('business_snapshot_hash__isnull', True), _negated=True), models.Q(('business_snapshot_hash', ''), _negated=True)), _connector='OR'), name='duty_log_signature_fields'),
        ),
        migrations.AddConstraint(
            model_name='departmentdutylog',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'void'), _negated=True), models.Q(('voided_at__isnull', False), ('voided_by_id__isnull', False), models.Q(('void_reason__isnull', True), _negated=True), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='duty_log_void_fields'),
        ),
    ]
