# Generated by Django 4.2.30 on 2026-07-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department_duty_log', '0005_departmentdutylog_duty_log_status_valid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentdutylog',
            name='mains_voltage',
        ),
        migrations.RemoveField(
            model_name='departmentdutylog',
            name='ups_voltage',
        ),
    ]
