# Generated by Django 4.2.30 on 2026-07-29 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_active_username_unique'),
        ('department_duty_log', '0006_remove_voltage_fields'),
    ]

    operations = [
        # 移除旧约束（0005 创建，含 void 选项）
        migrations.RemoveConstraint(
            model_name='departmentdutylog',
            name='duty_log_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='departmentdutylog',
            name='duty_log_void_fields',
        ),
        # 移除 void 字段（0001 创建）
        migrations.RemoveField(
            model_name='departmentdutylog',
            name='void_reason',
        ),
        migrations.RemoveField(
            model_name='departmentdutylog',
            name='voided_at',
        ),
        migrations.RemoveField(
            model_name='departmentdutylog',
            name='voided_by',
        ),
        # 更新 help_text / choices
        migrations.AlterField(
            model_name='departmentdutylog',
            name='duty_person',
            field=models.ForeignKey(help_text='值班人员，固定为创建时的当前登录用户', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.user'),
        ),
        migrations.AlterField(
            model_name='departmentdutylog',
            name='duty_person_name',
            field=models.CharField(help_text='值班人员姓名快照', max_length=100),
        ),
        migrations.AlterField(
            model_name='departmentdutylog',
            name='signed_by',
            field=models.ForeignKey(blank=True, help_text='签署人，必须与值班人员一致', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.user'),
        ),
        migrations.AlterField(
            model_name='departmentdutylog',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('signed', '已签署')], default='draft', help_text='签署状态', max_length=20),
        ),
        migrations.AlterField(
            model_name='departmentdutylog',
            name='supersedes',
            field=models.ForeignKey(blank=True, help_text='更正时指向被更正的记录', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='department_duty_log.departmentdutylog'),
        ),
        # 添加新的 status 约束（不含 void）
        migrations.AddConstraint(
            model_name='departmentdutylog',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'signed'])), name='duty_log_status_valid'),
        ),
    ]
