# Generated by Django 4.2.30 on 2026-07-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_duty_log', '0007_remove_void_fields_and_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='departmentdutylog',
            name='duty_log_signature_fields',
        ),
        migrations.AlterField(
            model_name='departmentdutylog',
            name='business_snapshot_hash',
            field=models.CharField(blank=True, default='', help_text='业务快照哈希', max_length=64),
        ),
        migrations.AlterField(
            model_name='departmentdutylog',
            name='remark',
            field=models.TextField(blank=True, default='', help_text='上级工作要求'),
        ),
        migrations.AlterField(
            model_name='departmentdutylog',
            name='signature_sha256',
            field=models.CharField(blank=True, default='', help_text='签名图片 SHA256 快照', max_length=64),
        ),
        migrations.AlterField(
            model_name='departmentdutylog',
            name='signed_by_name',
            field=models.CharField(blank=True, default='', help_text='签署人姓名快照', max_length=100),
        ),
        migrations.AlterField(
            model_name='departmentdutylog',
            name='weather',
            field=models.CharField(blank=True, default='', help_text='天气情况简述', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='departmentdutylog',
            constraint=models.CheckConstraint(check=models.Q(('status', 'draft'), models.Q(('signature_usage_id__isnull', False), ('signed_by_id__isnull', False), ('signed_at__isnull', False), ('signature_version__isnull', False), models.Q(('signed_by_name', ''), _negated=True), models.Q(('signature_sha256', ''), _negated=True), models.Q(('business_snapshot_hash', ''), _negated=True)), _connector='OR'), name='duty_log_signature_fields'),
        ),
    ]
