# Generated by Django 4.2.30 on 2026-07-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_duty_log', '0008_simplify_check_constraint'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='departmentdutylog',
            index=models.Index(fields=['-duty_date', '-id'], name='duty_log_date_idx'),
        ),
    ]
