# Generated by Django 4.2.30 on 2026-07-30 13:37

from django.db import migrations, models


def clean_draft_residual_signature_fields(apps, schema_editor):
    """清除 DRAFT 记录的残留签署字段，确保新约束不会失败"""
    DepartmentDutyLog = apps.get_model('department_duty_log', 'DepartmentDutyLog')
    DepartmentDutyLog.objects.filter(status='draft').update(
        signature_usage_id=None,
        signed_by_id=None,
        signed_at=None,
        signature_version=None,
        signed_by_name='',
        signature_sha256='',
        business_snapshot_hash='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('department_duty_log', '0009_add_duty_date_index'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='departmentdutylog',
            name='duty_log_signature_fields',
        ),
        migrations.RunPython(
            clean_draft_residual_signature_fields,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='departmentdutylog',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'draft'), ('signature_usage_id__isnull', True), ('signed_by_id__isnull', True), ('signed_at__isnull', True), ('signature_version__isnull', True)), models.Q(('status', 'signed'), ('signature_usage_id__isnull', False), ('signed_by_id__isnull', False), ('signed_at__isnull', False), ('signature_version__isnull', False), models.Q(('signed_by_name', ''), _negated=True), models.Q(('signature_sha256', ''), _negated=True), models.Q(('business_snapshot_hash', ''), _negated=True), ('signed_by_id', models.F('duty_person_id'))), _connector='OR'), name='duty_log_signature_fields'),
        ),
    ]
