# Generated by Django 4.2.30 on 2026-07-30 14:53

from django.db import migrations, models


def clean_draft_charfield_residuals(apps, schema_editor):
    """清除 DRAFT 记录残留的 CharField 签署字段"""
    DepartmentDutyLog = apps.get_model('department_duty_log', 'DepartmentDutyLog')
    DepartmentDutyLog.objects.filter(status='draft').update(
        signed_by_name='',
        signature_sha256='',
        business_snapshot_hash='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('department_duty_log', '0010_remove_departmentdutylog_duty_log_signature_fields_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='departmentdutylog',
            name='duty_log_signature_fields',
        ),
        migrations.RunPython(
            clean_draft_charfield_residuals,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='departmentdutylog',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'draft'), ('signature_usage_id__isnull', True), ('signed_by_id__isnull', True), ('signed_at__isnull', True), ('signature_version__isnull', True), models.Q(('signed_by_name', ''), ('signed_by_name__isnull', True), _connector='OR'), models.Q(('signature_sha256', ''), ('signature_sha256__isnull', True), _connector='OR'), models.Q(('business_snapshot_hash', ''), ('business_snapshot_hash__isnull', True), _connector='OR')), models.Q(('status', 'signed'), ('signature_usage_id__isnull', False), ('signed_by_id__isnull', False), ('signed_at__isnull', False), ('signature_version__isnull', False), models.Q(('signed_by_name', ''), _negated=True), models.Q(('signature_sha256', ''), _negated=True), models.Q(('business_snapshot_hash', ''), _negated=True), ('signed_by_id', models.F('duty_person_id'))), _connector='OR'), name='duty_log_signature_fields'),
        ),
    ]
