# Generated by Django 2.2.28 on 2026-05-29 22:17

from django.db import migrations, models
import django.db.models.deletion
import libs.mixins
import libs.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_add_tenant_id_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('duty_person', models.CharField(help_text='值班人员', max_length=100)),
                ('reporter', models.CharField(help_text='填报人', max_length=100)),
                ('department', models.CharField(help_text='所属科室', max_length=100)),
                ('duty_date', models.CharField(help_text='值班日期', max_length=20)),
                ('duty_situation', models.TextField(blank=True, help_text='值班情况', null=True)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(max_length=20, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'tdyw_duty_records',
                'ordering': ('-duty_date', '-id'),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
    ]
