# Generated by Django 2.2.28 on 2026-06-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutyrecord',
            options={'ordering': ('-duty_date', '-id'), 'verbose_name': '值班日志', 'verbose_name_plural': '值班日志'},
        ),
    ]
