# Generated by Django 4.2.30 on 2026-07-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0002_auto_20260627_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
