# Generated by Django 4.2.30 on 2026-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0003_alter_dutyrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dutyrecord',
            name='duty_date',
            field=models.DateTimeField(blank=True, help_text='值班日期', null=True),
        ),
        migrations.AlterField(
            model_name='dutyrecord',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
