# Generated by Django 4.2.30 on 2026-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0004_alter_dutyrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyrecord',
            name='duty_situation',
            field=models.TextField(blank=True, default='', help_text='值班情况'),
        ),
    ]
