# Generated by Django 4.2.30 on 2026-07-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0005_remove_null_from_string_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dutyrecord',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
