# Generated by Django 4.2.30 on 2026-08-03 18:17

from django.db import migrations, models
import django.db.models.deletion
import libs.mixins
import libs.tenant_base_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default='', help_text='租户标识', max_length=50)),
                ('name', models.CharField(help_text='事件名称', max_length=100)),
                ('enabled', models.BooleanField(default=True, help_text='是否启用')),
                ('target_date', models.DateField(help_text='目标日')),
                ('repeat_type', models.CharField(choices=[('none', '不重复'), ('daily', '每N天'), ('weekly', '每N周'), ('monthly', '每N月'), ('yearly', '每N年')], default='none', help_text='重复类型', max_length=10)),
                ('repeat_interval', models.IntegerField(default=1, help_text='重复间隔（N天/N周/N月/N年）')),
                ('content', models.TextField(blank=True, default='', help_text='提醒正文')),
                ('recipient_users', models.TextField(default='[]', help_text='接收人JSON列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('created_by_id', models.IntegerField(blank=True, help_text='创建人ID', null=True)),
                ('created_by_name', models.CharField(default='', help_text='创建人姓名快照', max_length=100)),
                ('updated_at', models.DateTimeField(blank=True, help_text='更新时间', null=True)),
                ('updated_by_id', models.IntegerField(blank=True, help_text='更新人ID', null=True)),
                ('updated_by_name', models.CharField(default='', help_text='更新人姓名快照', max_length=100)),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标识')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='删除时间', null=True)),
                ('deleted_by_id', models.IntegerField(blank=True, help_text='删除人ID', null=True)),
                ('deleted_by_name', models.CharField(default='', help_text='删除人姓名快照', max_length=100)),
            ],
            options={
                'verbose_name': '提醒事项',
                'verbose_name_plural': '提醒事项',
                'db_table': 'tdyw_reminders',
                'ordering': ('-id',),
            },
            bases=(models.Model, libs.tenant_base_model.TenantModelMixin),
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='接收人ID')),
                ('user_name', models.CharField(default='', help_text='接收人姓名快照', max_length=100)),
                ('date_key', models.CharField(help_text='日期标识，格式 2026-08-03', max_length=10)),
                ('is_acked', models.BooleanField(default=False, help_text='是否已确认')),
                ('acked_at', models.DateTimeField(blank=True, help_text='确认时间', null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='发送时间')),
                ('reminder', models.ForeignKey(help_text='关联提醒规则', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reminder.reminder')),
            ],
            options={
                'verbose_name': '提醒事项记录',
                'verbose_name_plural': '提醒事项记录',
                'db_table': 'tdyw_reminder_logs',
                'ordering': ('-sent_at',),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['enabled', 'is_deleted'], name='wr_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderlog',
            index=models.Index(fields=['user_id', 'is_acked'], name='wr_log_user_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderlog',
            index=models.Index(fields=['date_key', 'user_id'], name='wr_log_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='reminderlog',
            constraint=models.UniqueConstraint(fields=('reminder_id', 'user_id', 'date_key'), name='uniq_weekly_reminder_log'),
        ),
    ]
