# Generated by Django 4.2.30 on 2026-08-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reminderlog',
            name='uniq_weekly_reminder_log',
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(check=models.Q(('repeat_interval__gte', 1)), name='ck_reminder_interval_gte1'),
        ),
        migrations.AddConstraint(
            model_name='reminderlog',
            constraint=models.UniqueConstraint(fields=('reminder_id', 'user_id', 'date_key'), name='uniq_reminder_log'),
        ),
        migrations.AddConstraint(
            model_name='reminderlog',
            constraint=models.CheckConstraint(check=models.Q(('is_acked', False), ('acked_at__isnull', False), _connector='OR'), name='ck_reminder_log_acked_at'),
        ),
    ]
